### ISSUE TITLE
Negative sobol indices

### ISSUE THREAD

**Issue by rJonatan** [SALib/SALib#102]
Hi,
I wonder how to interpret negative numbers for the values of sensitivity indices. For example in one of my results, a parameter x has S1 = -71.6 and ST = 0.52. Likewise I saw that the example here gives negative indices:

https://waterprogramming.wordpress.com/2013/08/05/running-sobol-sensitivity-analysis-using-salib/

I thought that Sobol sensitivity indices were by definition positive, since they are defined as a quote of two different variances (see https://en.wikipedia.org/wiki/Variance-based_sensitivity_analysis). Did I misunderstand something?

Best,
Jonatan

**Comment by jdherman** [comment]
Hi Jonatan,

You're right, in theory the indices cannot be negative. When this happens, it's for numerical reasons. Usually one of two things is responsible:

1. Too small of a sample size, and if you ran more it would all work out. Or,

2. The indices have converged, but some of them are numerically zero. For the negative values, check to see whether their confidence intervals include zero-- if so, you can safely treat them as zero.

Usually the negative values are very small, though (as in the blog post example that you mentioned). So the -71.6 is strange. If the above doesn't clear up the issue, say more about the experiment -- Sample size, number of parameters, some example indices output..

**Comment by rJonatan** [comment]
Hi,
Thank you very much Jon for the previous answer. I tried for my problem to increase the sampling size, but so far this doesn't help. I've tried with 7572 samples for 5 parameters. This is the first order results for one of the outputs:

Parameter S1 S1_conf ST ST_conf
A -0.603300 6.608846 0.390747 0.044476
B 0.211724 0.620694 0.003222 0.000722
C -8.051588 8.116296 0.510029 0.045199
D -0.560395 3.002831 0.067063 0.008499
E 0.397044 0.607408 0.003144 0.000784

As you can see, despite the large number of samples do I not only get negative indices, but also very large confidence intervals. Furthermore the total effects are sometimes smaller than the first order effects. Does anyone have a clue to the reason behind this?

**Comment by jdherman** [comment]
Ok this is strange. The ST's look good. The S1's do not.

Can you give the parameter ranges, some example code/model output, and a short description of what the model is doing? We'll have to zoom out a little bit to try to track this down.

**Comment by jdherman** [comment]
@rJonatan let's move this over to #109 , it sounds like this may be a wider issue. I'll close this one.
