### ISSUE TITLE
Documentation Morris

### ISSUE THREAD

**Issue by rJonatan** [SALib/SALib#103]
Hi,
I have a small remark on the documentation for the morris.sample function: http://salib.readthedocs.io/en/latest/api.html#method-of-morris. It says that the sampling matrix has N rows, but if I'm not misstaken, it has (D+1)*N rows. Right?

**Comment by willu47** [comment]
Hi @rJonatan - yes, you are correct.  Feel free to submit a pull request with the change if you want!    Otherwise, I can do it.

**Comment by rJonatan** [comment]
Hi @willu47. I'd be happy to let you make the change, since I'm not an active Git user for the moment.

**Comment by willu47** [comment]
Okay, sure thing.

**Comment by jdherman** [comment]
Fixed by #148
