### ISSUE TITLE
how to handle integer variables

### ISSUE THREAD

**Issue by christos-tsotskas** [SALib/SALib#112]
How could I specify integer variables for a problem? At least, how to perform the analysis on a dataset where the input variables are integers? (similarly, how about if they were finite in nature?)

**Comment by jdherman** [comment]
There is no explicit way to do integer variables, but you can always do floating point samples and round them up or down. I've talked to a few people who had success with this approach.

The input variables are always assumed to be finite, you need to specify a lower and upper bound.

**Comment by christos-tsotskas** [comment]
any examples/links?
