### ISSUE TITLE
Centering output for sobol.analyze

### ISSUE THREAD

**Issue by rJonatan** [SALib/SALib#114]
Hi,
I have a question regarding sobol.analyze: how come there is no option for automatically normalizing/centering the output? I found the following warning for the method "sobol2002" in the R-package sensitivity (https://cran.r-project.org/web/packages/sensitivity/sensitivity.pdf):

'BE CAREFUL! This estimator suffers from a conditioning problem when estimating the variances
behind the indices computations. This can seriously affect the Sobol’ indices estimates in case
of largely non-centered output. To avoid this effect, you have to center the model output before
applying "sobol2002". ...'

Would this apply also for sobol.analyze? And in addition, could this explain the issue #109?

**Comment by jdherman** [comment]
Thanks for the suggestion @rJonatan -- I had not heard of this before. It will be a while before I can get to this, but I will look into it.

**Comment by rJonatan** [comment]
Glad that the suggestion was helpful. Thank you also @jdherman for your work on SALib!
