### ISSUE TITLE
[JOSS review] paper and documentation not align

### ISSUE THREAD

**Issue by stijnvanhoey** [SALib/SALib#118]
[JOSS review](https://github.com/openjournals/joss-reviews/issues/97)

In the paper, the description is focusing on the 6 current implementations. However, the [consise API Reference](http://salib.readthedocs.io/en/stable/api.html) (I also checked `latest`) contains only 5 method API descriptions.

**Comment by willu47** [comment]
This is due to no docstring for the fractional factorial implementation #80.

**Comment by willu47** [comment]
Closed by #119
