### ISSUE TITLE
Vectorise existing functions

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#125]
Lots of the existing sample and analyze methods could be vectorized for speed. We wrote several of these before learning the full power of numpy.

**Comment by jdherman** [comment]
Let's keep this in the guidelines, but I don't think it's specific enough to make an issue out of (which is my fault in the first place). 

Besides, we've cleaned up a lot of this old code since this was written, especially for Morris and Sobol. Most things that can be vectorized, are.
