### ISSUE TITLE
Github pages site outdated

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#126]
A few issues with the main landing page for SALib that should be an easy fix:

- [x] No link to the documentation at readthedocs

Broken links: 
- [x] link to `contributing.md` points to the local directory, rather than the file in the main github repo 
- [x] ditto MIT license
- [x] ditto advanced readme 

New links:
- [x] Link to JOSS paper (once we're published!), citation instructions, example and link to doi

**Comment by jdherman** [comment]
Fixed broken links over in the `gh-pages` branch:
https://github.com/SALib/SALib/commit/5301194fe00eca171ff1768a356168f2e415ac35

We can add the JOSS paper link to this and the regular README after it's published.

**Comment by willu47** [comment]
Closed by 6417117b52ef244e85c0bc319dcf0833723856af
