### ISSUE TITLE
morris analysis method requires problem['group'] to exist

### ISSUE THREAD

**Issue by rjplevin** [SALib/SALib#127]
The sample method uses problem.get('groups') and the analysis method should, too, to avoid requiring call to set problem['group'] = None.

**Comment by willu47** [comment]
Thanks for the suggestion @rjplevin.  Would you classify this as a bug?  Does this mean that if a problem dictionary is specified which excludes a group entry, then a morris analysis will fail?

**Comment by rjplevin** [comment]
Yes, assuming 'groups' is intended to be optional, it's a bug: it raises a KeyError on evaluating problem['groups']. It such an easy fix I didn't bother with a pull request. The sample method already handles it correctly using problem.get('groups') instead.
