### ISSUE TITLE
Regression tests for morris method are not stable

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#144]
The regression tests established in the `tests/test_regression.py::MorrisTests` class have been marked with `@pytest.mark.xfail` as the approach is not stable enough to test against a fixed sensitivity estimator (many of the tests use a very small number of trajectories so that the tests are relatively quick to run, but this results in wildly varying estimators).  The natural variation in the sampling procedure means that each test run results in a different answer.

* One solution to this is to fix the random number generator seed before running the tests, but I wonder if we should stick to the principle of testing the interface rather than the implementation?
* Another option is to divide the tests into quick-running tests which test the interface, and longer tests which test the implementation is valid (e.g. the various implementations of sensitivity analysis methods correctly identify the ranking of variables for a range of test functions)

**Comment by jdherman** [comment]
Yea, there are regression tests for all of the methods. This was a little lazy of me, but it's a nice way to make sure the whole process still works after changes.

If you're up for really diving into this and replacing them with interface tests, of course that would be great. But I think it would be a whole lot of work, especially for the other methods that haven't been updated in a while.

As a short-term fix, I'd be in favor of assigning a random seed for the methods that use true random sampling.

**Comment by willu47** [comment]
Hi @jdherman, it is not a criticism. The regression tests work perfectly well *as is* for those techniques which produce stable estimates e.g. the vanilla morris we can run with 10,000 trajectories.  But the optimal trajectories approach, particularly the brute force and local approaches are computationally demanding, which means that in the time allowed to run a 'quick' regression test we cannot generate a stable estimator.

It would be best practice to specify the seed to ensure we get exactly the same answer each test.
