### ISSUE TITLE
Can I use SALib to interpret inputs used in an unsupervised cluster analysis?

### ISSUE THREAD

**Issue by ivan-marroquin** [SALib/SALib#166]
Hi all,

I read the description of SALib and made wonder how this analysis approach can be applied on the outcome from an unsupervised cluster analysis. For input, I have a matrix N x D (where N is the number of observations and D is the number of features) and usually N >> D. 

Then, to generate a cluster structure from the input data I use either Self-Organizing Maps or K-means algorithms. Both neurons nodes or cluster centers are composed of a sample vector {D_1, ..., D_n}.

So, I have the following information:
- An input matrix N x D
- The output of the model, a set of sample vectors that corresponds to either number of neurons or cluster centers
- Each sample vector has an associated categorical value which represents either the neuron number or cluster number

If SALib can be applied to this type scenario. What is the model output to be used? The sample vectors? Or, the categorical values of the neuron number or cluster center?

Many thanks for your advice,

Ivan

**Comment by jdherman** [comment]
Hi @ivan-marroquin, you can certainly apply SA for this, but you should think about what question you want to answer at the end of it. 

I'm guessing you'd be interested in the sensitivity of the classification to each feature variable. (i.e., which feature has the largest influence on the classification?) If that's true, I would recommend using the categorical cluster numbers as the output variable. This assumes that the number of clusters is fixed.

But in general I'm not sure I would recommend doing this.  A number of machine learning methods already include measures of feature importance without any additional computation. For example a decision tree classifier will do this:
http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

You would be looking at the sensitivity of a statistical method, which is a perfectly fine thing to do, but a little bit unusual for this library. Typically SA is applied to models of physical systems and their processes. 

Hope that helps,
Jon

**Comment by ivan-marroquin** [comment]
Hi Jon ,

Thanks so much for your prompt answer and clarifications. As you pointed out, I am interested in understanding what features are the most relevant for the clustering output. Searching on internet, I haven't found a paper that describes the application of SA to the outcome of unsupervised classifiers. 

I am very interested to see what kind of results I can get with SALib library. If you are interested, I will let you know how does it fly.

I also thank you for sharing the link on feature importance. That can be another alternative to explore.

Kind regards,
Ivan

**Comment by jdherman** [comment]
Sounds good @ivan-marroquin -- I will close the issue now.
