### ISSUE TITLE
First order index greater than total index

### ISSUE THREAD

**Issue by shihabkhan1** [SALib/SALib#167]
Hi, please forgive me if I ask something stupid because I am new to python. I am trying to calculate sobol indices using `saltelli.analyze` for six parameters. The problem and the results are mentioned below - 

> problem = { 
> 		'num_vars': 6,
> 		'names': ['SF', 'sigma_E', 'l00', 'DS0_', 'COV_DS', 'lc'],
> 		'bounds': [[0.5, 2],
> 				   [0.75, 2],
> 				   [0.5, 2],
> 				   [50, 65],
> 				   [0.15, 0.25],
> 				   [35, 50]]
> 	}
> N = 300 / 2400 samples
> 
> First order indices [ 0.          0.03066379  0.1585347   0.02875659  0.09111114  0.02882451]
> First order indices, confidence [ 0.          0.03554003  0.10778229  0.12605363  0.15749953  0.0234399 ]
> Total index [ 0.          0.04025687  0.63677459  0.30542551  0.59086153  0.0103497 ]
> Total index confidence [ 0.          0.02308673  0.40460797  0.1848794   0.68160624  0.00654982]

### Question 1
I am confused because I'm finding that for the sixth variable, the first order index (0.028) is greater than the total index (0.010). I'm wondering why could that be? Is that an issue in the number of samples?

### Question 2
Also, is it common to obtain sensitivity index as 0 in the case of the first variable? Or could it be because of the narrow bounds of the first variable? The awkward thing is, when I had run the same model with N = 100/ 800 samples, I was getting S1 as 0.13 and ST as 0.41. The only other difference between the two trials is that I had implemented multiprocessing through `Pool.apply_async` to reduce the computation time as below - 

`param_values = saltelli.sample(problem, 1000, calc_second_order=False)`
`result = [p.apply_async(function_VoI,args = (x,)) for x in param_values]`
`Y = np.zeros([len(param_values)])`
`new_Y = np.zeros([len(param_values)])`
`mm = 0`
`for aa in result:`
`Y[mm] = aa.get()[0]`
`new_Y[mm] = aa.get()[1]`
`mm += 1`

This `function_VoI(x)` is my function which returns a list as `[Y, new_Y]`. I carry out sensitivity studies on these two vectors separately.

**Comment by jdherman** [comment]
Hi @shihabkhan1,
First, remember that this is a process of estimating sensitivity indices from a sample. The estimates will change with sample size. As N increases, you'd expect the indices to converge to their "correct" values, and the confidence intervals to shrink to 0.

When you see a result like S1 = 0.02 and S1_conf ~= 0.02, that parameter's first-order sensitivity is basically zero for all practical purposes. (The 95% conf. interval is 0.02 +/- 0.02). And yes, it is common to have at least a few parameters with sensitivity=zero, depending on the model of course.

Where you're seeing S1 > ST, I agree that should never happen, but they're both very small and could be considered zero. You see it doesn't happen with the parameters that are actually sensitive.

In your case, the most sensitive parameters have ST ~= 0.6 +/- 0.4. In my view, those confidence intervals are too large to trust the results, and I would recommend increasing the sample size. It sounds like this might be a computationally expensive model, but do the best you can.

By the way, we have shared-memory parallelization already built into the library for the Sobol method if you're interested, see the [advanced readme](https://github.com/SALib/SALib/blob/master/README-advanced.md).

Hope that helps!

**Comment by shihabkhan1** [comment]
Thank you very much @jdherman ! That helps a lot! :) :+1: 

I'll increase the sample size and see the results!

**Comment by shihabkhan1** [comment]
Hi @jdherman , I have one more question regarding the algorithm for SA itself.

I am using `pool_applyasync` to evaluate my model and the returned results might not be in the same order as the sobol design points. Would this affect the Sobol indices calculation?

**Comment by jdherman** [comment]
Yes, this is very important, the order of the model outputs must be the same as the inputs.

**Comment by shihabkhan1** [comment]
Hi @jdherman , I'm getting much stable results with a higher number of samples as you had suggested. But for the total index calculations for one variable, the results differ a lot between the Saltelli sampling scheme and the FAST method to calculate sensitivities.

I'm mentioning my results below - 

From `sobol.analyze` with N = 1000

> First order indices [  1.65918173e-04   1.36149108e-02   1.75585911e-01   2.35868962e-01
>   -5.25802630e-02   2.81990397e-03]
> First order indices, confidence [ 0.01724389  0.06481992  0.11389829  0.32707367  0.11141319  0.05942311]
> Total index [ 0.10406984  0.15201503  0.83539868  1.45901128  1.91484967  0.15141854]
> Total index confidence [ 0.05023272  0.06316581  0.39528544  2.23674184  2.26976624  0.08838253]

From `fast.analyze` with M=4 and N=65

> First order indices [0.0022073070639167139, 0.012609954975666636, 0.21431554484312798, 0.20971251576860392, 0.090317940511996028, 0.00098587333319256443]
> Total index [0.023111753568861526, 0.054411275338461573, 0.43208878801871098, 0.44062398790460444, 0.18555616327049007, 0.016888171761815896]

As can be seen from the results, its only the total index that differs a lot. The first order indices are more or less similar. The first scheme has a much higher number of samples. The output random variable Y in both the cases and it shows more or less the same mean and standard deviation.

Can such a result be explained?

**Comment by jdherman** [comment]
Hi @shihabkhan1 
I'm only guessing here, but if you run FAST again with N=1000 (or something close to it), you should see first- and total-order results similar to Sobol.

We don't have confidence intervals for FAST in SALib, but I wouldn't expect the estimates to converge at N=65.

**Comment by shihabkhan1** [comment]
Thanks a lot @jdherman .

The API reference says for the function - 

> SALib.sample.fast_sampler.sample(problem, N, M=4)
> Generate model inputs for the Fourier Amplitude Sensitivity Test (FAST).
> 
> Returns a NumPy matrix containing the model inputs required by the Fourier Amplitude sensitivity test. **The resulting matrix contains N rows and D columns**, where D is the number of parameters. The samples generated are intended to be used by SALib.analyze.fast.analyze().

Shouldn't it be N*D rows and D columns?
