### ISSUE TITLE
S_conv

### ISSUE THREAD

**Issue by GemsHSLU** [SALib/SALib#171]
Hello together
My question is about the S_conv result.
Is my interpretation right, that you use the confidence interval to reduce the outliner of the output Y and then calculate the new S_conv with the rest Y?
And based on that, that a big difference between S_i / S_Ti and S_conv means that not enough sample N have been used?

Thank you very much for your answer!

Kind regards
Stefan Gemperle

**Comment by jdherman** [comment]
Hi Stefan,
The value given for S_conf is the half-width of the 95% confidence interval for the sensitivity indices. So, [S1 +/- S1_conf] is the 95% CI. 

This represents the fact that the sensitivity indices are estimated from a sample, and therefore have some uncertainty associated with them. If S_conf is too large, then yes it means that a larger sample size N should be used. I typically look for S_conf to be roughly 10% of the Si value, at least for the sensitive parameters. (Parameters with very small Si may have confidence intervals overlapping zero, meaning their sensitivity is not statistically significant).

Your interpretation of how S_conf is calculated is roughly correct. It is based on bootstrapping, so many resamples are taken from the existing dataset Y (with replacement), and the Si values are recalculated. That lets us estimate the mean and variance of each Si to get a confidence interval. The only difference from what you said is that the resampling is not specifically focused on reducing outliers -- it is a uniform resample with replacement from the full output Y.

Hope that helps,
Jon

**Comment by GemsHSLU** [comment]
That's great, thank you very mutch!

**Comment by GemsHSLU** [comment]
Hello Jon
I have a following question to the Interpretation of S_conf.
I made an Sobol sensitivity analysis with three variables. The results are good. It looks like I have almost no interaction.
Now the S_i value and the S_i_conf value are ok as well as the S_T and the S_T_conf value. But there is only a small difference between them. All the efects of second (x1x2,...) and third order (x1x2x3) are statistically insignificant (Conf.interval overlapping Zero). 
My question is if this automatically means that the difference between S_i and S_T is insignificant as well?
My approach was to check it with the difference. When S_T minus S_i is bigger than S_i_conf plus S_T_conf, the difference between them is significant. Otherwise it's not.

What do you think? 
Thank you very much in advance for your answer.

Kind regards
Stefan Gemperle
