### ISSUE TITLE
Question on confidence interval level

### ISSUE THREAD

**Issue by ivan-marroquin** [SALib/SALib#176]
Hi,

I would like to understand better how the confidence interval level is computed in Salib and how to interpret the result. For instance, the delta momentum uses the command: 
                       norm.ppf(0.5 + conf_level / 2) * d.std(ddof=1) 

Do you have references to suggest? Or, if you could provide an explanation.

Many thanks,

Ivan

**Comment by jdherman** [comment]
This is just the standard formula for a confidence interval: Z * standard error

The Z value comes from the ppf function. For example Z = norm.ppf(0.95) when conf_level=0.95.

The standard error is the standard deviation of estimates of the mean. The different estimates of the mean come from bootstrapping, so no additional samples are needed.

**Comment by sofianehaddad** [comment]
Hi all,

@jdherman the formulation seems strange. 
If you consider the evaluation of the confidence interval using `Z * standard_error` (and not the percentile method), evaluation of such quantity should be done by marginal, i.e. for each marginal index `i`, confidence interval is given by `Si +/- Z_i * Sigma_i` 
Where:
 - `Z_i` corresponds to the variable *Z* you introduced, 
 - `Sigma_i` is the standard error observed by marginal : `\sum_{j=1}^{B}  1 / (B - 1) * (S_i^j- S_i^*)^2` and  `S_i^* = \sum_{j=1}^{B}  1 / B   (S_i^j)`

Here some references http://www.andreasaltelli.eu/file/repository/Archer.pdf

**Comment by jdherman** [comment]
@sofianehaddad thanks for the additional explanation. This is what I meant, I was just lazy with notation:
- The confidence interval is calculated separately for each index `i`
- Many estimates of `Si` are derived from bootstrapping. For example in the Sobol method, here is how they are calculated: https://github.com/SALib/SALib/blob/master/SALib/analyze/sobol.py#L98
- The standard deviation of these `Si` values **is** the standard error, following the same calculation that you wrote above, with `N-1` degrees of freedom:
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.std.html

I hope this clears up the issue. To the best of my knowledge we are following the Archer et al. 1997 bootstrapping approach for all of the methods that have confidence intervals available.

**Comment by sofianehaddad** [comment]
@jdherman Thanks for your feedback
Agreed with the Sobol indices. I read the code too quickly (I missed `AB[r, j]` for index `j`)

For the Morris case the indices are computed similarly. However for each marginal index `j` we resample the elementary  effects *independently* (for each marginal we use rendent as described here :  https://github.com/SALib/SALib/blob/master/SALib/analyze/morris.py#L275 

Is there any reason ? Do you have any references for that purpose ?
Thanks again for time spent

**Comment by ivan-marroquin** [comment]
thanks for all this inputs.

i have this question: the confidence limit that we get for each measure, should be interpreted as being "+/- value"?

**Comment by jdherman** [comment]
@sofianehaddad The confidence intervals for Morris I implemented based on the Archer approach, but I do not have a reference for the choice to resample the EE's independently. It could be rewritten to use the same sample for all parameters, using an array similar to `r` in the Sobol code. However, for a sufficiently large sample size I wouldn't expect it to make too much of a difference (default is N=1000 bootstrap resamples).

@ivan-marroquin yes, that is the right interpretation of the confidence intervals. The values given are the half-width of the 95% CIs.
