### ISSUE TITLE
Question on how to get reproducible results

### ISSUE THREAD

**Issue by ivan-marroquin** [SALib/SALib#177]
Hi,

In order to get reproducible results, do I need to set a seed? If so, should I use something like this:
random.seed(1969)
np.random.seed(1969)

Many thanks,

Ivan

**Comment by jdherman** [comment]
For the methods that use random sampling, yes you will need to set a random seed to get reproducible results. 

I think that you should only need to set np.random.seed .... we should have removed the dependence on the regular python "random", but I am not 100% sure about that. If "random" is still used, then you will need to set both.

You can always try a small number of samples and confirm that you get the same answer after setting the seed.

Also keep in mind that some of the sampling methods (like Saltelli) are quasi-random, not random, so they are actually deterministic and will be reproducible even without setting a random seed.
