### ISSUE TITLE
add ST on delta analysis

### ISSUE THREAD

**Issue by dreamqin68** [SALib/SALib#180]
can we add ST on delta analysis as constract ? maybe there are somthing interesting.

in this tool, the sobol analysis maybe only apply to sobol' sampling.  right?

**Comment by jdherman** [comment]
Hi @dreamqin68. Unfortunately the delta moment-independent method does not calculate total-order Sobol indices. You get the first-order indices for free along the way, though. See Plischke et al. 2013 for more info: http://www.sciencedirect.com/science/article/pii/S0377221712008995

Yes, the Sobol analysis step only applies to the Saltelli sampling method (see the example in the README). Other sampling methods do not provide the specific sampling order needed by the Sobol method.
