### ISSUE TITLE
Interpratation S_conf

### ISSUE THREAD

**Issue by GemsHSLU** [SALib/SALib#181]
HelloTogether
 I have a following question to the Interpretation of S_conf.
 I made an Sobol sensitivity analysis with three variables. The results are good. It looks like I have almost no interaction.
 Now the S_i value and the S_i_conf value are ok as well as the S_T and the S_T_conf value. But there is only a small difference between them. All the efects of second (x1x2,...) and third order (x1x2x3) are statistically insignificant (Conf.interval overlapping Zero).
 My question is if this automatically means that the difference between S_i and S_T is insignificant as well?
 My approach was to check it with the difference. When S_T minus S_i is bigger than S_i_conf plus S_T_conf, the difference between them is significant. Otherwise it's not.

What do you think?
 Thank you very much in advance for your answer.

Kind regards
 Stefan Gemperle

**Comment by jdherman** [comment]
Hi Stefan, thanks for using the library. This is a good question. I would interpret the question as: how to determine if the interactions are statistically significant?

A couple of side points first. The fact that the second-order indices are insignificant is a necessary but not sufficient condition to say that ALL interactions are insignificant. (SALib does not include estimates of third-order indices). The ST estimates in principle include estimates of all higher interactions.

To formally test if S1 is statistically equal to ST, I think you would want to use a hypothesis test for the equality of two means:
http://stattrek.com/hypothesis-test/difference-in-means.aspx?Tutorial=AP

(The S1 and ST estimates given by SALib are the means of their respective sampling distributions, and the confidence intervals are 1.96*stdev).

So, I agree with the initial step of subtracting (ST - S1). But you may need to recalculate the standard error as shown in that link. First back out the values of stdev from each confidence interval (divide the value given by 1.96). Then use the formulas in the link to calculate the new SE, and perform the hypothesis test.

This is a very good question. I usually only compare the values roughly, but I hadn't thought of a formal test for whether any interactions are significant. I'll leave the issue open so you can let us know how (or if) this works!

**Comment by GemsHSLU** [comment]
Hi Jon, thank you for the advice. Your Interpretation is exactly what I was asking.

The hypothesis test works just fine. My only problem is the calculation of the DF. I'm using the Saltelli/Sobol method with three input variables. I'm taking 1'000 samples and 8'000 (N(2*D+2)) results. Then, in reference to Saltelli, you use the matrix A and the matrix Ci to calculate Si and the matrix B and the matrix Ci to calculate S_Ti. With all of them including 1000 results, therefore 3000 different results are used to calculate both.

Do I use now 8'000, 3'000 or 1'000 to calculate the DF? I tend to 3'000, but I'm not 100% sure.
What's your opinion on that?

Thanks in advance for your Support!

**Comment by jdherman** [comment]
The confidence intervals are based on the standard error of the mean for the S1 and ST estimates, and the standard error is estimated by bootstrapping:
https://github.com/SALib/SALib/blob/master/SALib/analyze/sobol.py#L98

So the DF in this case should come from the number of bootstrap resamples (100 by default), not from the sample size of the experiment itself.

**Comment by GemsHSLU** [comment]
Ah exact! I didn't thought it trough.
I made a QQ-Plot and a histogram of my simulation results. They do not look like they are normal distributed. That is why I don't think that the two-sample t-test (I think btw it is the welch-test) can be used.
I will now test if the "Wilcoxon-Mann-Withney-Test" (or "U_Test") can be used. With this test I see the problem with the data. But my approach is to compare the results of Y_A * Y_Ci (for S_i) and Y_B * Y_Ci (for S_Ti). From my point of view, a relevant difference between them means also a relevant difference between S_i and S_Ti.
If this doesn't work, maybe a data transformation of all my results will help. Maybe I can get them in a normal distribution and then calculate S_conf and so on.

**Comment by GemsHSLU** [comment]
After some more digging, I came to the conclusion that the "Welch U test" is the right one to use. Based on the work of Morten W. Fagerland and Leiv Sandvik, the Welch U test is the best option in my situation to test skewed distribution (like mine) with unequal variances and 100 samples. Especially because the Wilcoxon-Mann-Withney-Test could answer the wrong questions (see the attached papers). I would also recommend to use the Welch U test as the standard test for your SALib, at least as long as the default 100 samples are used for the bootstrapping.
http://thestatsgeek.com/2014/04/12/is-the-wilcoxon-mann-whitney-test-a-good-non-parametric-alternative-to-the-t-test/
[Supplementary_to_Performance_of_two_sample_tests.pdf](https://github.com/SALib/SALib/files/1596182/Supplementary_to_Performance_of_two_sample_tests.pdf)
[Performance_of_five_two-sample_location_tests_for_skewed_distributions.pdf](https://github.com/SALib/SALib/files/1596183/Performance_of_five_two-sample_location_tests_for_skewed_distributions.pdf)
[t-test_non-parametic_tests_and_large_studies.pdf](https://github.com/SALib/SALib/files/1596184/t-test_non-parametic_tests_and_large_studies.pdf)

**Comment by jdherman** [comment]
Makes sense, thanks for the tip. Looks like this is already implemented in scipy if you're interested:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

(setting `equal_var=False`)
