### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rnedelec** [SALib/SALib#183]
Hello,
Just a small question about python 3 support in SALib. Python 3 seems supported but there is no specific classifier "Programming Language :: Python :: 3" in the setup.cfg file. Is it an omission or is there some incompatibility with Python 3 I didn't see ? (I didn't test it but only checked with pylint --py3k).

Thank you in advance for your answer.
Regards

**Comment by jdherman** [comment]
Yes Python 3 is supported, we just don't have it explicitly stated in the setup.cfg. The [tests](https://github.com/SALib/SALib/blob/master/.travis.yml) run against 2.7 and 3.5. I've been using SALib on 3.6 for a while now with no issues.
