### ISSUE TITLE
Instead of Monte Carlo Filtering which method is suitable for factor mapping ?

### ISSUE THREAD

**Issue by orcunkoraliseri** [SALib/SALib#184]
Sobol and Monte Carlo filtering are highly costly methods but for the robustness, I am planning to analyze building energy modeling while using sensitvity analysis. According to researches monte carlo filtering is suitable to define most efficent range values of decision variables. I can not see monte carlo filtering in Salib.

Is there any other method to accomplish this task instead of MCF?

**Comment by orcunkoraliseri** [comment]
Hello again, I reached Will Usher's presentation from YouTube.

![ekran goruntusu](https://user-images.githubusercontent.com/31666573/37865865-7c136a86-2f93-11e8-85fc-0ed81a35c87e.png)

You were specifiying that DMIM method has capabilities about factor mapping?

What kind of an application you are mention about it?

Do you mind if I can get an information for it?

**Comment by jdherman** [comment]
This may have been a typo, I wouldn't consider Delta-MIM a factor mapping method. SALib doesn't have any factor mapping. I'd suggest looking into machine learning methods like CART and PRIM (patient rule induction method) which are focused on identifying subsets of the input space.
