### ISSUE TITLE
Add new method - RBD FAST

### ISSUE THREAD

**Issue by celliern** [SALib/SALib#185]
RBD–FAST is an extension of the RBD sampling technique to the FAST method, developed by Tarantola, Gatelli and Mara (2006). The interest of RBD–FAST is the use of a single frequency ω0 for the sampling of each random variable. The RBD–FAST originality is based on a randomization procedure that consists of randomly permuting the set of samples for each random variable, run the model feeding by those permuted sets of random variables and then, reorder the output according to the input permuta tion of each random variable. For each reorganized set of output, according to each input permutation, the frequency ω0 is reconstituted through the N evaluations of the model output y and the sensitivity indices for each xi may be computed as for FAST.

## Original algorithm:

Author: S. Tarantola (JRC) Joint Research Centre All rights Reserved

## Update: M. Rabouille

Add: Reordering Y according a random design X (EASI algorithm) from E Plischke. Add: Unbiased estimator from J-Y Tissot & C Prieur. Note: The estimate is less dependant on the M value which can be raised up to 10.

## References:

S. Tarantola, D. Gatelli and T. Mara (2006) Random Balance Designs for the Estimation of First Order Global Sensitivity Indices, Reliability Engineering and System Safety, 91:6, 717-727

Elmar Plischke (2010) An effective algorithm for computing global sensitivity indices (EASI) Reliability Engineering & System Safety, 95:4, 354-360. <10.1016/j.ress.2009.11.005>

Jean-Yves Tissot, Clémentine Prieur (2012) Bias correction for the estimation of sensitivity indices based on random balance designs. Reliability Engineering and System Safety, Elsevier, 107, 205-213. <10.1016/j.ress.2012.06.010>

Jeanne Goffart, Mickael Rabouille & Nathan Mendes (2015): Uncertainty and sensitivity analysis applied to hygrothermal simulation of a brick building in a hot and humid climate, Journal of Building Performance Simulation, DOI: 10.1080/19401493.2015.1112430

**Comment by jdherman** [comment]
Added by #186 , thanks again @celliern !

**Comment by matteoottaviani** [comment]
hi, sorry to bother you; is the random sampling technique for rbd_fast fixed ora I can add my samples in iput, computed through a sampling method of mine?
Thanks!
mat

**Comment by celliern** [comment]
Hi!

If I understand well your problem, you want to use a custom sampler instead of lhs.

Is salib, sampler and sensibility analysis are nos linked : you generate your sample first, and run the sa after that.

That being said, a irrelevant sampler will make the analysis irrelevant as well : be sure of what you do.

Lucky you, rbdfast is (relatively) robust : I have been able to have coherent result on badly sampled inputs.

Your call

**Comment by matteoottaviani** [comment]
Hi! thank you very much for answering :)

yes, I would need to use a custom sampler, actually a way in which I could do a kind of 'intelligent sampling' and perform SA measures on them.
Up to now I achieved using delta measures (Borgonovo) of SAlib, since it has been studied thinking of situations in which one has only given data; 
now I was wondering whether another methods of salib could be helpful in this direction.

I tried with rbdfast but I have not been able up to now; I ve got back the following error anytime:
"IndexError: too many indices for array" 
but the data are actually the same used for delta, and in that case it works!

Thanks so much,
mat

**Comment by celliern** [comment]
Can you give a minimal reproductible example of this so I can investigate to know what is leading to its error? 

⁣Nicolas Cellier​

Le 11 mai 2019 à 17:11, à 17:11, Matteo Ottaviani <notifications@github.com> a écrit:

**Comment by matteoottaviani** [comment]
Of course, thanks!

here a scratch of the code to reproduce how I get the sample from the file and I attach the mentioned file as well.
thank you,
mat

`
import numpy as np
from SALib.analyze import rbd_fast
import pickle

problem = {
    'num_vars': 15,
    'names': ['beta','R','b1','b2','g1','g2','C','eta','x','y','n1','alpha','sigma','epsilon_sigma','epsilon_mu'],
    'bounds': [[0.0, 10.0], [1.00000001, 1.1], [-2.0, 2.0],[-2.0, 2.0],[-2.0, 2.0],[-2.0, 2.0],[0.0, 5.0],
  [0.0, 1.0],
  [0.0, 0.025],
  [0.0, 0.025],
  [0.0, 1.0],
  [0.0, 100.0],
  [0.0, 1.0],
  [0.0, 0.1],
  [0, 0.1]],
}


opt=['autocorr','kurt','clustered','memory']

X_test=[]
Sii=[]
Sii2=[]
Sii3=[]

s=0
mc=2
X_te,Y_test= pickle.load(open('TESTSAMPLE1000OB_'+str(mc)+'.pkl','rb'))
predict=pickle.load(open('SURROGATE10Kmat5210000OB_'+str(mc)+str(opt[s])+'.pkl','rb'))
    
    
prediction_model=np.reshape(predict['model'],(1000,))
prediction_krig=np.reshape(predict['kriging'], (1000,))
prediction_xgboo=predict['xgboost']
X_test=np.reshape(X_te, (1000,15))
                
analyzer = rbd_fast
    
Si = analyzer.analyze(problem,X_test, prediction_model,M=10, print_to_console=True)
Si2= analyzer.analyze(problem,X_test, prediction_krig,M=10, print_to_console=False)
Si3= analyzer.analyze(problem,X_test, prediction_xgboo,M=10, print_to_console=False)
`


[surrog+test.zip](https://github.com/SALib/SALib/files/3172523/surrog%2Btest.zip)
