### ISSUE TITLE
SA for upper bound within interpolation?

### ISSUE THREAD

**Issue by thatrandomlurker** [SALib/SALib#194]
Hello all,
sorry for inquiring here. I am rather new to Python and SALib. To keep it short, I am conducting my sensitivity analysis using your library. However, I am encountering problems for the parameters that are used as indices and within a interpolation in my model. Stackoverflow is not very responsive when it comes to questions regarding SA it seems. I understand that the problem is that the model fails due to the attempt to include the sampled array for the parameter used within the interpolation. Is the inclusion of arrays intended (for other parameters this does appear to provide the sensitivity results) or is there a way to loop through the input-file-rows in order to obtain the output for all sampled parameter combinations, but one value used at the time? 

My stackoverflow post also included a simple example of the problem:
https://stackoverflow.com/questions/49668426/sensitivity-analysis-of-upper-bound-within-linear-interpolation-in-python

Thank you very much for all the effort! Your library is certainly the best one around for SA in Python.

**Comment by willu47** [comment]
Hi there, thanks for using the library!  From a quick glance at your stackoverflow question, I can see that your bounds are defined as `'bounds': [[2, 0.16]]`.  I suggest you try 'bounds': [[0.16, 2.0]]`.

**Comment by thatrandomlurker** [comment]
Hey, thanks for the fast reply. Is the bound not specified with [mean, std] when using `dists: ['norm']`?

**Comment by willu47** [comment]
Yes you are correct.  You're problem is that you are trying to make an array out of arrays - see this line:
`Y1 = np.array([0, fbY, fbY, fbY*0.5])`.  Try `Y1 = np.concatenate((fbY, fbY, fbY*0.5), axis=0)` instead.

**Comment by willu47** [comment]
Hi there,

To conduct a sensitivity analysis using SALib, you first generate an array of sample values, run these through your model to create an array of results, and then use the analyse function to perform the SA with the matching array of inputs and model results.  

It is up to you whether you iterate through each sample (row) in the input sample array, or use a numpy vector operation to compute the results "all at once".  All SALib requires is that the input array and array of model results are the same length.  The size of the input array will differ - one column for each parameter value, whereas your model results should be a 1-dimensional array, one row for each row in the input sample.

**Comment by thatrandomlurker** [comment]
Okay thank you very much, I will keep trying by writing a one-at-a-time iteration. One last question, my model produces several relevant outputs for the SA. Currently, I just `return` all (12) outputs within my model and analyze them with `Si = [sobol.analyze(problem, Y[i]) for i in range(12)]`. Does this nonetheless produce the right SA results or is that not warranted? I obtain a list of length 12 each element being the dictionary according to the documentation (S1, S1_conf, S2, S2_conf, ST, ST_conf), but for all of the outputs. It looks correct by inspection but when you said the output should be a 1-dimensional array I thought maybe the calculations are off. Thanks again for your time and the development of SALib.

**Comment by willu47** [comment]
That sounds correct. You need to call `sobol.analyze` for each and every model output you wish to investigate.
