### ISSUE TITLE
Sensitivity Analysis in Python after Transferring the model from Dymola

### ISSUE THREAD

**Issue by Amuntaseer** [SALib/SALib#199]
I want to perform a Global Sensitivity Analysis for Building Simulation in Python Interface. I am doing my Simulation in 'Dymola'. I want to Transfer the model to python and do the Sensitivity Analysis. Can anyone suggest or give me an example where the model from Dymola is transferred to python and also the sensitivity Analysis has performed?

Thank you

**Comment by willu47** [comment]
Hi @Amuntaseer. I don't think this is the right place to ask about transferring your model to Python. Maybe try StackOverflow?

However, it is not necessary for your model to be in Python to use SALib to conduct a sensitivity analysis. You can create a sample of input data for your model using SALib `sample` methods, then run your Dymola model with these data, then `analyze` your model results using SALib again.

I hope that helps.
