### ISSUE TITLE
Installation Failure :PyFMI

### ISSUE THREAD

**Issue by Amuntaseer** [SALib/SALib#201]
Hello,
I want to use the PyFMI to import my Dymola model in Python. But when I am trying to install, it is showing the following error. i am using `pip install PyFMI`

(a) `Collecting PyFMI
  Using cached https://files.pythonhosted.org/packages/cc/e5/cf5ecd0a6dcf1b1fff89e7a14de6b3d7888a35b8a2e4db22ddb3a9f9b081/PyFMI-2.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-f9wyxe_c/PyFMI/setup.py", line 172, in <module>
        raise Exception("FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.")
    Exception: FMI Library cannot be found. Please specify its location, either using the flag to the setup script '--fmil-home' or specify it using the environment variable FMIL_HOME.`

How can I solve this? Also are both PyFMI and FMPy is same ?

**Comment by jdherman** [comment]
Posted to wrong repo ?
