### ISSUE TITLE
When Morris Output is a List of Lists!

### ISSUE THREAD

**Issue by mr-ehsani** [SALib/SALib#202]
**Hello everyone,**
**Consider that this is the problem:**

problem={
                  'num_vars': 2,
                  'names': ['x1', 'x2'],
                  'bounds': [ [1,2], [1,2] ]
                    }

**And the output is a _list of lists_ like Y:**

Y=[
      [1.5, 5],
      [2, 6.5],
      [3, 7]
        ]

**We use the Morris method for generating samples:**

X=morris.sample (problem, N = 1, num_levels = 10, grid_jump = 2)

**When I use Morris analyze, using the following command;**

Si=morris.analyze (problem, X, Y, conf_level=0.95, print_to_console=True, num_levels=10, grid_jump=1)

**An error occurs which states that**

_op_vec = model_outputs.reshape(num_trajectories, trajectory_size)
ValueError: cannot reshape array of size 6 into shape (1,3)_

**Does anybody know how can I fix this problem?**

**Comment by jdherman** [comment]
You can only analyze the sensitivity of one output at a time. If `Y` is a matrix of two model outputs, then you need to extract only one column from it: `Y = Y[:,0]` for example.

This is mentioned several places in the documentation. I would also recommend setting a higher number of trajectories `N` to get reasonable results.
