### ISSUE TITLE
Handle Model Failures

### ISSUE THREAD

**Issue by dmey** [SALib/SALib#206]
In physical models where the stability of the numerical solution may be influence by a change in parameters, a change in parameter/s may lead the model to fail. As it stands, this will result in a model-output vector (Y) with fewer number of samples in the output than in the input-- i.e. using Sobol:
https://github.com/SALib/SALib/blob/3bc2ddfb50f091e5e5dd1ed4e7fae05853f150e5/SALib/analyze/sobol.py#L79-L81

Is there a way to circumnavigate this problem somehow, whilst keeping statistical meaning unchanged?

**Comment by jdherman** [comment]
See discussion #134.

The model output should have placeholders to keep the dimension the same. Exactly what those values should be is up for discussion. In the previous issue we had talked about using the mean of the other values. But that's just one option, I don't think there is an official way to handle this. (Hopefully the % of failed samples is not too large).

**Comment by dmey** [comment]
Thank you -- let me have a think if there's something else we can do about this in the next days.

**Comment by dmey** [comment]
I couldn't find much about this but I think that using the mean to fill missing values will introduce bias and may under/overestimate the impact of certain parameters over others.

A different approach may be to fill missing values due to model failures by interpolating the values from successes originating from samples close to those that lead the model to fail.

In other words, given a model `g(u,w)` where `u` and `w` are model parameters, and `Y` is the model-output vector, we could say that at the failure instance `g'`, corresponding to model-output value `Y'`, value `Y'` can be generated by interpolating the results from those parameters that are in closest proximity to those used when the model failed. In effect, you generate missing values by weighting the results from parameters closest in space with those leading the model to fail.

I haven't got time in the next few weeks to code this up but it shouldn't be too hard to implement. What do you think?

**Comment by jdherman** [comment]
You're probably right. I've never tried this in practice. Interpolating X->Y sounds like a better way to fill the missing values, at least compared to using the mean.

I don't think this functionality would need to be part of SALib. It should be fairly easy to do as a postprocessing step with scipy or the like.

**Comment by dmey** [comment]
That's fine. I'll have to handle these cases in the future so if I go down this route, I'll let you know but feel free to close this for now.

**Comment by jdherman** [comment]
Ok, thanks. I will close this, but also copy your idea into the open discussion #134 so we keep it in mind for the future.
