### ISSUE TITLE
Unable to install SALib 

### ISSUE THREAD

**Issue by valwu** [SALib/SALib#207]
When I execute 'pip install SALib'  on centOS 7, it is giving an error of "distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pyscaffold<2.6a0,>=2.5a0')".
After installed pyscaffold (2.5.2), it is giving error of "your setuptools version is too old(<12)",but my setuptools version is 39.1.0,and this is the biggest version required by tensorflow which is my  necessary.
However , everything go well on windows.

**Comment by willu47** [comment]
Have you using conda to install SALib?  E.g. `conda install SALib`? This could help avoid some of the issues with incompatible libraries.

However, this has reminded me that we need to update to the most recent versison of PyScaffold, but this will involve removing support for Python 2.

**Comment by willu47** [comment]
Try `conda install -c conda-forge SALib`

**Comment by vielxm** [comment]
Thank you wilu47 for your support, i could install SAlib with your command "conda install -c conda-forge SALib".

**Comment by willu47** [comment]
SALib>=1.3 now uses Pyscaffold 3 which removes the above issues with setuptools.
