### ISSUE TITLE
Pandas friendly structure

### ISSUE THREAD

**Issue by ConnectedSystems** [SALib/SALib#213]
Pandas DataFrames are the de facto standard for analysis purposes. It would be nice to have pandas friendly inter-operability out of the box.

**Comment by willu47** [comment]
Hi @ConnectedSystems - thanks a lot for your contribution and welcome to SALib! Adding support for pandas "out of the box" seems like a nice idea, but I think we should extend your pull request to all the methods at once.  Also, I think an `results.as_df()` method could be a neat way, either to return a pandas DataFrame containing the sensitivity analysis results, or to provide a dict to be passed into a pandas DataFrame. The former option would require adding pandas to the list of SALib requirements, which I would prefer not to do, but if you have a compelling argument, I could be persuaded!

**Comment by willu47** [comment]
Close by #214
