### ISSUE TITLE
Update to latest version of PyScaffold

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#215]
The most recent version of PyScaffold offers a number of benefits over the previous version.

Firstly, it does away with a troublesome dependency `pbr` which causes issues with conda #182 and #207 

Secondly, it reduces the duplication of `install_requires` and `requirements.txt`.

One disadvantage is the it does not support Python 2.7.

**Comment by sanjayankur31** [comment]
Hello, 

Any update on this? We're working on including SAlib in [NeuroFedora](https://neuro.fedoraproject.org) but the use of an older PyScaffold creates an issue for us currently.

Cheers!

**Comment by sanjayankur31** [comment]
Hello @willu47 : It would be really good if it could be updated to use the latest pyscaffold. I don't use it directly, but there are other tools that use it that we'd also like to include in NeuroFedora ([uncertainpy](https://github.com/simetenn/uncertainpy) is one of them).

We're proritising py3 now that py2 will soon be EOL. It'll encourage users that havent moved yet to migrate to py3 too.

Thanks very much!

**Comment by willu47** [comment]
@sanjayankur31 I've updated the pyscaffold dependency.  You can find this on the develop branch and it will be merged in soon to the master branch as the next release
