### ISSUE TITLE
Interpretation horizontal_bar_plot, covariance_plot & sample_histograms

### ISSUE THREAD

**Issue by theo20** [SALib/SALib#220]
Can you please give me some more explanation of the plots and how to interpret them? 
for example: 

the horizontal bar plot shows the mu_star. The black line in the middle is the mu_star_conf which is created by mu_star + mu_star_conf , mu_star -mu_star_conf. The mu_star_conf is obtained using boostrapping. If I want to show the error bars,  should I just use mu_star + mu_star_conf , mu_star -mu_star_conf?  
What the sample_histograms plot shows? How can I interpret the samples obtained from bootstrap in relation to Morris's results?  Thanks

**Comment by jdherman** [comment]
Yes, the `_conf` values are the half-width of the 95% CI by default. So that is the correct interpretation of the error bars.
