### ISSUE TITLE
Possibly incorrect first-order sensitivities from Ishigami function

### ISSUE THREAD

**Issue by ConnectedSystems** [SALib/SALib#224]
The commented description for the Ishigami test function states:

```python
# Non-monotonic Ishigami Function (3 parameters)
# First-order indices:
# x1: 0.3139
# x2: 0.4424
# x3: 0.0
```

I do not seem to be getting this expected result (see code snippet below).
Am I doing something wrong?

Otherwise, it would be nice to better document the conditions in which the example results are expected (e.g. sample size, sample and analysis method...)

```python
from SALib.sample import latin
from SALib.analyze import sobol
from SALib.test_functions import Ishigami
import numpy as np

seed_value = 101
num_samples = 1000

problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}

param_values = latin.sample(problem, num_samples, seed=seed_value)

Y = Ishigami.evaluate(param_values)

Si = sobol.analyze(problem, Y, print_to_console=False)

total, first, second = Si.to_df()

first
```

  | S1 | S1_conf
-- | -- | --
x1 | 0.124795 | 0.265309
x2 | 0.069378 | 0.203661
x3 | 0.112679 | 0.225504

**Comment by jdherman** [comment]
You have to use the `saltelli` sampling method to get the right cross-sampling order expected by the `sobol` analysis method. The example file shows this:
https://github.com/SALib/SALib/blob/master/examples/sobol/sobol.py

LHS could also work, but would need to be cross-sampled as in the Saltelli method. A sample size of 1000 should be enough to get close to the right S1 values, at least within the confidence intervals.

**Comment by ConnectedSystems** [comment]
Thanks for the quick reply - I think this addresses my query completely
