### ISSUE TITLE
Can SALib support spatial/temporal sensitivity analysis?

### ISSUE THREAD

**Issue by SirSharpest** [SALib/SALib#232]
Hello, 

I have been using SALib for a while now, and I am wondering if any of the methods allow for the analysis of models with respect to time and space. 

e.g. f(a) = (a*a*t)/tx 

where t and x are not input variables. 

alternatively, is it possible to analyse vector outputs rather than discrete numbers?

**Comment by jdherman** [comment]
hi @SirSharpest good question.

Formally, no. But you can treat model outputs at different timesteps / grid cells as different output variables, and pass them to the analysis methods 1 column at a time. Just keep in mind the SA methods don't know the outputs are connected in space/time, so if there are any considerations related to autocorrelation you will have to work out the details.

A few studies in the water resources field along these lines:
- https://www.hydrol-earth-syst-sci.net/17/5109/2013/hess-17-5109-2013.html
- https://onlinelibrary.wiley.com/doi/abs/10.1002/hyp.10968%4010.1111/%28ISSN%291099-1085.Kieth-Beven

**Comment by SirSharpest** [comment]
Thanks for the information, @jdherman. 

I've had a look at the first paper you've linked. Am I correct in understanding that your procedure for analysis (fig 4 and 5) was to have a fixed series of periods and space and then to calculate the morris values for each of these?

Then I don't quite understand where your root mean squared error values are derived from? 

(Apologies if this isn't the appropriate place to have this discussion,  though I can see it being useful for others if who may have similar questions)

**Comment by jdherman** [comment]
Oh good point. The parameters are changing in space, but there is only one model output (RMSE at the watershed outlet). The output is changing in time.

So in that paper the question we were asking is: how sensitive is total model error (through time) sensitive to changes in spatially distributed parameters.

In general though you could have model outputs that vary spatially, and/or parameters that vary through time, although that one seems less likely.

**Comment by SirSharpest** [comment]
Thanks for the info @jdherman, in-case anyone in future stumbles across this here was my solution: [Example of Space*Time analysis](https://i.imgur.com/2LJWcdu.png) basically I fixed x,t and looked at each parameter e.g. D(x,t). SALib worked perfectly doing it this way with Sobol analysis.
