### ISSUE TITLE
argument order for analyze.rbd_fast

### ISSUE THREAD

**Issue by j-chacon** [SALib/SALib#238]
Hi

I just found out that `analyze.rbd_fast` has a different argument order with respect to the other `analyze` functions. This one is sorted as (problem, Y, X), while the others are organised as (Problem, X, Y)

Will it be a good idea to reformat this so there is consistency in the interface?

Regards,

**Comment by ConnectedSystems** [comment]
I've gone ahead and submitted a PR to address this (see #239). I'm not a member of the SALib team but thanks from one user to another for catching this.

**Comment by willu47** [comment]
Closed by #239
