### ISSUE TITLE
Unexpected distribution of Morris samples with more than 4 grid levels

### ISSUE THREAD

**Issue by mjeanner** [SALib/SALib#248]
Hi there !

I am using SALib to run Morris sensitivity analyses, and I am facing a problem with Morris sample generation.
When using 4 grid levels, each parameter is distributed over its 4 grid levels, i.e. 0, 1/3, 2/3 and 1 when normalized. When using more grid levels, the delta value is modified accordingly but only four grid values appear in the samples.

For instance, in the following example the number of levels is set to 6:

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```python
from SALib.sample.morris import sample

#Manual definition of the problem
problem = {
 'num_vars': 8,
 'names': ['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8'],
 'groups': None,
 'bounds': [[0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0],
            [0.0, 1.0]]
}

#Generate Morris samples
param_values = sample(problem, N=1000, num_levels=6,
                      optimal_trajectories=None)
```
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

The delta value is modified accordingly, i.e. that the step for elementary effects calculation is then  0.6, but the variables only take the values 0, 0.4, 0.6 and 1, while 0.2 and 0.8 never appear. The same behavior occurs for larger number of levels as well.

Thanks a lot for your help !

Martin

**Comment by willu47** [comment]
Hi @mjeanner - thank you for the clear explanation of the problem and related issue #249.  I think this is clearly a bug which should be fixed. I will try to replicate this issue first, and then we can think through some solutions.

**Comment by willu47** [comment]
I am now investigating, and confirm that the sample using 6 levels does indeed look uneven. However, this seems strange, as one of the findings of Morris' 1991 [paper](http://www.jstor.org/stable/1269043) was that for even numbers of levels *p*, *delta = p/[2(p-1)]* guarantees a uniform distribution.

**Comment by willu47** [comment]
Hi @mjeanner - do you want to try running the code from #252 - this should fix your issue with the uneven samples.

**Comment by mjeanner** [comment]
Hi @willu47, thanks a lot for this fix - the samples are now spread on all grid levels also when num_levels>4 !

**Comment by willu47** [comment]
Great, I'll try to wrap this up and get it released in the next few days.

**Comment by jdherman** [comment]
Merged now, thanks @willu47
