### ISSUE TITLE
Question lognormal distribution

### ISSUE THREAD

**Issue by tzipperle** [SALib/SALib#250]
I have tried to create a sample with saltelli for different distriputions like in SALib v0.7.1: Group [Sampling & Nonuniform Distributions](https://waterprogramming.wordpress.com/2016/02/25/salib-v0-7-1-group-sampling-nonuniform-distributions). I understood it that the lower bound of the lognormal distribution is the mean and the second is the standard deviation. With the following code I have created a sample.

```python
problem = {
    'num_vars': 3,
    'names': ['x1', 'x2', 'x3'],
    'bounds': [[-3.14159265359, 3.14159265359],
               [5, 0.4],
               [5, 0.4]],
    'dists': ['unif', 'norm', 'lognorm']
}

# Generate samples
param_values = saltelli.sample(problem, 1000, calc_second_order=True)
```

Why is the mean of the lognormal distribution  around 160? 
![histogram](https://user-images.githubusercontent.com/6015123/58960681-f4ed6e80-87a7-11e9-8ab6-770018929638.png)

I use Windows 10 with python 3.7.1 and  SALib 1.3.6

**Comment by jdherman** [comment]
Hi @tzipperle ,

The random number generation in numpy for lognormal distributions assumes that the inputs are log-space (ln) mean and standard deviation. This lines up with the real-space mean that you're getting.

**Comment by tzipperle** [comment]
Hi @jdherman ,

Thanks for the explanation.
