### ISSUE TITLE
what happens if no model output is possible for sample vector?

### ISSUE THREAD

**Issue by arslantahir66** [SALib/SALib#255]
In some cases it has been observed that a NON LINEAR model has be not converged for a sample generated by SAlib. In this case no value of model Output is generated, how does SAlib precieve it, does for this empty output entry, does it considers the value of zero (which would be incorrect as model incovergence doesnt mean a zero value output). Or does SAlib considers it as NAN.  
1- Inany case (0 or NAN) which SAlib method would be appropriate for this application,
2-does SAlib has some internal mechanism to ignore NO output, samples and vector for sensitvity analysis.

Best Regards

**Comment by jdherman** [comment]
See previous discussion in #134  and #237 

In general you can decide what to do with missing values. SALib does not have any internal way to ignore missing values, so you will have to replace NaNs with something.
