### ISSUE TITLE
Add FAQ with answers to the most common questions to the documentation

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#258]
It would be helpful to include a more immediate link to where to get help and a FAQ on the readme and in the documentation.

- **Q.** I've already got results from my Monte Carlo simulation - which technique can I use?
  **A.** DMIM
- **Q.** I get this error when installing SALib 1.3 with Python 2.7
  **A.** SALib 1.3 onwards does not support Python 2.7
- **Q.** Can you help me with implementing my sensitivity analysis?
  **A.** Check out the examples [here](https://github.com/SALib/SALib/tree/master/examples)

**Comment by ConnectedSystems** [comment]
Added general FAQ as markdown document and in the [wiki](https://github.com/SALib/SALib/wiki/FAQ)
