### ISSUE TITLE
 SALib issue tracker #SAlib

### ISSUE THREAD

**Issue by niraj8697** [SALib/SALib#270]
Dear Jon / Wil/Salib developer,

Thank you very much for developing an open source software SAlib. I am a new user of this software & compiling it with Python for my own study. 

The Ishigami example works well for me documented here https://salib.readthedocs.io/en/latest/basics.html#an-example
However, I am not able to plot given in the attached file.. I am looking forward to plot Y (output) vs X1 / X2 same as in the attachment in [0, 1] limit.

![IMG1](https://user-images.githubusercontent.com/57362674/68135513-cab3fe80-ff49-11e9-8ece-e540fc3b1a37.JPG)

Could you please help in this regard? I will be very much thankful to you for the  same.

 

*Example code

import numpy as np
import matplotlib.pyplot as plt
from SALib.sample import saltelli
from SALib.analyze import sobol
from SALib.sample.fast_sampler import sample as fast_sampler
from SALib.analyze.fast import analyze as fast_analyzer
from SALib.test_functions import Ishigami
import matplotlib
matplotlib.rc('figure', figsize=(6, 6))

problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}
samples = fast_sampler(problem, 2000, seed=101)
np.savetxt("param_values.txt", samples)
Y = Ishigami.evaluate(samples)
Si = fast_analyzer(problem, Y, print_to_console=False)
Si.plot()

**Comment by ConnectedSystems** [comment]
Hi @niraj8697 

I'd suggest having a look at the `savvy` package (https://github.com/houghb/savvy) which may have the kind of visualization you're after.

That said, if I understand you correctly this is a relatively straight-forward plotting exercise.

```python
# ... after running the code in your example

import matplotlib.pyplot as plt

names = problem['names']
x1_inputs = samples[:, names.index('x1')]
x2_inputs = samples[:, names.index('x2')]

plt.scatter(x1_inputs, Y, marker='o', alpha=0.4)
plt.scatter(x2_inputs, Y, marker='.', alpha=0.4)
plt.xlabel("X")
plt.ylabel("Y")
```


![image](https://user-images.githubusercontent.com/4075136/68187869-ec6dbe00-fffb-11e9-80bd-4406a31eb041.png)

**Comment by niraj8697** [comment]
Thank you very much for answer. Now it's clear to me ..Fanatastic
