### ISSUE TITLE
Sobol Indices (Negative) & not matching with R Package

### ISSUE THREAD

**Issue by niraj8697** [SALib/SALib#277]
Dear user,

Recently, I faced a problem with sobol analysis results

```python
# Perform analysis
Si = sobol.analyze(problem, Y, calc_second_order=True, num_resamples=100,
            conf_level=0.95, print_to_console=True)
```

Y is attached for the reference....
The result obtained is different than R package for the same input.. ..Could any one please help me to figure out the issue ?

Salib
 Parameter S1 S1_conf ST ST_conf
x1 0.019522 0.036718 0.991004 0.042381
x2 -0.008420 0.033168 1.005745 0.041473
x3 -0.031159 0.034805 1.032269 0.055246
x4 -0.003859 0.035548 1.027899 0.046800

R results
[input.docx](https://github.com/SALib/SALib/files/3910629/input.docx)
# Model runs: 60000 

 original          bias std. error     min. c.i.  max. c.i.
X1 0.03052948 -0.0025201811 0.01530504 -3.112346e-06 0.06720971
 X2 0.45468790 -0.0032829662 0.01272489  4.332534e-01 0.48427634
 X3 0.18339427 -0.0009877617 0.01644451  1.530832e-01 0.21648349
 X4 0.32118027 -0.0017089329 0.01231835  2.984512e-01 0.34563679
## 
 Total indices:
   original          bias   std. error  min. c.i.  max. c.i.
 X1 0.01737156  3.419055e-05 0.0004438342 0.01641291 0.01818515
 X2 0.49307431 -1.390719e-04 0.0112479825 0.47084374 0.51534768
 X3 0.20720198  1.653553e-03 0.0050508063 0.19491080 0.21571724
X4 0.32220133  7.532271e-04 0.0087575178 0.30496359 0.33812582

#218

**Comment by niraj8697** [comment]
[Y.txt](https://github.com/SALib/SALib/files/3910631/Y.txt)

**Comment by ConnectedSystems** [comment]
Hello,

Could you please let me know what sampling method you used to generate the input values?

The R code you used would also be helpful.

**Comment by niraj8697** [comment]
Hi team,

The method of sampling is based on mean & standard deviation of the data ..
e.g . 
# Generate samples (LHS)
#The testing parameter mean & sd
C_m, C_sd = 1.5, 0.1
a_m, a_sd = 0.1739, 0.036
K_m, K_sd = 6.7208*10**5, 9.701*10**4
F_z_m, F_z_sd = 9.0034*10**4, 5.5803*10**3


#Sobol - generate parameter matrix
n = 60000
x1 = np.random.normal(a_m, a_sd, n)
x2 = np.random.normal(F_z_m, F_z_sd, n)
x3 = np.random.normal(K_m, K_sd, n)
x4 = np.random.normal(C_m, C_sd, n)
samples = np.array([[x1, x2, x3, x4]]).T

thanks ...

**Comment by ConnectedSystems** [comment]
Hello,

As indicated in #218 and #224 the sobol analysis method provided in SALib is not compatible with Latin Hypercube sampling at this time.

You could use Saltelli sampling, as indicated in the example.
https://github.com/SALib/SALib/blob/master/examples/sobol/sobol.py

If Latin Hypercube is necessary, then RBD-FAST is a compatible method.

Alternatively pull requests are welcome if you'd like to contribute changes to the Sobol method to support Latin Hypercube sampling.

**Comment by ConnectedSystems** [comment]
Feel free to reopen if necessary but I will go ahead and close this issue assuming that you've come to an acceptable workaround.
