### ISSUE TITLE
Analyse a set of experiments from a file

### ISSUE THREAD

**Issue by raounakloudad** [SALib/SALib#281]
Hello,

Thanks for this great library,

I have a set of experiments designed by Taguchi method stored in a file, and I would like to analyse the sensitivity of the inputs,

Could you please provide a small code that uses data from a file?

Thank you very much for your help,

**Comment by jdherman** [comment]
Assuming the experiments are the inputs (X), then only the Delta method will work. Our example for the Delta method is here: 
https://github.com/SALib/SALib/blob/master/examples/delta/delta.py

**Comment by raounakloudad** [comment]
Hi jdherman,

Thank you very much,

It works,

**Comment by raounakloudad** [comment]
Hi jdherman,

I have executed the same example several times, and each time I get slightly different results,

Is it normal that I don't get exactly the same results each time I run the program?

Thank you very much
