### ISSUE TITLE
Plotting issues with Sobol and morris method in SALib

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#282]
I am doing sensitivity analysis for an interior equilibrium point for a ecological dynamical system using SOBOL and MORRIS method and got some problems with plotting. Unfortunatley there are not many examples to make the plotting clear for people which may make the work difficlt for beginners.
First for sobol method when using `Si_df=Si.to_df()` I get a list and not a dataframe which result in error when plotting.
The error message is
 ```python
AttributeError                            Traceback (most recent call last)
<ipython-input-48-7cfc6017cf5d> in <module>
      1 Si_dfx = Si_x.to_df()
----> 2 barplot(Si_dfx)

~\Anaconda3\lib\site-packages\SALib\plotting\bar.py in plot(Si_df, ax)
     27     >>> barplot(Si_df)
     28     '''
---> 29     conf_cols = Si_df.columns.str.contains(CONF_COLUMN)
     30 
     31     confs = Si_df.loc[:, conf_cols]

AttributeError: 'list' object has no attribute 'columns'
```

Secondly when using Morris method I get an error message when plotting. The error message is:
```python
TypeError                                 Traceback (most recent call last)
<ipython-input-47-d9c47d207b18> in <module>
      1 # first plot
      2 fig=plt.figure(figsize=(15,10))
----> 3 SALib.plotting.morris.horizontal_bar_plot(ax, Si_xm, problem,sortby='mu_star', unit='')
      4 # set plot style etc.
      5 plt.show()

~\Anaconda3\lib\site-packages\SALib\plotting\morris.py in horizontal_bar_plot(ax, Si, param_dict, sortby, unit)
     54                   align='center',
     55                   ecolor='black',
---> 56                   **param_dict)
     57 
     58     ax.set_yticks(y_pos)

~\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py in barh(self, y, width, height, left, align, **kwargs)
   2594         kwargs.setdefault('orientation', 'horizontal')
   2595         patches = self.bar(x=left, height=height, width=width, bottom=y,
-> 2596                            align=align, **kwargs)
   2597         return patches
   2598 

TypeError: bar() missing 1 required positional argument: 'left'
```
My code is in the attached file.
[GSA_EP6_Nondim_Var.zip](https://github.com/SALib/SALib/files/4280588/GSA_EP6_Nondim_Var.zip)

**Comment by ConnectedSystems** [comment]
Hello,

The method you're using for your analysis is Sobol' which, by default, returns total, first order, and second order sensitivities.

For this particular analysis, `to_df()` will return a list of DataFrames; one for each above. So to access these, you would:

```python
Si = sobol.analyze(problem, Y, print_to_console=True)
total_Si, first_Si, second_Si = Si.to_df()

# OR
sensitivities = Si.to_df()
total_Si, first_Si, second_Si = sensitivities
```

This is indicated in the [docstring](https://github.com/SALib/SALib/blob/2fc1f2c9569d21a13fc414ef3d6a0ff0c271e17a/src/SALib/analyze/sobol.py#L310) for the `to_df()` method, and in the [advanced readme](https://github.com/SALib/SALib/blob/master/README-advanced.md) (at the very end)

Other methods, such as Morris, may only return a single dataframe (i.e. not a list).

In the future, we may move to returning a single dataframe with a multi-index to avoid this kind of confusion but given most novices do not know how to access dataframes with a multi-index, I decided when implementing this feature to keep it simple.

**Comment by ConnectedSystems** [comment]
Incidentally, if you're just after an indicative plot, the following will be sufficient:

```python
Si_x = sobol.analyze(problem,ep6_all[:,0])
Si_x.plot()

# You may have to adjust your figure size as well
plt.gcf().set_size_inches(16, 4)
```

**Comment by FO2020** [comment]
Thanks for quick reply.I actually read the documentation (Complete Module Reference) and didn't find that info about indexing which is mentioned in advanced readme. 
Yes ,What I want is just some indicator plots to show the results I got. Still dont't the resaon for error message regarding morris method but I do got the plot using ````barplot() ```  but not using ```morris.horizontal_bar_plot()```.

**Comment by ConnectedSystems** [comment]
The morris plotting methods are specific to the morris method. Based on the notebook you provided you are using the Sobol' method to analyze your results.

We're planning more work to improve both the documentation and the visualizations. I'll make sure this specific set of issues you had will get looked at.

If you would like to contribute changes yourself to the documentation to be clearer to other newcomers, you would be more than welcome. 

All the best and happy analyzing.

**Comment by FO2020** [comment]
Actually I used both Sobol and Morris method in the attached file. Of course I will think about that.

**Comment by ConnectedSystems** [comment]
Sorry for the confusion, seems I closed the issue too early.

From your example above (original post) and what is in the notebook you provided there are two issues with regard to the use of the `horizontal_bar_plot()` function.

Firstly, you appear to be trying to attach the barplot (a 2D plot) to an existing 3D plot.
Create a new figure and axes object instead:

```python
fig, ax1 = plt.subplots(1)
```

Secondly, the parameter dictionary is not the problem specification. It is a dictionary of additional options that will be passed to matplotlib, specifically through ["ax.barh()"](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.barh.html)

If you have no additional options to add, simply provide an empty dictionary:

```python
# Instead of:
SALib.plotting.morris.horizontal_bar_plot(ax1, Si_xm, problem, sortby='mu_star', unit='')

# Do this:
SALib.plotting.morris.horizontal_bar_plot(ax1, Si_xm, {}, sortby='mu_star', unit='')
```

**Comment by FO2020** [comment]
I appreciate your help.  I was thinking of adding the model I work with as an example of using Sobol and morris as there is only one example on SALib site, What do you think?

**Comment by ConnectedSystems** [comment]
Hello again,

I'm currently unsure what additional insight another example in the documentation would bring for the particular mix of methods you are using. That said, I think showcasing an example application of SALib - including the issues you ran into - would be very valuable. 

We could, with the approval of @jdherman or @willu47, add such content either to the GitHub wiki page for this project and/or add it to the documentation as a "recipe" or "cookbook" showcase of a specific "real" application example for other beginners to follow.

You can open a separate issue to discuss this further if this is something that interests you. 

In any case, if this issue is resolved for you, please go ahead and close it. For now, I am off to bed. Talk again shortly.
