### ISSUE TITLE
Sensitivity Analysis with respect to intermediate values

### ISSUE THREAD

**Issue by lukas1994** [SALib/SALib#290]
Hi, say I have the following setup:
```
input distributions: x1, x2
intermediate values: m1 = f1(x1, x2), m2 = f2(x1, x2)
final value: y = g(m1, m2, x1, x2)
```
SALib is doing a great job of getting the sensitivities of y with respect to x1 and x2. How would I compute the sensitivities of y with respect to m1 and m2?

**Comment by jdherman** [comment]
Hi @lukas1994 , the issue is that m1 and m2 can't be sampled independently of x1 and x2. So I think this is the same as the issue #193 about sampling correlated distributions.

The methods currently in SALib can't sample correlated inputs, although there is a PR in progress for the HDMR method, which can.

In this case if m1/m2 are computed from deterministic functions of only x1/x2, then it would be a perfect correlation -- so I guess it's not clear what the meaning of the sensitivity of m1/m2 would be anyway. but I might be missing something.

**Comment by lukas1994** [comment]
Thanks @jdherman ! Let me give you an example:
Say I have some distributions for growth rates: `growth rate business unit A`, `growth rate business unit B`
Now say, `final growth rate = 0.1 * growth rate business unit A + 0.9 growth rate business unit B + some random noise` and `revenue = 10000$ * final growth rate + other stuff`.
SALib would now be able to give me sensitivities for `revenue` with respect to `growth rate business unit A` but it won't be able to do that with respect to `final growth rate`.
Modelling this as correlated inputs could work, I'll give that a try.
Maybe feature importance algorithms would be a good fit for this situation? How would you decide between using feature importance vs sensitivity?

**Comment by ConnectedSystems** [comment]
@lukas1994 If I understand correctly, your model (say `h()`), put programmatically, is:

```python
def h(x1, x2):
    m1 = f1(x1, x2)
    m2 = f2(x1, x2)
    
    # final growth rate
    fgr = (0.1 * m1) + (0.9 * m2) + random_noise  
    revenue = 10000.0 * fgr  + other_stuff
    return revenue
```

And if the above is correct, you're asking how to apply a method to final_gr?

**Comment by lukas1994** [comment]
Yes, something like that. In my previous comment I tried to describe something like:
```
def h(x1, x2):
    growth1 = normal(0,1)
    growth2 = normal(1,3)
    
    # final growth rate
    fgr = (0.1 * growth1) + (0.9 * growth2) + random_noise  
    revenue = 10000.0 * fgr  + other_stuff
    return revenue
```

And now I want to know how important is `fgr` compared to `other_stuff` for example. Is feature importance what I'm looking for or should I rather use sensitivity analysis with correlated inputs?

**Comment by ConnectedSystems** [comment]
A potential workaround is to determine the range of `fgr` and `other_stuff` and apply SA on the last step of the function, e.g.

```python
def calc_revenue(fgr, other_stuff):
    return 10000.0 * fgr  + other_stuff
```

By Feature Importance, I assume you're refering to Random Forest? Yes, it will give you an indication of ranking however I can't speak it its appropriateness. Probably okay to do so, so long as you're able to capture the intermediate values. I would expect the correlated values to have similar rankings.

**Comment by lukas1994** [comment]
I thought about the first approach but there you would first need to estimate the distributions of `fgr` and `other_stuff` and then as a second step you could apply sensitivity.
I'll look into feature importance algorithms -- maybe that's more appropriate in this case.

Thanks!

**Comment by lukas1994** [comment]
I thought about the first approach but there you would first need to estimate the distributions of `fgr` and `other_stuff` and then as a second step you could apply sensitivity.
I'll look into feature importance algorithms -- maybe that's more appropriate in this case.

Thanks!
