### ISSUE TITLE
Why is the default value of num_resamples for Delta-MIM lower than for other methods?

### ISSUE THREAD

**Issue by TobiasKAndersen** [SALib/SALib#291]
Hi all,

Default num_resamples values for different SALib analyze methods:
Morris: num_resamples=1000
DGSM: num_resamples=1000
Sobol: num_resamples=100
Delta-MIM: num_resamples=10

Why is the default value for resamples lower for Delta-MIM (and Sobol) than Morris and DGSM?

And thanks for all the great work!

**Comment by jdherman** [comment]
Hi @TobiasKAndersen good catch, there is no reason for this. In fact 10 is too low for a bootstrap estimate, which does not add much computing time anyway. Want to submit a PR to fix this, maybe make them all = 100 to be consistent?

**Comment by ConnectedSystems** [comment]
@jdherman I can't for the life of me find the Issue or PR where this was discussed but there was talk of setting the defaults to 1000. I cannot remember the reasoning.

**Comment by jdherman** [comment]
yea I sort of remember that too. On one hand there isn't much computational cost to doing an arbitrarily large number. But at the same time there isn't much statistical reason to do that many, if the only goal is estimating a mean +/- CI. I could see it either way.

**Comment by TobiasKAndersen** [comment]
Another approach would be to not include a default value, then the user would have to consider the most optimal value for their case. But of course, this is not in line with the rest of SALib.
I would be happy to submit a PR with default num_resamples = 100

**Comment by jdherman** [comment]
Ok, 100 sounds good. Leaving it without a default might confuse people and break previous versions. Thanks for catching this.
