### ISSUE TITLE
Sobol algorithm for randomized functions

### ISSUE THREAD

**Issue by lukas1994** [SALib/SALib#292]
Can the Sobol algorithm handle randomized functions?
Say f(x,y) = x**2 + 2*y*A + x*y + A, where A is some random variable.
Can I still calculate the sensitivities of f with respect to x and y (for some input distribution of x and y)?

**Comment by jdherman** [comment]
The code will work, but I'm not sure what it would mean for interpreting the output. There will be an extra source of variance that is not accounted for in the sensitivity indices. Why not include A as another parameter to sample?

**Comment by lukas1994** [comment]
I have quite a lot of these input distributions but I only care about a few sensitivities.

**Comment by jdherman** [comment]
Ok. then I'd suggest at least adding a third parameter representing the index of the random realizations for all other variables. So you would find the sensitivity to parameters x, y, and i, where i represents the contribution to the total variance of "everything else". 

If you only care about the importance of x and y relative to each other, then you wouldn't need to do this. But I think you'd have to check if their effects are washed out by the other random variables.

**Comment by lukas1994** [comment]
That’s a great idea! Will try that. Thanks :)
