### ISSUE TITLE
Incorrect Sobol g function results?

### ISSUE THREAD

**Issue by DigitalPig** [SALib/SALib#293]
I am sure I am doing something wrong here but I cannot find where. 

I am reading the [Saltelli 2002](http://www.sciencedirect.com/science/article/pii/S0010465502002801) paper, on Page 290 Section 5, the author is testing this algorithm with Sobol G function:

![Screenshot from 2020-04-11 03-27-38](https://user-images.githubusercontent.com/97392/79038074-8128a900-7ba4-11ea-95eb-3ee9f226e7d1.png)

I am trying to repeat the author's tests using the following code:

```python
from SALib.sample import saltelli
from SALib.analyze import sobol
from SALib.test_functions import Ishigami
import numpy as np
from functools import partial

# %%
def psi(t, a):
    return (np.abs(4*t -2) + a) / (1 + a)

param_a_array = [0, 0.5, 3, 9, 99, 99]
psi_array = [partial(psi, a=i) for i in param_a_array]
def evaluate_model_p(x, func_array):
    return np.prod([v(x) for v in func_array])

# %%
problem = {
    'num_vars': 6,
    'names': ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    'bounds': [[0, 1],
               [0, 1],
               [0, 1],
               [0, 1],
               [0, 1],
               [0, 1]]
}

param_values = saltelli.sample(problem, 10000)

# %%
Y = np.zeros([param_values.shape[0]])

for i, X in enumerate(param_values):
    Y[i] = evaluate_model_p(X, psi_array)
   
# %%
Si = sobol.analyze(problem, Y)
```

The first order Sobol indices I have are:

```

Si
{'S1': array([0.008951  , 0.01900799, 0.01116865, 0.020058  , 0.01720087,
        0.0102313 ]),
 'S1_conf': array([0.00828363, 0.02171837, 0.01284479, 0.02083286, 0.01274454,
        0.00802342]),
 'ST': array([0.2934952 , 0.33114771, 0.24861919, 0.39577492, 0.32104749,
        0.31388651]),
 'ST_conf': array([0.21464042, 0.23829173, 0.18040653, 0.31523333, 0.23419328,
        0.20756677]),
```

These seem to be very different than the author's results in Fig 2:

![Screenshot from 2020-04-11 03-30-44](https://user-images.githubusercontent.com/97392/79038129-e7153080-7ba4-11ea-976f-f56320b8b3dd.png)

I saw the testing code also defines a [Sobol G function](https://github.com/SALib/SALib/blob/aea0a18ff4aebb886df06d8a285396aa024f62cd/src/SALib/test_functions/Sobol_G.py), but it is slightly different than the paper one. Is there a special reason why we use this form of g function instead of the original 2002 paper's form?

**Comment by ConnectedSystems** [comment]
Hello,

To answer your last question first, the provided test function is the modified Sobol G-function (also known as G*), as detailed in the docstring and [here](https://www-sciencedirect-com.virtual.anu.edu.au/science/article/pii/S0010465509003087?via%3Dihub).

It is an extension to the original G-function and is identical in cases where alpha and delta parameters are not specified. In such cases `alpha` is set to 1 and `delta` to 0.

![image](https://user-images.githubusercontent.com/4075136/79038556-8413b000-7c1d-11ea-9150-32bc845c82ef.png)


As for your results, I'm not sure exactly but I suspect it's something to do with your loop approach and/or the use of `partial()`.

I've mocked up the example below and get the expected results.

```python
from SALib.test_functions import Sobol_G
from SALib.sample.saltelli import sample
from SALib.analyze.sobol import analyze
import numpy as np
import matplotlib

matplotlib.rc('figure', figsize=(12, 4))

def sobol_g(t, a):
    """Original Sobol-G"""
    return np.prod((np.abs(4*t -2) + a) / (1 + a))


def run_model(vals, a):
    Y = np.empty(vals.shape[0])
    for i, t in enumerate(vals):
        Y[i] = sobol_g(t, a)
    return Y


problem = {
    'num_vars': 6,
    'names': ['x1', 'x2', 'x3', 'x4', 'x5', 'x6'],
    'bounds': [[0, 1],
               [0, 1],
               [0, 1],
               [0, 1],
               [0, 1],
               [0, 1]]
}

param_values = sample(problem, 10000)
param_a = np.array([0, 0.5, 3, 9, 99, 99])
Y = run_model(param_values, param_a)

Si = analyze(problem, Y, num_resamples=1000)

Si.plot();
```

![image](https://user-images.githubusercontent.com/4075136/79039941-26389580-7c28-11ea-8a75-46f88d5784f1.png)

**Comment by DigitalPig** [comment]
Ah. I see. My bad. The issue is indeed in the `prod` function I use. Thank you. Closing this now.
