### ISSUE TITLE
Dealing with zero standard deviation of the model output

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#295]
I am doing the sensitivity analysis for a dynamical model consisting of 3 ODE.Because the output is a time series I chose the max value as a sensitivity variable but I am getting the following error message when computing the sensitivity indices for  maximum value of x.
``
C:\Users\farha\Anaconda3\lib\site-packages\SALib\analyze\sobol.py:93: RuntimeWarning: invalid value encountered in true_divide
  Y = (Y - Y.mean()) / Y.std()
​
``
This happen because the standard deviation of the x output is zero  but what I should do get around this. The ODE solver could solve the model successfully after changing the method to explicit method of  Radau .
The complete code is in the follwing file:
[GSA _NonDim_Parameter_Without_InitialValue.zip](https://github.com/SALib/SALib/files/4465509/GSA._NonDim_Parameter_Without_InitialValue.zip)

**Comment by jdherman** [comment]
If the standard deviation of the output is zero, then the output is never changing in response to the input parameters, and so there is no way to do a sensitivity analysis.

I'd suggest (1) confirm that all of the outputs are in fact the same, and (2) if so, maybe rethink the choice of the maximum value as the output of interest. And/or (3) double check that the input parameters are actually being changed in the model (I've made this mistake many times...)

**Comment by FO2020** [comment]
Thank for your reply.
In my code I did the sensitivity for maximum value of x and mean value of x and end value of x which should be equilibrium value and for all I got NaN in the result. For Max x the output of the model is the same and so std=0 and for others the output is not the same and std is not zero but still get NaN
