### ISSUE TITLE
Sorting the results of sensitivity analysis in descending order

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#296]
Hei again.
Is it possible to add option in the analysis to sort the factors in order of importance. For Sobol method when we convert the list to a dataframe  we can't sort in decending order becuause it is a list and we have to loop over the list to sort.
i want somthing like
`SI_Sobol=sobol.analyze(problem, i,descending=True)`

I was trying to compact my code then I got error message for sort:
my variables of interst is a list:
`SOBOL=[ x_Max,x_Mean,x_End, y1_Max,y1_Mean, y1_End, y2_Max,y2_Mean, y2_End]
RESULTS_Sobol=[]
for i in SOBOL:
    SI_Sobol=sobol.analyze(problem, i)
    SI_DF_Sobol=SI_Sobol.to_df()
    SI_DF_Sobol.sort_values(by=['ST'], inplace=True, ascending=False)
    RESULTS_Sobol.append(SI_DF_Sobol)
Six_Max,Six_Mean,Six_End, Siy1_Max,Siy1_Mean, Siy1_End, Siy2m_Max,Siy2_Mean, Siy2_End=RESULTS_Sobol   `

Error message:
`AttributeError                            Traceback (most recent call last)
<ipython-input-140-aa47a36fa41d> in <module>
      5     SI_Sobol=sobol.analyze(problem, i)
      6     SI_DF_Sobol=SI_Sobol.to_df()
----> 7     SI_DF_Sobol.sort_values(by=['ST'], inplace=True, ascending=False)
      8     RESULTS_Sobol.append(SI_DF_Sobol)
      9 #Six_Max,Six_Mean,Six_End, Siy1_Max,Siy1_Mean, Siy1_End, Siy2m_Max,Siy2_Mean, Siy2_End=RESULTS_Sobol
AttributeError: 'list' object has no attribute 'sort_values' `

**Comment by ConnectedSystems** [comment]
Hello,

For the Saltelli method, the `to_df()` method returns a list of DataFrames.

Change this line: 

```python
SI_DF_Sobol = SI_Sobol.to_df()
```

To:

```python
total, first, second = SI_Sobol.to_df()
total.sort_values(by=['ST'], inplace=True, ascending=False)
```

**Comment by FO2020** [comment]
Thanks for your reply.This will solve the problem but what I suggested that when the analysis is performed it should sort the result by default but maybe this is not very important.
