### ISSUE TITLE
issue 248 with more than 4 num_levels

### ISSUE THREAD

**Issue by bigtaotaoo** [SALib/SALib#297]
Hi there !

I am using SALib to run my sensitivity analysis with Morris method. I have the same problem as described in issue #248 . I use the version 1.3.8.

Can you give me a help ? Thanks a lot.

Benoit

**Comment by willu47** [comment]
Hi @bigtaotaoo - this has been fixed in the latest release 1.3.11

**Comment by bigtaotaoo** [comment]
Thanks a lot. It works.
