### ISSUE TITLE
Index  and columns  names of sensitivity indices doesn't convert to latex

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#300]
Hei, I did the sensitivity analysis with both SOBOL and Morris method and converted the result to dataFrame and so dataframe to Latex but the Greek or even normal letters doesn't convert to latex .
Is there a way to do it because it is possible to convert any dataframe to latex and the index names and columns names should get converted.
I am not sure if this is a Panda issue or SALIB issue but I made a dataframe as the output of sensitivity measure S1 and converted it to latex with same command and the index and columns names got converted as well.
The code is in the attached file:
[GSA_EP6_NonDimVar_NonDim_model.zip](https://github.com/SALib/SALib/files/4500371/GSA_EP6_NonDimVar_NonDim_model.zip)

**Comment by ConnectedSystems** [comment]
Hello,

If I understand you correctly, you'd like the mathematical notation displayed in figures?

You can accomplish this by using the `rename()` for DataFrames and using the math notation for matplotlib. Example below

```python
df = Morris.to_df()
df = df.rename(columns={"mu": "$\mu$"})
```

References:
* https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html
* https://matplotlib.org/3.1.1/tutorials/text/mathtext.html

**Comment by FO2020** [comment]
Thanks for the quick reply.
Yes,that is what I wanted but I wondered why they don't get converted directly without using rename. For sobol method I have to write the whole S2 row indices as you mentioned and this is time consuming.

**Comment by ConnectedSystems** [comment]
Hello,

Displaying it in the DataFrame is a bit tricky. Not sure if it's possible.

Could you try using the latex math notation in the problem spec where you're giving each parameter a name? That will at least avoid you having to rename all the index values.

Then you can try converting the extracted DataFrame to latex with `escape=False`

`df.to_latex(encoding='utf-8', escape=False)`

**Comment by FO2020** [comment]
I did that and got blank in front of some of them and this ( and \ is removed in others. Puting this encoding='utf-8' in the argument gives error message.
![SensitivityLatex](https://user-images.githubusercontent.com/61733579/79746811-e5690c80-830a-11ea-92dd-086ccb60bb6b.png)

**Comment by ConnectedSystems** [comment]
Please see the below.

If it still doesn't work, could you attach a minimum example as either `.py` or HTML?

```python
from SALib.sample.morris import sample
from SALib.analyze.morris import analyze
from SALib.test_functions import Ishigami

problem = {
    'num_vars': 3,
    'names': ['$\theta_{10}$', '$x2$', '$x3$'],
    'bounds': [[-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359]]
}

moat_sample = sample(problem, 100)
Y = Ishigami.evaluate(moat_sample)

result = analyze(problem, moat_sample, Y)

result.to_df()
```

![image](https://user-images.githubusercontent.com/4075136/79748122-3c450500-8350-11ea-8af0-c55a8a9f678d.png)

```python
print(result.to_df().to_latex(escape=False))
```
![image](https://user-images.githubusercontent.com/4075136/79748291-87f7ae80-8350-11ea-894b-fe58646d8571.png)

**Comment by FO2020** [comment]
I uploaded the .py file as zip because its the only format allowed here.
[Convert sensitivity Dataframe to latex.zip](https://github.com/SALib/SALib/files/4503371/Convert.sensitivity.Dataframe.to.latex.zip)

**Comment by ConnectedSystems** [comment]
Going to sleep now but I'll have a look tomorrow afternoon and get back to you

**Comment by FO2020** [comment]
Good night. It seems that there is a problem with converting beta1 and beta2 which I don't know why. The others get converted correctly.

**Comment by ConnectedSystems** [comment]
Hello,

Turns out you have to escape the backslash as well, like so:

`$\\beta_{10}$`

**Comment by FO2020** [comment]
Yes,it works as wanted now. Thanks a lot
