### ISSUE TITLE
Integer error in delta.analyze method

### ISSUE THREAD

**Issue by massimopizzol** [SALib/SALib#304]
Hi

I am running SALib on a python 3.7.1  environment with numpy version 1.18.1. 
When running the `delta.analyze` function I get an error. Here the code and the error.
(Note: when using the Saltelli and Sobol methods everything works fine. 
Note2: same code on python environment 3.6.7 and numpy 1.17.2 returns no error)  

` from SALib.sample import latin
from SALib.analyze import delta
from SALib.test_functions import Ishigami
import numpy as np

problem = {
    'num_vars': 3,
    'names': ['x1', 'x2', 'x3'],
    'bounds': [[-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359]]
}

X = latin.sample(problem, 1000)
Y = Ishigami.evaluate(X)
Si = delta.analyze(problem, X, Y, print_to_console=True)
`
This is the error I get

`Traceback (most recent call last):
  File "/Users/massimo/miniconda/envs/BW2.1/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/massimo/miniconda/envs/BW2.1/lib/python3.7/site-packages/SALib/analyze/delta.py", line 60, in analyze
    m = np.linspace(0, N, M + 1)
  File "<__array_function__ internals>", line 6, in linspace
  File "/Users/massimo/miniconda/envs/BW2.1/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
`

**Comment by ConnectedSystems** [comment]
Hello,

Are you able to install and try the most recent version of SALib?

**Comment by massimopizzol** [comment]
Thanks for quick answer. I believe it's the most recent version. I have installed today with 'conda install -c conda-forge salib'

**Comment by ConnectedSystems** [comment]
It looks like the conda-forge version is horribly out of date - v1.1.2 whereas we're up to v1.3.x now.

Could you try the version available via pip? 

`pip install SALib`

In the meantime I'll prod @willu47 to see what I can do about conda-forge.

**Comment by massimopizzol** [comment]
It worked! Many thanks for your (very fast) support
