### ISSUE TITLE
Error importing morris 

### ISSUE THREAD

**Issue by amanmajid** [SALib/SALib#305]
When I attempt to run `from SALib.sample import morris` I get an error related to comb:

>   File "/home/aman/anaconda3/lib/python3.7/site-packages/SALib/sample/morris/__init__.py", line 34, in <module>
    from . gurobi import GlobalOptimisation
>   File "/home/aman/anaconda3/lib/python3.7/site-packages/SALib/sample/morris/gurobi.py", line 19, in <module> from scipy.misc import comb as nchoosek
> ImportError: cannot import name 'comb' from 'scipy.misc' (/home/aman/anaconda3/lib/python3.7/site-packages/scipy/misc/__init__.py)

This might be because `comb` was moved to `scipy.special`. Changing `from scipy.misc import comb` to `from scipy.special import comb` in `gurobi.py` and `brute.py` in the morris directory fixed this for me.

**Comment by ConnectedSystems** [comment]
Hello,

Are you by chance using an install from conda?

I ask because this particular issue was fixed a while ago - the version available on conda is out of date (we'll be addressing that asap).

Is installation via pip possible?

**Comment by amanmajid** [comment]
Hi,

Yes, I am using conda. 

Apologies, I missed the previously closed issue. 

I will install via pip.

Thanks!
