### ISSUE TITLE
Gaussian inputs

### ISSUE THREAD

**Issue by marcrocasalonso** [SALib/SALib#307]
Hi,
Thank you in advance for your time.

I have a metamodel _M(x1,x2,x3)_ with three inputs **X**=[x1,x2,x3] with Normal distributions x1=N(0,1), x2=N(0,1), x3=N(0,1).

My idea is to develop sensitivity analysis for the metamodel _M_ with gaussian inputs not with Uniform distribution. How I can definde the problem to obtain the Saltelli samples?
**_My example idea:_**
problem = {
    'num_vars': 3,
    'names': ['x1', 'x2', 'x3'],
    'dist': [[N(0,1)],
               [N(0,1)],
               [N(0,1)]]
}

Thank you very much for your help and time!
Marc

**Comment by jdherman** [comment]
Hi @marcrocasalonso , this is built in we just haven't documented it fully. 

```
problem = {
'num_vars': 3,
'names': ['x1', 'x2', 'x3'],
'bounds':[[0,1], [0,1], [0,1]],
'dists': ['norm', 'norm', 'norm']
}
```
when a distribution other than uniform ('unif') is specified, the `bounds` become the parameters of the distribution, in this case the mean and standard deviation.

**Comment by marcrocasalonso** [comment]
Thank you very much!
