### ISSUE TITLE
Use of Fractional Factorial method

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#311]
Hei,
I am wondering how to use the Fractional Factorial method in SALib because we using the ff sample method I get more parameters than I have which result in error when running the analysis. Do I need to use different syntax than other method? I red the documentation and the examples of course.
```
import numpy as np
from numpy import *
from cmath import*
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import scipy as scp
from scipy.integrate import solve_ivp, odeint
import SALib
from SALib.sample import saltelli,morris,latin,ff
from SALib.sample import morris
from SALib.analyze import sobol,dgsm,rbd_fast,delta,ff,dgsm
from SALib.analyze import morris
from SALib.plotting.bar import plot as barplot
from SALib.plotting.morris import *

problem = {
    'num_vars': 11,
    'names': ['$\\beta_{1}$', '$\\beta_{2}$', '$\\epsilon_{1}$','$\\epsilon_{2}$','$g_{12}$','$\gamma_{12}$','$\omega_{11}$','$\omega_{22}$','$x_{0}$','${y_{1}}_{0}$','${y_{2}}_{0}$'],
    'bounds': [[200, 2500000],
               [200, 2500000],
               [0.01, 100],
               [0.01, 100],
               [0.04, 600],
               [0.0002, 20],
               [0.002, 100],
               [0.002, 100],
               [0.0002, 5.71428571],
               [0.01, 2000000],
               [0.01, 2000000]]
}

def dynamical_model_bacteria(t,X,beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22):    
    x, y1, y2 = X
    dxdt=x*(1-x-y1-y2)
    dy1dt=y1*(-epsilon1-omega11*y1-g12*y2+beta1*x)
    dy2dt=y2*(-epsilon2+gamma12*y1-omega22*y2+beta2*x)
    return dxdt,dy1dt,dy2dt


def run_model(param_values):
    loop_n = param_values.shape[0]
    x_res = np.empty((loop_n, 4))
    y1_res = np.empty((loop_n, 4))
    y2_res = np.empty((loop_n, 4))
    
    t = [0, 60]
    t_eval_pts = np.linspace(0, 60, 8000)
    for i in range(loop_n):
        beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22,x0,y10,y20 = param_values[i]

        X0 = [x0, y10, y20]
        arg_list = (beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22)
        sol = solve_ivp(dynamical_model_bacteria, t, X0, args=arg_list, t_eval=t_eval_pts,method='Radau')

        x, y1, y2 = sol.y
        x_res[i, :] = amax(x), mean(x), median(x), x[-1]
        y1_res[i, :] = amax(y1), mean(y1), median(y1), y1[-1]
        y2_res[i, :] = amax(y2), mean(y2), median(y2), y2[-1]
    return x_res, y1_res, y2_res

param_values5=SALib.sample.ff.sample(problem,seed=None)

xff, y1ff, y2ff=run_model(param_values5)

FF=[i for i in xff.T] + [i for i in y1ff.T] + [i for i in y2ff.T]
RESULTSff=[]
for i, j in zip(FF, range(12)):
    Si_ff= ff.analyze(problem,param_values5, i,second_order=True, print_to_console=False, seed=None)
    Sidf_ff=  Si_ff.to_df()
    RESULTSff.append( Sidf_ff)
    barplot( Sidf_ff)
    plt.xlim([-1, 100])
    plt.ylim([-0.5, 0.7])
    plt.gcf().set_size_inches(20, 4)
    plt.show
```

The error message I get:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-cdf8f2782bdc> in <module>
----> 1 xff, y1ff, y2ff=run_model(param_values5)

<ipython-input-31-22407fed1a3c> in run_model(param_values)
     16     t_eval_pts = np.linspace(0, 60, 8000)
     17     for i in range(loop_n):
---> 18         beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22,x0,y10,y20 = param_values[i]
     19 
     20         X0 = [x0, y10, y20]

ValueError: too many values to unpack (expected 11)

```

**Comment by ConnectedSystems** [comment]
Hello again @FO2020 

As the error message states, the error occurs in the following line in your `run_model()` function:

```python
beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22,x0,y10,y20 = param_values[i]
```

Running your example code (thanks, by the way), and investigating `param_values`, e.g:

```python
print(param_values.shape)
# (32, 16)
```

It appears it has 16 columns. Why?

Looking into the documentation for Fast Factorial:

> The resulting matrix has D columns, where D is smallest power of 2 that is greater than the number of parameters.

Looking at the packaged example for `ff` and investigating the sample matrix we see [here](https://github.com/SALib/SALib/blob/b93924d207585825689c5628a05418da037547d5/examples/ff/ff.py#L25) that the number of model parameters is 3, but the sample matrix has 4 columns (the smallest power of 2 that is > 3).

We also see that columns past the number of parameters are ignored.

So change your line above to:

```python
beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22,x0,y10,y20, *_ = param_values[i]
```

where:
* `*` is Python for "put everything else into the variable I declare next" and 
* the variable `_` is Python convention for "I declare this variable but don't plan on using it" to let other programmers know you are intentionally ignoring or not using the variable.

**Comment by FO2020** [comment]
Thanks for reply I got the Idea of getting 16 but what are other values used for?
In documentation there is this 
```
Y = X[:, 0] + (0.1 * X[:, 1]) + ((1.2 * X[:, 2]) * (0.2 + X[:, 0]))

```
Which I didn't get why it is written like this.

**Comment by ConnectedSystems** [comment]
That's the model formulation and uses only the first 3 columns which map to the factors of interest.

As for the other column values, these represent dummy variables that are used in the analysis of results.

See the documentation for the fractional factorial analysis method [here](https://github.com/SALib/SALib/blob/b93924d207585825689c5628a05418da037547d5/src/SALib/analyze/ff.py#L22).

**Comment by FO2020** [comment]
It seems that we can change the number of samples in this method,
I am getting 4 dummy variables in the result, should I just ignore them?
By the I have tested almost all methods all gave same results except for dgsm and partly this ff method.

**Comment by ConnectedSystems** [comment]
Glad you managed to resolve this. Cheers.

**Comment by FO2020** [comment]
Yes,I get the results but they include dummy variables so I am not going to use them.By the way for my model these methods(Sobol,rbd_fast,delta, even dgsm) give the same result for S1 and morris mu_star is actually equivalent to sobol S_T and not S1 the same in the paper I mentioned to you previously. I appreciate your help.
