### ISSUE TITLE
Morris returns mu_star=0 for Ishigami function

### ISSUE THREAD

**Issue by yohm** [SALib/SALib#312]
I'd like to ask you a question of how to interpret the results obtained by Morris method.
I tried the following sample code which is shown in the SAlib document.

```python
from SALib.sample.morris import sample
from SALib.analyze.morris import analyze
from SALib.test_functions import Ishigami

# Define the model inputs
problem = {
    'num_vars': 3,
    'names': ['x1', 'x2', 'x3'],
    'bounds': [[-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359]]
}

# Generate samples
X = sample(problem, 10, num_levels=4)

# Run model (example)
Y = Ishigami.evaluate(X)

# Perform analysis
Si = analyze(problem, X, Y, num_levels=4, print_to_console=True)
```

We obtained the following indicating all three parameters have significant values of mu_star, which is totally fine as Ishigami function depends on all parameters.

```
Parameter                         Mu_Star         Mu    Mu_Star_Conf      Sigma
x1                                  7.704      7.704           3.796      6.587
x2                                  7.875      1.575           0.000      8.133
x3                                  6.249      1.250           3.814      9.222
```

The problem occurs when we increase `num_levels` to a higher value, such as 64.
The output looks like the following, which indicates that x2 is not an influential parameter.

```
Parameter                         Mu_Star         Mu    Mu_Star_Conf      Sigma
x1                                  9.293      9.293           6.691     11.895
x2                                  0.373     -0.026           0.120      0.450
x3                                  6.624     -3.302           4.205      9.402
```

To my understanding, this occurs because the Ishigami function is periodic in x2 with period pi, which is exactly half of the range of x2. Since Morris method changes the value of a factor by exactly half of the range, Ishigami function behaves as if it is independent of x2.

While I understand this is not a problem of the implementation of this library, isn't there an algorithm to avoid this problem?

**Comment by ConnectedSystems** [comment]
Hello @yohm 

Apologies for the delay in getting back to you.

Is there a specific reason why a high number of levels is selected? 

Typical values are 4, 6, or 8 ([Franczyk, 2019](https://doi.org/10.1007/s11600-019-00356-5)), although higher values are also possible (e.g. 10 in [Norton 2010](https://doi.org/10.3182/20090706-3-FR-2004.00111))

In practice the choice in number of levels appears to be based on the assumption that 4 to 10 will explore enough of parameter space (as discussed in Franczyk, 2019).

Again relying on Franczyk (2019), the choice of the number of levels is also related to the number of trajectories (`r`), where levels set too high compared to small values of `r` will "waste" experiments.

The implementation provided in SALib uses the method presented in [Ruano et al. (2012)](https://doi.org/10.1016/j.envsoft.2012.03.008) to determine an optimal `r`, however you can provide your own value by setting the `optimal_trajectories` parameter, e.g:

```python
X = sample(problem, 10, num_levels=4, optimal_trajectories=some_value)
``` 

Hope this helps.

**Comment by yohm** [comment]
@ConnectedSystems Thanks for your reply.
I got that the typical values are at most 10. I tried a higher value because I thought it would give us a more accurate estimate when the input factor is a continuous value. Since I had enough computational resources, I tried to avoid possible biases caused by the discretization by increasing the level as well as `r`.

From a practical point of view, I agree that we don't have to increase the number of levels. Thanks for your helpful answer.

**Comment by willu47** [comment]
If you increase the number of levels, then you must also significantly increase the number of trajectories (`N`) - because you will otherwise create a biased sample (each trajectory visits only a limited number of values for each parameter) as stated above

**Comment by yohm** [comment]
@willu47 Thank you for your answer. Actually, the issue is not caused by the number of trajectories `N`, but by the property of the Ishigami function.
For a demonstration, I tried the calculation for `N=10000` with various `num_levels` as follows:

```py
def f(n_levels):
    X = sample(problem, 10000, num_levels=n_levels)
    # Run model (example)
    Y = Ishigami.evaluate(X)
    # Perform analysis
    Si = analyze(problem, X, Y, num_levels=n_levels, print_to_console=True)
    return Si['mu_star']

n_levels = [4,8,10,16,32,64]
for lev in n_levels:
    st = f(lev)
```

`mu_star` for x1, x2, x3 depend on `num_levels` as the following. As you see, only x2 shows a significant dependence on `num_levels` while the other two are independent of `num_levels`.
To my understanding, this singularity of x2 comes from the periodicity of the Ishigami function with respect to x2.

![mu_star](https://user-images.githubusercontent.com/718731/81901464-8c368500-95f9-11ea-9f0f-dedf410fba9c.png)
