### ISSUE TITLE
Problem with the installation

### ISSUE THREAD

**Issue by marcrocasalonso** [SALib/SALib#313]
Hey,

I am trying to install your package in Ubuntu with "sudo pip install SALib" but it doesn't works. This is the error that appears: 
"Complete output (1 lines):
    Error: version of setuptools is too old (<38.3)!
".
 
I have upgradeed the setup tool by " pip install --upgrade pip setuptools
" but appears the same problem.
This is the error that appears:

![Screenshot from 2020-05-05 11-16-40](https://user-images.githubusercontent.com/37378243/81051541-1ed07900-8ec2-11ea-9614-9038e9e1feab.png)
 Thank you in advance,
Marc

**Comment by ConnectedSystems** [comment]
Hello,

I don't think it is advisable, generally, to use `sudo pip install`, see link and discussion within:

https://stackoverflow.com/questions/61452582/why-is-using-sudo-pip-a-bad-idea

I advise using a separate environment - I personally use [conda](https://docs.conda.io/en/latest/miniconda.html) for this purpose, but there are others such as virtualenv.

To get things working asap, you could try:

`pip install git+https://github.com/SALib/SALib.git#egg=SALib`

**Comment by ConnectedSystems** [comment]
I'm going to assume the above resolved the issue, so closing this now
