### ISSUE TITLE
Getting Sobol first order effect from delta method

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#314]
Hello,
I read the article  [https://www.sciencedirect.com/science/article/pii/S0951832006000883?casa_token=P_Yf7woHVNUAAAAA:ieqN-5JZcswsfAXjWMS-v8XIoU4TKR_7WrTPJhCgQIpsChUa5BdMWgXyRH3vl8yGxPrztIBVTRk](url) by E.Borgonovo which is reference at SALib and I am not getting the idea of getting Sobol first order index S1 in the output and not just delta as in the paper. Is there a explanation for this?

**Comment by jdherman** [comment]
The S1 value is estimated as a byproduct of calculating the delta value, based on the conditional PDFs. It is not part of the delta method itself but is a useful output to include.
