### ISSUE TITLE
Negative value or values greater than one for delta index from delta method

### ISSUE THREAD

**Issue by FO2020** [SALib/SALib#315]
Hello, Sorry for coming with multiple questions.
I am trying to test different methods for sensitivity. I study the sensitivity of max,mean,median and,equilibrium value of the model output. For median value of y2 and some others I got huge positive values and negative values. The values for main effect S1 are reasonable and comparable with sobol and RBD-Fast method.
I tested with number of samples  1000,(15000 with resample_number=100,500) and 60000 and no improvement.
According to Borgonovo 2007  article delta values should be between 0 and 1.
Is there something wrong with my model or implementation of the method?
The code
```
import numpy as np
from numpy import *
from cmath import*
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import scipy as scp
from scipy.integrate import solve_ivp, odeint
import SALib
from SALib.sample import saltelli,morris,latin,ff,finite_diff
from SALib.sample import morris
from SALib.analyze import sobol,dgsm,rbd_fast,delta,ff,dgsm
from SALib.analyze import morris
from SALib.plotting.bar import plot as barplot
from SALib.plotting.morris import *
problem = {
    'num_vars': 11,
    'names': ['$\\beta_{1}$', '$\\beta_{2}$', '$\\epsilon_{1}$','$\\epsilon_{2}$','$g_{12}$','$\gamma_{12}$','$\omega_{11}$','$\omega_{22}$','$x_{0}$','${y_{1}}_{0}$','${y_{2}}_{0}$'],
    'bounds': [[200, 2500000],
               [200, 2500000],
               [0.01, 100],
               [0.01, 100],
               [0.04, 600],
               [0.0002, 20],
               [0.002, 100],
               [0.002, 100],
               [0.0002, 5.71428571],
               [0.01, 2000000],
               [0.01, 2000000]]
}
def dynamical_model_bacteria(t,X,beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22):    
    x, y1, y2 = X
    dxdt=x*(1-x-y1-y2)
    dy1dt=y1*(-epsilon1-omega11*y1-g12*y2+beta1*x)
    dy2dt=y2*(-epsilon2+gamma12*y1-omega22*y2+beta2*x)
    return dxdt,dy1dt,dy2dt
def run_model(param_values):
    loop_n = param_values.shape[0]
    x_res = np.empty((loop_n, 4))
    y1_res = np.empty((loop_n, 4))
    y2_res = np.empty((loop_n, 4))
    
    t = [0, 60]
    t_eval_pts = np.linspace(0, 60, 8000)
    for i in range(loop_n):
        beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22,x0,y10,y20,*_ = param_values[i]

        X0 = [x0, y10, y20]
        arg_list = (beta1, beta2, epsilon1,epsilon2,g12,gamma12,omega11,omega22)
        sol = solve_ivp(dynamical_model_bacteria, t, X0, args=arg_list, t_eval=t_eval_pts,method='Radau')

        x, y1, y2 = sol.y
        x_res[i, :] = amax(x), mean(x), median(x), x[-1]
        y1_res[i, :] = amax(y1), mean(y1), median(y1), y1[-1]
        y2_res[i, :] = amax(y2), mean(y2), median(y2), y2[-1]
    return x_res, y1_res, y2_res

param_values4 =SALib.sample.latin.sample(problem, 15000)
%%time
xDelta, y1Delta, y2Delta=run_model(param_values4)
%%time
  
DELTA=[i for i in xDelta.T] + [i for i in y1Delta.T] + [i for i in y2Delta.T]
RESULTSDelta=[]
for i, j in zip(DELTA, range(12)):
    Si_Delta= delta.analyze(problem,param_values4, i,num_resamples=500)
    Sidf_Delta= Si_Delta.to_df()
    Sidf_Delta.sort_values(by=['S1'], inplace=True, ascending=False)
    #Renaming the columns names to put them in math notation
    Sidf_DeltaNew=Sidf_Delta.rename(columns={'delta':'$\delta$','delta_conf':'$\delta_{conf}$','S1': '$S_{1}$','S1_conf':'${S_{1}}_{conf}$'})
    RESULTSDelta.append( Sidf_DeltaNew)
    barplot( Sidf_Delta)
    #plt.xlim([-1, 100])
    #plt.ylim([-0.5, 0.7])
    plt.title(TITLE[j] )
    #plt.gcf().set_size_inches(20, 4)
```
![A9258E3B-C998-47F7-9ACF-3B904C7C3D31](https://user-images.githubusercontent.com/61733579/82262983-40ba0900-9962-11ea-8d0b-39b505755b03.jpeg)
![8537F07C-7150-4B6E-9723-47D5FB8E7456](https://user-images.githubusercontent.com/61733579/82262998-49aada80-9962-11ea-992b-f438b5d8bd42.jpeg)

**Comment by ConnectedSystems** [comment]
Hi @FO2020 

The approach implemented in SALib uses the bias reduction method as detailed in Plischke et al. (2013; https://doi.org/10.1016/j.ejor.2012.11.047). 

Do remember to report the confidence bounds in your work. If the confidence bounds overlap 0 and 1 then it is working as expected.

I took the liberty of testing out the analysis with your bacteria model directly (using 100 samples and 1000 bootstraps) and both the model and the analysis appears to be working fine:

dxdt
![image](https://user-images.githubusercontent.com/4075136/82294693-e36d9880-99f1-11ea-91db-10cd168b6ec0.png)

dy1dt
![image](https://user-images.githubusercontent.com/4075136/82294737-f4b6a500-99f1-11ea-8d5a-a0da8b7c03d1.png)

dy2dt
![image](https://user-images.githubusercontent.com/4075136/82294777-039d5780-99f2-11ea-901b-7bda903e0e43.png)


I believe the call to `solve_ivp()` is complicating matters but I don't have the time to delve into what your doing with it and what might be affecting things.

That said, do note this ongoing issue with SciPy `solve_ivp()` which may be relevant for you.
https://github.com/scipy/scipy/issues/8922

Additionally, I found this in my travels which might be useful.
https://jitcode.readthedocs.io/en/v1.5.0/

**Comment by FO2020** [comment]
Thank s for taking time to look at the issue.I tested with number of samples 100 and I got the same result as yours  when I increase number of samples the result not logical. 
I had to use solv_ivp because I needed stiff solver and the famous solver odeint gave wrong results. The strange thing is that I get reasonable results for all methods except for delta values
 Here is the complete example .
![NegativeDeltaMedianY1](https://user-images.githubusercontent.com/61733579/82316829-abecf500-99cd-11ea-9c90-32bb3ae23833.png)

**Comment by jdherman** [comment]
There is something here related to outliers in the model output. Here is a minimum example using the Ishigami function:

```python
import numpy as np
from SALib.sample import latin
from SALib.analyze import delta
from SALib.test_functions import Ishigami

problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}

N = 10000
X = latin.sample(problem, N)
Y = Ishigami.evaluate(X)
Y[N-50] = 10**10 # outlier
Si = delta.analyze(problem, X, Y, print_to_console=True)
```

Output with no outlier:
```
Parameter delta delta_conf S1 S1_conf
x1 0.213095 0.004333 0.315429 0.014489
x2 0.361875 0.009624 0.434681 0.026199
x3 0.164573 0.007377 0.002751 0.002412
```
Output with outlier:
```
Parameter delta delta_conf S1 S1_conf
x1 8852.381336 17019.882939 0.002103 0.319877
x2 10153.512708 8712.940108 0.002103 0.432511
x3 19024.310073 10148.592602 0.002098 0.001467
```

Something bad is happening, but I'm not sure what. Options would be to replace the outlier with another value (if it is incorrect), or log-transforming the model outputs to reduce the impact of outliers.

**Comment by FO2020** [comment]
I will try to take the logarithm of the output and do analysis and check I will get better results

**Comment by ConnectedSystems** [comment]
HI @FO2020 

Just wanted to check that by "interval" you're referring to the parameter bounds?

If so, then this:

```python
'bounds': [[-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359]]
```

Is (near) identical to:

```python
[[-np.pi, np.pi]]*3
```

The `*3` tells Python to repeat the value 3 times such that it will be expanded to:

```python
[
    [-np.pi, np.pi],
    [-np.pi, np.pi],
    [-np.pi, np.pi]
]
```

So the only real difference is that @jdherman forces an outlier:

```python
Y[N-50] = 10**10 # outlier
```

**Comment by FO2020** [comment]
@ConnectedSystems 
Thanks for explanation. That was strange because I got reasonable results without doing anything with outliers. I didn't get what outlier line of code do actually.
1-I had look at jitcode and find it interesting but it need some packages and time to apply it to my model and not sure I will manage it.
2-For log transforming I did this: I had some small negative values and zeros in output and used rounded them to smallest possible positive numbers to get around because this give error when taking log of the output. 

```
xDelta[xDelta<=0,] = np.nextafter(0, 1)
y1Delta[y1Delta<=0] = np.nextafter(0, 1)
y2Delta[y2Delta<=0] = np.nextafter(0, 1)
Si_Delta= delta.analyze(problem,param_values4, np.log(i),num_resamples=1000)
```
3-The result are good for N=1000,num_resamples=1000 and will test for larger N
![image](https://user-images.githubusercontent.com/61733579/82389297-1177ca80-9a3c-11ea-85e9-e845ba66bd5a.png)
![image](https://user-images.githubusercontent.com/61733579/82389375-4a17a400-9a3c-11ea-973c-29527c566d60.png)
4-This method is very slow compared to sobol and others.

**Comment by ConnectedSystems** [comment]
Hi

> That was strange because I got reasonable results without doing anything with outliers. I didn't get what outlier line of code do actually.

To clarify, that was the point. In his example, the "outlier line of code" was used to manually insert a significant outlier to show you that this can cause a problem. With no outlier, you get expected "reasonable" results. (thanks @jdherman for jumping in there, btw)

> This method is very slow compared to sobol and others.

Yes, DMIM is computationally expensive relative to other approaches. It's not really an implementation issue as such if that's what you were getting at. 

The advantage of course is it does not require a specific sampling structure (e.g. like Sobol or FAST).
Theoretically you can mix and match with any sampling approach, but in practice there are certain pitfalls to be aware of.

**Comment by jdherman** [comment]
Yea thanks for explaining. I'm concerned about this beyond just this application. We also ran into this problem in our research group. 

Not sure why this happens, but my guess is something to do with the KDE fits and/or the bias correction step when the model output is skewed. I'll leave this open in case anyone has an idea.

**Comment by FO2020** [comment]
@ConnectedSystems @jdherman Taking log seems to work here,I got at least reasonable values .
Does outliers affect other methods for example Sobol?In that case ,is log transforming the model output good option?

**Comment by jdherman** [comment]
Great. I haven't seen this issue ever come up with the Sobol method.

**Comment by FO2020** [comment]
@jdherman For Sobol ST I got a big value which I couldn’t find reason for. ST for r =19836 which is not very reasonable even though ST theoretacaly could be greater than 1.
![1636FE58-0086-4BB5-8A68-4A465CE3E0A5](https://user-images.githubusercontent.com/61733579/82582184-f3bc7980-9b91-11ea-8ba7-31403d186a5f.jpeg)

**Comment by ConnectedSystems** [comment]
Hi @FO2020 

Thinking on this a little more, I have some follow up questions.

As @jdherman shows, the issue with extremely large sensitivity values appear in the presence of extreme outliers.

Could you confirm, if able:

1. That the model results are sensible for the given inputs?

In other words, are the outliers genuine model results or is there an issue with the model?

2. Do the results for both Sobol and Delta become acceptable if the input and outputs for outliers are removed or otherwise constrained?

Below is an example where extreme outliers are constrained to an arbitrary bound.

This is **not** a recommendation of applying the analysis (although it may work as a pragmatic workaround), just a line of questioning.

```python
for i, j in zip(DELTA, range(12)):
    # Constrain extreme outliers before analysis
    Y = i.copy()
    Ymean = Y.mean()
    Ystd = Y.std()
    thres = (8*Ystd)
    min_thres, max_thres = (Ymean - thres), (Ymean + thres)

    # Record of index position of outliers for later inspection
    outliers = np.where((Y < min_thres) | (Y > max_thres))

    Y[Y < min_thres] = min_thres
    Y[Y > max_thres] = max_thres

    Si_Delta= delta.analyze(problem,param_values4, Y, num_resamples=500)

    # ... continue on as before ...
```

**Comment by FO2020** [comment]
Hei @ConnectedSystems and thanks for taking time to answer.
1-I can confirm that there is something wrong with the model output because the very large values or negative values in the output shouldn't occur.I have checked manually the big negative values and it seem the ODE solver get problem there and after changing some options in the ode solver I got correct solution. The solution should basically go toward on of the stable equilibrium point for which I have analytical expression. The problem could be related to parameter intervals but for now I am trying to find out the possible reason for the huge positive values or negative values.
For the input factors there shouldn't be a problem as long as they are from the chosen interval  for each parameter .
for example
2-I tried your nice idea but still got values greater than one for delta.
![image](https://user-images.githubusercontent.com/61733579/82834344-1ec00980-9ec1-11ea-869b-7d85d0fca136.png)

**Comment by FO2020** [comment]
@TobiasKAndersen What about log transformation of the model output , it worked in my case but the outliers in my case because of solver error and not expected model output så i didnt USE the results but your case i different  så log transform may fix the problem

**Comment by TobiasKAndersen** [comment]
Thanks for the tip, @FO2020 - it worked like a charm

**Comment by FO2020** [comment]
@ConnectedSystems @jdherman 
Hei again,
Upon trying to figure out why I was getting wrong values I changed the nondimensionalization of the model and followed a procedure to find outliers and checked If they are caused by ODE slver, or they are genuine model output. Many were caused by the solver and some were correct model output. I run the sensitivity again with N=100000 and got large negative values for median and equilibrium value of y1 for parameter b. The statistic for the model output doesn't show any extreme outliers.
Statistics for y1 variable of the model output for delta method:
![Statistics of y1 variableDeltaMethod](https://user-images.githubusercontent.com/61733579/85401254-05f75200-b55a-11ea-8fef-5feb197e8a7a.png)

Results from delta method for median and eqm. values of y1:
![SensitivityDeltaMethodMedianY1](https://user-images.githubusercontent.com/61733579/85400140-3fc75900-b558-11ea-9993-5e88039441ba.png)
![SensitivityDeltaMethodEqmY1](https://user-images.githubusercontent.com/61733579/85400167-4d7cde80-b558-11ea-9e1e-d8b398b08abe.png)
Results from RBD-Fast method shows the same values for S1 as for Delta Method
![image](https://user-images.githubusercontent.com/61733579/85400389-a0ef2c80-b558-11ea-8fde-1f82387587ea.png)
![image](https://user-images.githubusercontent.com/61733579/85400400-a8163a80-b558-11ea-8851-c4578750ad12.png)
The code used:
```
import numpy as np
from numpy import *
from cmath import*
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import scipy as scp
from scipy.integrate import solve_ivp, odeint
import pandas as pd 
import SALib
from SALib.sample import saltelli,morris,latin,ff,finite_diff
from SALib.sample import morris
from SALib.analyze import sobol,dgsm,rbd_fast,delta,ff,dgsm
from SALib.analyze import morris
from SALib.plotting.bar import plot as barplot
from SALib.plotting.morris import *
problem = {
    'num_vars': 11,
    'names': ['$a$','$b$','$\\delta_{1}$', '$\\delta_{2}$','$\psi$','$\phi$','$\\omega_{1}$','$\\omega_{2}$','$x_{0}$','${y_{1}}_{0}$','${y_{2}}_{0}$'],
    'bounds': [  [1e-05,1e-03]
               , [0.1,10]
               , [0.1,10]
               , [0.1,10]
               , [0.1,10]
               , [0.0001,5]
               , [0.001,10]
               , [0.001,5]
                ,[0,10000],
                 [0,1000],
                 [0,100]
                          ]
}

def DM_bacteria(t,X,pm):    
    x, y1, y2 = X
    a, b,delta1,delta2,psi,phi,omega1,omega2=pm
    dxdt=x*(1-a*x-y1-b*y2)
    dy1dt=y1*(-delta1-omega1*y1-psi*b*y2+x)
    dy2dt=y2*(-delta2-omega2*b*y2+phi*y1+b*x)
    return [dxdt,dy1dt,dy2dt]
def DM_jac(t,X,pm):
    x, y1,y2 = X
    a, b,delta1,delta2,psi,phi,omega1,omega2=pm
    J=np.array([[-2*a*x - b*y2 - y1 + 1, -x, -b*x], 
                [y1, -b*psi*y2 - delta1 - 2*omega1*y1 + x, -b*psi*y1], 
                [b*y2, phi*y2, -2*b*omega2*y2 + b*x - delta2 + phi*y1]])
    return J

#Solver that can be used
SOLVERS=['RK45','RK23','DOP853','BDF','Radau','LSODA']
def run_model(param_values,tMax,solvers,RelTol,AbsTol):
    loop_n = param_values.shape[0]
    
    x_res = np.empty((loop_n, 4))
    y1_res = np.empty((loop_n, 4))
    y2_res = np.empty((loop_n, 4))
    
    t = [0, tMax]
    t_eval_pts = np.linspace(0, tMax, 25*tMax)
    for i in range(loop_n):
        a, b,delta1,delta2,psi,phi,omega1,omega2,x0,y10,y20,*_ = param_values[i]
        X0 = [x0, y10, y20]
        pm=np.array ([ a, b,delta1,delta2,psi,phi,omega1,omega2])
        #hmax=0.01
        #,max_step=0.01
       
        sol=solve_ivp(DM_bacteria,t,X0,method= solvers,t_eval= t_eval_pts,args=(pm,),jac=DM_jac,rtol=RelTol,atol=AbsTol);

        x, y1, y2 = sol.y
        x_res[i, :] = amax(x), mean(x), median(x), x[-1]
        y1_res[i, :] = amax(y1), mean(y1), median(y1), y1[-1]
        y2_res[i, :] = amax(y2), mean(y2), median(y2), y2[-1]
    return x_res, y1_res, y2_res

# Title for plotting
TITLE=['Sensitivity of Maximum value of $x$'     ,'Sensitivity of Mean value of $x$'     ,'Sensitivity of Median value of $x$'    ,'Sensitivity of Equilibrium value of $x$',
       'Sensitivity of Maximum value of $y_{1}$' ,'Sensitivity of Mean value of $y_{1}$' ,'Sensitivity of Median value of $y_{1}$','Sensitivity of Equilibrium value of $y_{1}$',
       'Sensitivity of Maximum value of $y_{2}$' , 'Sensitivity of Mean value of $y_{2}$','Sensitivity of Median value of $y_{2}$','Sensitivity of Equilibrium value of $y_{2}$']

#Si Analysis'
param_values3 =SALib.sample.latin.sample(problem, 100000)
xRbdFast, y1RbdFast, y2RbdFast=run_model(param_values3,364,SOLVERS[0],1e-09,1e-09)
xDelta,y1Delta, y2Delta=xRbdFast,y1RbdFast,y2RbdFast
param_values4=param_values3
DELTA=[i for i in xDelta.T] + [i for i in y1Delta.T] + [i for i in y2Delta.T]
RESULTSDelta=[]
for i, j in zip(DELTA, range(12)):
    Si_Delta= delta.analyze(problem,param_values4, i,num_resamples=1000)
    Sidf_Delta= Si_Delta.to_df()
    #Renaming the columns names to put them in math notation
    Sidf_DeltaNew=Sidf_Delta.rename(columns={'delta':'$\delta$','delta_conf':'$\delta_{conf}$','S1': '$S_{1}$','S1_conf':'${S_{1}}_{conf}$'})
    RESULTSDelta.append( Sidf_DeltaNew)
    barplot( Sidf_Delta)
    #plt.xlim([-1, 100])
    #plt.ylim([-0.5, 0.7])
    plt.show()
    plt.title(TITLE[j] )
   

```
What could be the reason for these large negative values? Could it be that I have a lot of zeros in the model output or something else?

**Comment by ConnectedSystems** [comment]
Hi @FO2020 

Out of curiosity do you have a reference for that bacteria model?

Looking at the results you show for Median and Equilibrium for y1, the mean for both is around 0.052 but the median is tiny: `6.08e-12` and `3.14e-10` respectively.

That tells me already that the outlier detection method I suggested earlier isn't suitable - the large mean relative to the very small median suggests fairly extreme outliers, such that the mean doesn't really reflect the result population but instead indicates the influence of the outliers.

In this case, try the Interquartile Range (IQR) outlier detection test.

You can easily do this with `scipy.stats.iqr()` in combination with `np.quantile()`: 

```python
Q1 = np.quantile(0.25)
Q3 = np.quantile(0.75)
median_iqr = scipy.stats.iqr(y1_median)

below_threshold = y1_median[y1_median < (Q1 - 1.5 * median_iqr)]
above_threshold = y1_median[y1_median > (Q3 + 1.5 * median_iqr)]
```

For overview, see:
https://en.wikipedia.org/wiki/Interquartile_range#Outliers

**Comment by FO2020** [comment]
Thanks @ConnectedSystems for taking time to look at this.
1-The model for bacteria/microorganisms interaction I made myself . The following pdf document give some information about what the model represent.
[BacteriaMicroorganizimInteraction.pdf](https://github.com/SALib/SALib/files/4821803/BacteriaMicroorganizimInteraction.pdf)
2-What I did wasn't actually removing the outliers but I checked that the solvers gave correct output by using several criteria and now I can confirm  that outliers are genuine model output and appears when there aren't any stable equilibrium points in the system, but they are not extremely larger than the other values as before.
3-Setting  very small negative number of order `-1e-253` in the output to zero, adding the smallest possible positive number `np.nextafter(0,1)` to the model output to handle zeros, log transforming and running the analysis I got the following:
Sensitivity for median value of y1:
![image](https://user-images.githubusercontent.com/61733579/85461887-2dbfd780-b5a5-11ea-93e6-be26564a00df.png)
Sensitivity for  eqm. Value of y1:
![image](https://user-images.githubusercontent.com/61733579/85462034-5647d180-b5a5-11ea-8ac9-9edf3c3adf4c.png)
You see that I got rid of negative values but the results for S1 are not correct compared to RBD-Fast method. Omega2 now is the most sensitive parameter while it  should be b as in RBD-Fast and Delta before log transforming.
The question now is :Does log transforming change the ranking and sensitivity ?

**Comment by ConnectedSystems** [comment]
Hello again,

I guess my intention was to simply point out that there are in fact outliers in the results which, as mentioned previously, can affect the results of DMIM analysis. I did not intend to imply in this case that you should remove or constrain outliers.

I'm not much of a mathematician so I'm unable to assist beyond this point other than to say it appears DMIM is not a suitable analysis method in the context where extreme outliers are expected.

Given this is for your Masters and it seems your focus is on pathogen modelling rather than sensitivity analysis, I suggest you talk to your supervisor(s) about this to determine the boundaries of your thesis. You may end up just simply reporting the limitations of DMIM in your context.

**Comment by FO2020** [comment]
@ConnectedSystems Thanks for your kind help and suggestion. I suppose that is what I am going to do in the end and I agree that this is not my focus but I thought that it will be nice idea to compare methods and find limitations. Maybe someone will look at this problem in the future as Campolongo did for Morris method.

**Comment by ConnectedSystems** [comment]
Topic for your PhD perhaps?

**Comment by FO2020** [comment]
@ConnectedSystems That could be one option but this topic will need stronger background in statistics which I don't have but nothing can stop me if I became interested.

**Comment by ConnectedSystems** [comment]
Revisiting this thread, I wonder if anyone has the time to compare/investigate with the PAWN method (also a moment-independent method)
