### ISSUE TITLE
saltelli.sample enables user defined skip_values? 

### ISSUE THREAD

**Issue by QianWanghhu** [SALib/SALib#316]
Hey,
I was trying to use saltelli.sample and found that the skip_values is not a parameter in the method. The value used is 1000 in the code. It might be good to add skip_values as a parameter.  Or is there any particular reason that skip_values is hidden? 
Look forward to your reply.

Best wishes,
Qian

**Comment by jdherman** [comment]
It's just a default, but it could be added as a keyword argument with the same default.
