### ISSUE TITLE
evaluate_model is undefined?

### ISSUE THREAD

**Issue by amirjodeiri** [SALib/SALib#318]
Hi, 
As a  part of Basics in SALib documentation:
for i, X in enumerate(param_values):
    Y[i] = evaluate_model(X)
is used. according to Python 3.7, evaluate_model is undefined.

**Comment by ConnectedSystems** [comment]
Hello,

To clarify, the documentation is using `evaluate_model(X)` as an example.

It is expected that you replace this with your own function which runs the model and returns a result for the given parameter values.

**Comment by ConnectedSystems** [comment]
Just to add, you can see a working example of this in the "examples" folder, e.g. [this one for Sobol](https://github.com/SALib/SALib/blob/master/examples/sobol/sobol.py)

I'm closing this issue now but feel free to follow up with other questions if you need.
