### ISSUE TITLE
Refactoring Morris sample module

### ISSUE THREAD

**Issue by lbteixeira** [SALib/SALib#325]
Hello. I'll propose a few more changes on the sampling module `morris.py`. No functionalities will be changed for now, I'll just try to clean the code a little more. Specially, I'll break the function `_compute_optimised_trajectories` in more functions.

**Comment by willu47** [comment]
Hi @lbteixeira - Another thing which need doing is removing the brute force optimised trajectories code which depended upon Gurobi. This has been superseded by the locally optimal solution. Alternatively, it could be implemented in an open-source optimisation framework such as PuLP or pyomo, although those are both large dependencies which may not be worth it.

**Comment by lbteixeira** [comment]
Hello, @willu47. Ok, I'll delete the brute force method. Later, if we find it's necessary to have it, we can implement it using these frameworks you cited.

**Comment by willu47** [comment]
I actually meant the `gurobi.py` file - the brute force method is impractical for normal use, but it for very small tests to compare the other methods against.  Suggest you retain brute force and remove the gurobi file (and all other gurobi-related references).

**Comment by lbteixeira** [comment]
Oh, ok. Sorry about that. I'll do as you said.
