### ISSUE TITLE
Refactoring - analyze/morris.py

### ISSUE THREAD

**Issue by lbteixeira** [SALib/SALib#327]
Hello.

I would like to make some more clean up, this time for the module `morris.py` of the package `analyze`. What I intend to do is:

1. Break the function `analyze` into smaller functions
2. Remove unused code
3. Some minor style modifications

If you know something else that should change in this module, please let me know.

**Comment by ConnectedSystems** [comment]
I think the changes merged addresses this issue, but please reopen if not.
