### ISSUE TITLE
Documentation ReadTheDocs

### ISSUE THREAD

**Issue by rddaz2013** [SALib/SALib#332]
First ... Nice Work thx

On Page : https://salib.readthedocs.io/en/latest/basics.html

The ghosts of "Python 2" appear again in the print expression in the example

best wishes

**Comment by ConnectedSystems** [comment]
Thanks for raising the issue. I will be cleaning up the documentation in the near future.

**Comment by ConnectedSystems** [comment]
This is addressed in #346 so am closing now. Changes will be available in v1.4
