### ISSUE TITLE
Question about confidence level

### ISSUE THREAD

**Issue by rddaz2013** [SALib/SALib#333]
"The _conf keys store the corresponding confidence intervals, typically with a confidence level of 95%" 

What "confidence intervals" exactly mean?  confidence intervals on the effect ?

best wishes

**Comment by ConnectedSystems** [comment]
Hi @rddaz2013 

The confidence intervals relate to the bounds which cover 95% of the possible sensitivity index value, estimated through bootstrap resampling.

I'm not entirely sure if I've interpreted your question correctly so feel free to clarify if my response doesn't answer your enquiry.

**Comment by rddaz2013** [comment]
Thx @ConnectedSystems for the answer. 

"corresponding confidence intervals" what general means is clear to me, but...

> Si is a Python dict with the keys "S1", "S2", "ST", "S1_conf", "S2_conf", and "ST_conf". The _conf keys store the corresponding confidence intervals, typically with a confidence level of 95%

So is the confidence intervals based on value of Si['S1'] or S1 - on the sensitivity or on the input value?

**Comment by ConnectedSystems** [comment]
If I understand your question correctly, the indicated confidence interval is related to the reported sensitivity for a parameter.

Using the example to illustrate:

```python
from SALib.sample import saltelli
from SALib.analyze import sobol
from SALib.test_functions import Ishigami
import matplotlib.pyplot as plt
import numpy as np

problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}

param_values = saltelli.sample(problem, 1000)

Y = Ishigami.evaluate(param_values)

Si = sobol.analyze(problem, Y, print_to_console=True)

Si.plot()
plt.show()
```

We get the following table:

| Parameter | S1            | S1_conf    | ST               | ST_conf |
|------------|------------|------------|--------------|----------|
| x1             | 0.307975  | 0.066815  | 0.560137     | 0.080400 |
| x2             | 0.447767  | 0.055719  | 0.438722     | 0.041036 |
| x3             | -0.004255 | 0.058783  | 0.242845     | 0.024382 |

First order sensitivity for x1: 0.30 ± 0.06
Total sensitivity for x1: 0.56 ± 0.08
... etc ...

Using plotting function perhaps conveys the above clearer:

![image](https://user-images.githubusercontent.com/4075136/89473699-e6914d00-d7c6-11ea-9ca1-495e0186682a.png)

Hope this answers your question

**Comment by ConnectedSystems** [comment]
I assume this issue has been resolved - feel free to re-open if more information is needed.

**Comment by Atulsingh92** [comment]
Added question to the above, 
how can I plot the above plot, without the confidence interval without haveing to post process Si data to another df to construct a bar plot separately?
Or is that the only way to draw the above without the confidence interval?

**Comment by ConnectedSystems** [comment]
Hi Atul,

You don't necessarily have to create another dataframe for this yourself, as SALib has a conversion method built-in for quite some time now.

```python
# Using the problem specification from the previous example above
Y = Ishigami.evaluate(param_values)
Si = sobol.analyze(problem, Y, print_to_console=False)

ST, S1, S2 = Si.to_df()

ST.loc[:, "ST"].plot(kind='bar')
```

All other adjustments to the figure itself can be made using usual matplotlib approaches.

<img width="184" alt="image" src="https://user-images.githubusercontent.com/4075136/157997603-e6a296f4-0e76-4598-bbe0-3299d7157c65.png">
