### ISSUE TITLE
MatplotlibDeprecationWarning in morris.py example file

### ISSUE THREAD

**Issue by MatthiVH** [SALib/SALib#342]
I'm working with python 3.5.
When I run the following Morris example script here [(morris.py),](https://github.com/SALib/SALib/blob/master/examples/morris/morris.py#L14)
it gives me the following warning:

MatplotlibDeprecationWarning: 
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.
  warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "

The problem occurs in line 56: sample_histograms(fig2, param_values, problem, {'color': 'y'})

**Comment by ConnectedSystems** [comment]
Hi @MatthiVH 

Could you check what version of matplotlib you are using? It seems to be a relatively old one.

```
# If you are using conda:
$ conda list matplotlib

# If using pip on windows:
$ pip list | findstr matplotlib

# if on linux/osx:
$ pip list | grep matplotlib
```

FYI, the one in my environment is v3.3.1

**Comment by MatthiVH** [comment]
Hi,

I have v3.0.3.
Well if the warning only disappears with higher versions of matplotlib, I guess I have to install a higher version of python as well.

**Comment by ConnectedSystems** [comment]
Hi again,

If you can't upgrade, I'd suggest finding the most recent matplotlib version that still supports 3.5 and see if that clears the warning. Note that this is message is a warning only and should not affect results.

Otherwise, if this is a new project I'd recommend creating a new environment with at least Python 3.7

**Comment by MatthiVH** [comment]
Alright. Thanks for the information. Upgrading is not possible anymore with python 3.5 so to clear the warning, I'll have to use a higher version of python then. Indeed, it doesn't affect the results. Thanks!
