### ISSUE TITLE
SALib.plotting.bar module error

### ISSUE THREAD

**Issue by Zs0lty87** [SALib/SALib#359]
Have the results 
Trying to plot the Sobol method but it gives the error: 

""
---> 29     conf_cols = Si_df.columns.str.contains(CONF_COLUMN)
     30 
     31     confs = Si_df.loc[:, conf_cols]

AttributeError: 'list' object has no attribute 'columns' ""

Converting to data frame gives a list, can that be the problem?

**Comment by ConnectedSystems** [comment]
Hi @Zs0lty87 

And yes, Sobol results returns a list of dataframes (total, first, second order indices).

Something like the below should work:

```python
Si = sobol.analyze(...)

total, first, second = Si

total.plot()
```

Otherwise I'd need to see an example of the code you're trying to run.

**Comment by Zs0lty87** [comment]
Thanks for the help

total, first, second = Si.to_df() <-- this one works, maybe the documentation should be updated for people like me who's not an expert in programing :)

Is there a module here where you could plot both the 1st and the total at the same time and can you also use logarithmic scale?

Thank you and great GSA package btw ;)

**Comment by ConnectedSystems** [comment]
Hi again,

I will update the example in the plotting module as it is incorrect and probably what caused the confusion here.

And yes, I agree that generally the documentation needs an update. We're working on it 😄 

FYI, a correct example for the Sobol method is mentioned here:
https://github.com/SALib/SALib/blob/master/README-advanced.md

As for your other plotting questions, the `plot` functions all return a matplotlib axes object, and you can manipulate those as you like.

Below is an example that I think should work.

```python
import matplotlib.pyplot as plt
from SALib.plotting.bar import plot as barplot
from SALib.test_functions import Ishigami
from SALib.sample import saltelli
from SALib.analyze import sobol
import numpy as np

problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}

X = saltelli.sample(problem, 1000)
Y = Ishigami.evaluate(X)
Si = sobol.analyze(problem, Y, print_to_console=False)
total, first, second = Si.to_df()

ax = barplot(total)

ax.set_yscale('log')

# Make the plot appear if not in Jupyter notebooks
plt.show()
```

You can create your own figure layout using the usual matplotlib functions

```python
# More direct control by manually specifying figure attributes
fig, (ax1, ax2) = plt.subplots(1,2, figsize=(16,6))

ax1 = barplot(total, ax=ax1)
ax2 = barplot(first, ax=ax2)

ax1.set_yscale('log')
ax2.set_yscale('log')

# Make the plot appear if not in Jupyter notebooks
plt.show()
```

Hope this helps

**Comment by Zs0lty87** [comment]
Thanks a lot for the support.

Great job
