### ISSUE TITLE
Convergence check for FAST and RBD-FAST GSA

### ISSUE THREAD

**Issue by MatthiVH** [SALib/SALib#373]
Hi,

I'm doing uncertainty and sensitivity analysis for some research on IEA - EBC annex70 on building stock models.
Is there a way to check for convergence using the FAST global sensitivity analysis?
In Sobol for example, you immediately get the bootstrapped confidence intervals for S1 and ST, so you could compare it to an arbitrarily chosen limit (e.g. 0.05) and conclude that the sensitivity indices have converged as the CI is below 0.05.

This is however not the case for the FAST global sensitivity analysis since there are no confidence intervals calculated. Same issue for RBD-FAST, so I'm wondering if it can be implemented in these two SA-methods (FAST and RBD-FAST) or if there is another good way to check for convergence?

Kind regards,
Matthias

**Comment by ConnectedSystems** [comment]
Hello,

I just put in a tentative implementation to estimate CIs for both FAST and RBD-FAST for the v1.4.0 development release.

If you can, you can try it out via pip:

`pip install --pre salib==1.4.0.dev0`

Please do note the above is a pre-release and there may be unknown bugs or issues.

If you cannot upgrade to the pre-release version you can still apply bootstrapping, externally from the package.

Here is an example:

```python
import numpy as np
from scipy.stats import norm

from SALib.analyze import rbd_fast
from SALib.sample import latin
from SALib.test_functions import Ishigami
from SALib.util import read_param_file


problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds': [[-np.pi, np.pi]]*3
}

X = latin.sample(problem, 1000)
Y = Ishigami.evaluate(X)

num_results = Y.shape[0]
num_params = X.shape[1]
conf_level = 0.95

# use ~50% of available data for each resample, as an example
n_size = int(num_results * 0.5)

num_resamples = 100
res = np.zeros((num_resamples, num_params))
for i in range(num_resamples):
    sample_idx = np.random.choice(num_results, replace=True, size=n_size)
    X_rs, Y_rs = X[sample_idx], Y[sample_idx]
    Si = rbd_fast.analyze(problem, X_rs, Y_rs)
    res[i] = Si['S1']
    
for i in range(res.shape[1]):
    S1_conf = norm.ppf(0.5 + conf_level / 2.0) * res[:, i].std(ddof=1)
    print('Param', i+1, '+/-', S1_conf)
```

**Comment by ConnectedSystems** [comment]
Hi @MatthiVH 

I'm assuming everything is okay now so I will close this issue. Feel free to reopen if not.
