### ISSUE TITLE
Delta Moment-Independent Measure with correlated input paramaters

### ISSUE THREAD

**Issue by Tangzl922** [SALib/SALib#390]
Hi,

I'm using delta analysis with correlated input parameters. As presented in the documentation, we need to assign distributions to parameters respectively. But how can we describe the correlation among these parameters?

**Comment by ConnectedSystems** [comment]
Hello,

At present SALib does not support correlated sampling.
There is a PR currently in progress (although somewhat stalled) that aims to allow correlated sampling (see https://github.com/SALib/SALib/pull/338). You could clone a copy of the work there but there are no guarantees it will work.

If you already have the samples, you could try the HDMR method currently available in our pre-release version. This method is said to be able to handle correlations (https://doi.org/10.1021/jp9096919)

```bash
$ pip install --pre salib==v1.4.0b0
```

Note that depending on the model the HDMR method can have high memory requirements so it may not be appropriate.

**Comment by Tangzl922** [comment]
Hi,

That's exactly what I'm wondering. Everything is clear. Thank you for your help!
