### ISSUE TITLE
Problem with morris.sample in Morris method

### ISSUE THREAD

**Issue by eleonora921** [SALib/SALib#391]
Hi!
I have a problem with Morris method. In particular for generation of sample. I obtain this error

AttributeError                            Traceback (most recent call last)
<ipython-input-39-8d846c7d9376> in <module>
----> 1 vals =morris.sample(problem, 5000,num_levels=11)
      2 vals
      3 
      4 # initializing matrix to store output
      5 Y = np.zeros([len(vals),1])

AttributeError: module 'SALib.analyze.morris' has no attribute 'sample'

Is it possible to solve?
Thank you!

**Comment by ConnectedSystems** [comment]
Glad to see this resolved. Let us know if there are any other issues.
