### ISSUE TITLE
A Question about samples

### ISSUE THREAD

**Issue by rensx5514** [SALib/SALib#393]
I have a 3 * 3 * 3 matrix variable. How to set its range in 'problem'? 

3Q!

**Comment by ConnectedSystems** [comment]
Hello,

I will need some more information to help.

What does the matrix represent?

SALib will produce samples in the shape of `N*D`, where `N` is the number of samples and `D` is the number of parameters.

You will have to wrap your function to reshape this array into the form expected by the target model.

**Comment by rensx5514** [comment]
> Hello,
> 
> I will need some more information to help.
> 
> What does the matrix represent?
> 
> SALib will produce samples in the shape of `N*D`, where `N` is the number of samples and `D` is the number of parameters.
> 
> You will have to wrap your function to reshape this array into the form expected by the target model.

matrix maybe like 
M = [[[1,4,3],[1,5,2],[3,1,4]],
[[2,7,9],[2,4,7],[3,6,5]],
[[1,3,5],[2,3,5],[2,5,1]]]

every M[i][j][k] >= 0 and   M[i][j][k] <= 10

As what the examples say, matrix M can be split  into 27 variables and set the range is [0,10].But I want to get the matrix M as a variables to analyze its sensitivity.How can I get it? 3QQQQQQQQ

**Comment by ConnectedSystems** [comment]
Hi again,

It may be that if you do not have access to your model's code, you may not be able to apply SALib to it. As I said above, the sample array SALib produces an array in the shape of `N*D`: the first dimension is the number of samples, and the second dimension is the number of parameters. In your case `D` is 27.

To clarify, I was wondering what does the matrix represent?
* In your case what is the 2nd and 3rd dimension? Time steps?
* Would your model/function still work if you only gave 1 step (e.g. a single time step)?
  e.g., an array with the shape of (1, `N`, `D`)?

You maybe able to "trick" your model into running for a single step, for example:

```
M = [[[1, 4, 3 ..., D],
        [1, 5, 2, ..., D],
        [3, 1, 4, ..., D],
        ...,
        N]]
```

In which case you simply need to wrap your model as I said above:

```python

def f(x):
    """Some model that requires 3-dimensional input"""
    pass


def wrapper(x):
    # add 3rd dimension
    # resulting array has shape (1, N, D)
    reshaped_x = np.array([x])

    return f(reshaped_x)
```

Hope this helps

**Comment by ConnectedSystems** [comment]
Hello,

I think I understand what you mean, I'll respond again soon.

**Comment by ConnectedSystems** [comment]
Hello,

Create samples for your `3*3*3` matrix:

```
def f(x):
    """Example function: pretend it expects a 3-dimensional input."""
    return np.sum(x**2)


problem = {
  'num_vars': 27,
  'names': [f'x{i+1}' for i in range(27)],
  'bounds': [[0, 10]]*27
}

X = saltelli.sample(problem, 10, calc_second_order=False)
```

The Saltelli sampler will create an array in the form of `N*D`, where `D = 27`

Note that for the Saltelli sampler, `N = n(D+2)` where `n` is 10 (the number given to the sampler).

Create a wrapper around your function to reshape this input into the expected matrix form.
The process would treat a `N*27` array as `N` entries of (3*3*3).

An example is below.


```python
def wrapper(x):
    n = x.shape[0]   # Get number of samples

    # Create result array 
    # (assumes function returns a single value - adjust this accordingly)
    Y = np.zeros(n)  

    for i in range(n):
        # Reshape 27 elements in to 3x3x3 array
        reshaped_x = x[i].reshape((3,3,3))

        # Run function and store result
        Y[i] = f(reshaped_x)
    
    return Y
```

Good luck

**Comment by rensx5514** [comment]
Get it! I would like to express my sincere appreciation to your response.

**Comment by rensx5514** [comment]
I'm sorry to reopen this issue. I realize what you say that 27 variables were wrappered as a array for my func.
But the problem is that we created 27 variables for 'sobol.analyze'.We get the result from 'sobol.analyze' is 27 variables, not a variable. Si['S1'] is not what we expected.Do you mean that ?

**Comment by ConnectedSystems** [comment]
Could you show example code?

**Comment by rensx5514** [comment]
> Could you show example code?
As what you say before, I add this.
` Si = sobol.analyze(problem, Y, print_to_console=True)`
I want to take 27 variables as one variable and get the sensitivity of this variable.
Obviously,  'print('S1:', Si['S1'])' is not what we expected

**Comment by ConnectedSystems** [comment]
Hello,

I don't have all the details of your context but what you want to do, as I currently understand it, does not make much sense to me.

Is this 3-dimensional input the only model parameter?

If so, and you treat it as a single input, then all the variance in output will be attributed to this single input unless you have something else happening inside the model or otherwise affecting the model results.

In other words, I assume your model looks like:

<img src='https://latex.codecogs.com/svg.latex?Y%20=%20f(X)'>

in which case `Si` is only dependent on `X`, unless your model actually looks something like:

<img src='https://latex.codecogs.com/svg.latex?Y%20=%20f(X)%20+%20\epsilon'>

where `Ɛ` is used here to denote some internal or external influence on Y.


See equations in [this paper](https://dx.doi.org/10.1111/0272-4332.00040) for full explanation, preprint accessible [here](http://www.andreasaltelli.eu/file/repository/Risk_Analysis_2002.PDF)


I suppose you could use group sampling - wherein you would assign all parameters to a single group, and it would perturb ('change the value of') all parameters as one to achieve what you want, but that still doesn't make much sense to me.

```python
problem = {
  'num_vars': 27,
  'names': [f'x{i+1}' for i in range(27)],
  'bounds': [[0, 10]]*27,
  'groups': ['group1']*27
}
```

**Comment by rensx5514** [comment]
> I don't have all the details of your context but what you want to do, as I currently understand it, does not make much sense to me.
> 
> Is this 3-dimensional input the only model parameter?
> 
> If so, and you treat it as a single input, then all the variance in output will be attributed to this single input unless you have something else happening inside the model or otherwise affecting the model results.
> 
> In other words, I assume your model looks like:
> 
> ![](https://camo.githubusercontent.com/5d75800e2b1ecb36d284ba4ff6438f9cb653d58e960fb107f2e83f7e52d46e19/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e6c617465783f592532303d25323066285829)
> 
> in which case `Si` is only dependent on `X`, unless your model actually looks something like:
> 
> ![](https://camo.githubusercontent.com/815e21e82b4326e17d838c2b6c1c617ab525df238b980313ed3fa3b872ae115f/68747470733a2f2f6c617465782e636f6465636f67732e636f6d2f7376672e6c617465783f592532303d253230662858292532302b2532305c657073696c6f6e)
> 
> where `Ɛ` is used here to denote some internal or external influence on Y.
> 
> See equations in [this paper](https://dx.doi.org/10.1111/0272-4332.00040) for full explanation, preprint accessible [here](http://www.andreasaltelli.eu/file/repository/Risk_Analysis_2002.PDF)
> 
> I suppose you could use group sampling - wherein you would assign all parameters to a single group, and it would perturb ('change the value of') all parameters as one to achieve what you want, but that still doesn't make much sense to me.
> 
> ```python
> problem = {
>   'num_vars': 27,
>   'names': [f'x{i+1}' for i in range(27)],
>   'bounds': [[0, 10]]*27,
>   'groups': ['group1']*27
> }
> ```

I solved the problem by adopting your suggestion.
Thank you so much for your help.
