### ISSUE TITLE
Does SALib work with the data which provide with .txt file?

### ISSUE THREAD

**Issue by 1rashiid** [SALib/SALib#394]
I have the "param_values" as .txt file, and "Y" as .txt file. But, I could not use the SALib, since in the example it uses "sobol.analyze(problem...", and use the problem as input. 
Could you help me how to solve this? thank you.

**Comment by ConnectedSystems** [comment]
Hello,

Could you take a look at the examples [here](https://github.com/SALib/SALib/blob/develop/README-advanced.md) first?

**Comment by 1rashiid** [comment]
Hello, Thanks for the response. But, this example did not solve my question. The problem is that I have done the outputs for the parameters. i.e, I have the "parameters_value", and the outputs. In this example, at first, it sample the parameters, and "sobol.analyze(problem..." this line of the code, does not accept the parameters_values as input.

**Comment by willu47** [comment]
To read a parameter file in from a text file, use the following:

```python
from SALib.util import read_param_file

problem = read_param_file('../../src/SALib/test_functions/params/Sobol_G.txt')
```
As @ConnectedSystems described - this can found in the example files (see the morris.py example)

For reading in your Y `.txt` file into a numpy array required to use SALib, the easiest way is to use [`numpy.loadtxt()`](https://numpy.org/doc/stable/reference/generated/numpy.loadtxt.html)

But perhaps you should be using the command-line interface to SALib if you're using text files?

**Comment by 1rashiid** [comment]
Thank you for your response. I think that my problem is a little different. In the morris example, the parameter values read by
problem = read_param_file('../../src/SALib/test_functions/params/Sobol_G.txt') is a .txt file with the lower and upper bound. 
I have run my model in python2.7. I have chosen my parameter based on uniform distribution which is also defined in Python 2.7.  My parameters value is a .txt file which is the chosen parameters. For example, for Y= f(x1,x2). I have the parameter values as a .txt file with (10, 2) size. And my Y is a (10,1). But here, the example seems that includes the lower and upper bound.

**Comment by ConnectedSystems** [comment]
Hello again,

You could read in the `Y` values with `numpy.loadtxt()` as @willu47 described, and 

1) recreate the problem spec to suit (i.e., make the dictionary manually). This is only viable if you know the parameter bounds, which I assume you do.

or 

2) Read in the `X` values (again, with `numpy.loadtxt()` ) and use the minimum and maximum of the sampled values to represent the parameter bounds. This is not ideal but the only option I can think of where the range of possible values has been lost.

**Comment by 1rashiid** [comment]
Thanks again. No, this solution also does not solve my question. Since I have done the sampling for my parameters before. Thanks for your time and response.

**Comment by ConnectedSystems** [comment]
I'm not sure if I understand as neither of my suggestions require you to sample again.

Perhaps this example is more accessible:

```python
# "parameter values as a .txt file with (10, 2)"
# This is an example only, you may have to adjust how the data is read in
X = np.loadtxt("parameter_values.txt")

# "Y is a (10,1)"
# This is an example only, you may have to adjust how the data is read in
Y = np.loadtxt('results.txt')

x1_bounds = (X[:, 0].min(), X[:, 0].max())
x2_bounds = (X[:, 1].min(), X[:, 1].max())

problem = {
  'num_vars': 2,
  'names': ['x1', 'x2'],
  'bounds': [x1_bounds, x2_bounds]
}

Si = sobol.analyze(problem, Y, calc_second_order=True, conf_level=0.95, print_to_console=True)
```

**Comment by 1rashiid** [comment]
@ConnectedSystems Thanks. I will do it. I hope it works:)

**Comment by ConnectedSystems** [comment]
Closing this as we haven't heard back from you. Hope you found a good solution.
