### ISSUE TITLE
Error in Source code of 'analyze' for sobol 

### ISSUE THREAD

**Issue by cighosh** [SALib/SALib#397]
if we set 'calc_second_order=False' it gives error. Need to change/update or add another 'elif' statement I guess. Thanks!

**Comment by cighosh** [comment]
I can try to fix the error though. Thanks!

**Comment by Mickael01** [comment]
Hi cighosh,

It might be because the variable calc_second_order is not set the same value in sample and analyse. It is either both true or both false.

**Comment by cighosh** [comment]
Hi got it. Thanks. 

Yes that might be the reason, which I overlooked, sorry about that. The analyze part, I kept to default, which maybe 'True' for calc_second_order. :). The document only tells about the sample part, so I have not taken the analyze part into consideration.
Thanks for the quick help anyway. :)
