### ISSUE TITLE
How to generate different sample for the same problem with Saltelli.sample 

### ISSUE THREAD

**Issue by Mickael01** [SALib/SALib#399]
Hi, 
Is it normal that when performing twice the saltelli.sample function with the same problem 
and a different seed I obtain the same array.

A = saltelli.sample(problem,10,seed=123456)
B = saltelli.sample(problem,10,seed=654321)
then 
comparaison = A ==B 
comparaison.all() 
return True

Sincerely Mickaël

**Comment by Mickael01** [comment]
Sorry, it is me again.

I just find the following issue #334 that speaks about it will change the skip_values instead.

I will close it and read in detail the issue #334.

**Comment by ConnectedSystems** [comment]
Glad you found the solution!
