### ISSUE TITLE
version 1.3.12 is available on pypi but not on conda-forge

### ISSUE THREAD

**Issue by bhazelton** [SALib/SALib#401]
The most recent version on conda-forge is 1.3.11, but there's a newer version, 1.3.12 on pypi.

It looks like maybe this just requires merging in the related PR on the conda-forge feedstock repo (https://github.com/conda-forge/salib-feedstock)? Maybe this step should be mentioned in the docs developed for #355?

**Comment by ConnectedSystems** [comment]
Thanks for pointing this out - I'm attempting to set up auto-merge so this doesn't get overlooked again.
