### ISSUE TITLE
Sobol Sensitivity Analysis with sampling from normal distribution

### ISSUE THREAD

**Issue by jellinge** [SALib/SALib#405]
Hi,

first, thank you very much for you library, which I have been using extensively in the last weeks! 

I am wondering, if I can sample my parameters for sensitivity analysis (Saltelli) a  from a normal distribution instead of the upper and lower limit. Is this already possible or am I missing a point here?

Many thanks!

Best
Johannes

**Comment by ConnectedSystems** [comment]
Hi @jellinge 

Thanks very much for using the library, glad it is of help to you.

The example given here is relevant to you:

https://github.com/SALib/SALib/issues/307

```python
problem = {
  'num_vars': 3,
  'names': ['x1', 'x2', 'x3'],
  'bounds':[[0,1], [0,1], [0,1]],
  'dists': ['norm', 'norm', 'norm']
}
```

Do note that when using alternate sampling distributions, the meaning of the `bounds` entry changes.
For normal distributions the first value is the mean, the second value indicates the standard deviation.

**Comment by ConnectedSystems** [comment]
Incidentally, tentative updated docs can be found here:

https://github.com/SALib/SALib/blob/develop/docs/advanced.rst

**Comment by jellinge** [comment]
Hi,
thank you very much for the fast and comprehensive answer!
