### ISSUE TITLE
Role of seed in SALib.sample.saltelli

### ISSUE THREAD

**Issue by isaackramer** [SALib/SALib#412]
The SALib.sample.saltelli function has a "seed" input that suggests there is a way to randomize the generated points. Changing the value of this input, however, appears to have no effect on the output. Am I missing something?

```
names = ['var1', 
         'var2', 
         'var3']

bounds = [[0, 1], 
          [1, 2], 
          [2, 3]]

inputs = {'num_vars': len(names),
          'names': names,
          'bounds': bounds}
								
# generate samples
param_vals_1 = saltelli.sample(problem=inputs, 
                                N=100)
param_vals_2 = saltelli.sample(problem=inputs, 
                               N=100, 
                               seed = 10)
```

These both produce the same values.

**Comment by ConnectedSystems** [comment]
To produce different results, you should change the `skip_values` (default 1000).

The `seed` option is there for compatibility reasons. The docs for the next version have been updated to communicate this more explicitly as we know this has caused confusion.

**Comment by isaackramer** [comment]
Thanks for the quick response!
