### ISSUE TITLE
Sobol Indices of Normal, Lognormal and Truncated distributions

### ISSUE THREAD

**Issue by marcrocasalonso** [SALib/SALib#420]
Hi,

first, thank you very much for you library!

I am wondering, if I can sample my parameters for sensitivity analysis (Saltelli) a from a normal distribution, lognormal distributions and a truncated lognormal distribution. Is this already possible or am I missing a point here?

**My distribution inputs are:**
_h1=chaopsy.Normal(mu1,sigma1)
h2=chaopsy.LogNormal(mu2, mu2*sigma2, shift=1.15, scale=0.18)
h3=chaopsy.Uniform(low3,upp3)
h4=chaopsy.Trunc(0.975-cp.LogNormal(-2.6, 0.5), lower=0.75)_

Many thanks!

Best
Marc Rocas

**Comment by ConnectedSystems** [comment]
Hello,

You can specify a distribution, although this functionality is not yet fully documented.

You can see a list of supported distributions [here](https://github.com/SALib/SALib/blob/83979f5b510385e67b1fc1e2cf1d50c6df67a859/src/SALib/util/__init__.py#L109)

You can see a partial example of how to use it [in this test](https://github.com/SALib/SALib/blob/e30a3a559aa017997e5172e1e48bc50ddb085597/tests/test_regression.py#L194)

Each parameter is specified a distribution. Do take care though, as it does change the meaning of the `bounds` entry.

`truncnorm` is a little problematic as it is only available in SALib v1.4 (currently available as a pre-release).
We currently have no tests to cover this however, so there may be issues.

You should be able to try it out with `pip install --pre salib==1.4.0.rc0` if you want.

**Comment by marcrocasalonso** [comment]
Thank you for your time and answer :)
