### ISSUE TITLE
Add citation to the readme

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#421]
About 11 peer-reviewed publications have cited the github repository, rather than the JOSS paper. Adding the citation at the top of the readme would help clarify how to cite the software.

The citation is currently stored in a separate file in the repository root.

**Comment by schmitts** [comment]
You have that list of publications at hand?

**Comment by willu47** [comment]
Yes, on Google scholar, if you look at the entry for SALib, you can see it has consolidated citations to the [JOSS paper](https://scholar.google.co.uk/scholar?oi=bibs&hl=en&cites=566904225393358690&as_sdt=5) (386), [Github  repository](https://scholar.google.co.uk/scholar?oi=bibs&hl=en&cites=11783361414383595059&as_sdt=5) (16).

**Comment by ConnectedSystems** [comment]
Sorry to dredge this up but just FYI I've added a citations.cff file so it is even easier to cite the JoSS submission (see right hand side on front page of GitHub repo)

![image](https://user-images.githubusercontent.com/4075136/132090337-e03c68bd-0a39-4970-89cd-a888c1e39825.png)
