### ISSUE TITLE
[bug] Sobol range check for conf_level is incorrectly inclusive of 0 and 1

### ISSUE THREAD

**Issue by scottshambaugh** [SALib/SALib#422]
conf_level should be within, but exclusive of 0 and 1. 1 leads to an infinite value later on in the line `Z = norm.ppf(0.5 + conf_level / 2)`, and 0 give a nonsensical result. Opening a PR here shortly.

**Comment by ConnectedSystems** [comment]
Closing as PR has been merged. Thanks again for catching this.
