### ISSUE TITLE
Migrate to pyscaffold 4

### ISSUE THREAD

**Issue by ConnectedSystems** [SALib/SALib#439]
PyScaffold 4 is now available and may resolve recent (and likely future) issues with setuptools (e.g., #438)

**Comment by schmitts** [comment]
Hi!

I've added SALib to Spack (https://github.com/spack/spack/commit/9add3182c79fd5b7e32e7c9287370b04abca527c) but I'm having issues with PyScaffold. If I understood PyScaffold correctly it should _only_ be needed when setting up a new python package. But at the moment SALib has a requirement on PyScaffold in `setup.py`. It would be good if that install/run-time dependency could be removed.

Thanks,

Sebastian

**Comment by schmitts** [comment]
I've removed the dependency on pyscaffold manually (#449) and that seems to work fine. I've also tried to update to pyscaffold 4 (`putup --update`) and it would remove these lines as well.

**Comment by ConnectedSystems** [comment]
Hi @schmitts 

As always, thanks for your efforts. 

Do note that in this instance #445 already exists - I wonder to what extent these efforts can be merged, and generalized for both us and the Spack project. I haven't had the time to look over that PR yet but it is on my list of things to do.

Additionally, if I recall correctly the `setup.py` gets auto-generated by PyScaffold and should not be edited directly as your changes may get overwritten automatically during publication of a package version or similar. If PyScaffold v4 still uses a `setup.cfg` file, that's where you want to include your changes.

Thanks again.

**Comment by schmitts** [comment]
In #445 the problematic line that pulls in pyscaffold is removed (https://github.com/SALib/SALib/pull/445/commits/f33e24b87f4a9bd04990dd7cd917d091e10688cc#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52L34) - that's all I need for the Spack package to work.

**Comment by ConnectedSystems** [comment]
Ah, awesome, hope you don't mind me closing this PR in favour of #445 then

I will try to make time to review #445 this week, but it may take longer.

**Comment by schmitts** [comment]
I've tried #445 and it works with Spack.
