### ISSUE TITLE
User is forced to skip_values

### ISSUE THREAD

**Issue by stelong** [SALib/SALib#442]
Hello,

I was trying to run the latest 1.4.0 version to perform Sobol' GSA using Saltelli method and I am not able to saltelli.sample a sequence with skip_values = 0.

I am not sure why the default skip_values is set to 1024 as later on this will for sure throw either a Warning or an Error according to how unlucky the user has been in choosing the N value.

Also, I am not sure why the default skip_values is not set to 0, as in your documentation you refer to a paper (http://arxiv.org/abs/2008.08051) where it is explicitly proved that skipping the first/firsts points of a Sobol' sequence could be deleterious.

Anyway, I had a look at the code and apparently I cannot set skip_values = 0 since the math.log operator complains when computing the m_exp exponent:

```
math.log(0, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: math domain error
```

An easy fix (although I am sure you'd like to keep using math) would be to use the numpy function as this does return something (-inf) which at least won't make the following if statement (if n_exp >= m_exp) fail:

```
np.log2(0)
<stdin>:1: RuntimeWarning: divide by zero encountered in log2
-inf
```

Thanks a lot!

**Comment by ConnectedSystems** [comment]
Hello,

First, thank you for raising this issue for us, we do depend on the community to give us feedback.

I was not the one to implement this but to give some context, looking at the history of the codebase it seems the `skip_values` parameter was set to 1024 (and 1000 before that). I assume this was following what seems to be common advice in that skipping initial values produces more uniform samples. Whether 1024 is too high a value for this purpose is a different matter, which I will leave to those better informed to debate over.

In any case, I am convinced and so have adjusted the default for `skip_values` to 0.

I will tag you into the PR I create.

**Comment by stelong** [comment]
Dear @ConnectedSystems,

thank you for having implemented this little fix, I am sure that covering a broader range of possibilities (skip_values >= 0) is better than limiting the use to only a very specific case.

I have been using this library for quite some time now, so I am happy I could give my little contribution as well.

Cheers!
