### ISSUE TITLE
Array error in sobol.analyze

### ISSUE THREAD

**Issue by mfrankel923** [SALib/SALib#444]
I am using the saltelli.sample and sobol.analyze methods to do a sensitivity analysis of some parameters of a water quality chemical reaction model. I am varying 16 parameters. 

When I go to use the sobol.analyze method, I get the error: 

![image](https://user-images.githubusercontent.com/42812919/124192236-91b78e80-da8a-11eb-9425-d91e2c70a913.png)

This seems to me like there may be something in the code of the analyze method that could be fixed. I have gotten this error in the past and had to use the .flatten() method to make the dimensions work out.

Interestingly, though, I do not get this error when I run the method with other models which are easier to evaluate with higher values of N. In this case, this was just an initial run and the N for the saltelli.sample method was 32 as I did not want to take an extremely long time for the analysis to complete. 

I have attached both my python script and my variable workspace that can be used in spyder. You will not be able to run the code (it has some other packages and models which I am not uploading) but is intended to give an idea as to how I am using the sensitivity analysis methods. The spyder workspace has all of the variables when the script is finished running, except for the error that gets thrown on line 83 related to the sobol.analyze method.

Just wanted to flag this issue in case any code updates were needed- or if I am doing something wrong, feel free to let me know. Also just for context, I am only expecting 2 of the parameters to be influential in the model outputs.

Thanks!

Here are the files:
[sobol_issue_to_github.zip](https://github.com/SALib/SALib/files/6750937/sobol_issue_to_github.zip)

**Comment by ConnectedSystems** [comment]
Hi @mfrankel923 

Thanks for using the library.

Could you let me know which version of SALib you have installed? I will look into this later today.

**Comment by mfrankel923** [comment]
@ConnectedSystems 

I have version 1.3.13 installed. Thanks for looking into this.

**Comment by ConnectedSystems** [comment]
Hi @mfrankel923 

Took a quick look at this.

This circa L 73 - `crit_time=np.zeros((r,1))`

I'm assuming the model outputs a single output (i.e., it is 1 dimensional?).

If so, what is expected here is `np.zeros(r)`.

Compare:

```python
>>> np.zeros((5, 1))
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

>>> np.zeros(5)
array([0., 0., 0., 0., 0.])
```

The first produces a 2 dimensional array (an array of arrays), but what you need is a 1d array as in the second.

Could be something else though so let me know if this doesn't work or if my assumption is incorrect.

**Comment by mfrankel923** [comment]
@ConnectedSystems  Yes that did the trick. Thanks for your help!
