### ISSUE TITLE
Implement scrambling of Sobol' sequence

### ISSUE THREAD

**Issue by ConnectedSystems** [SALib/SALib#450]
Scrambled Sobol' sequences offer improved uniformity and convergence properties compared with earlier approaches.

http://jcgt.org/published/0009/04/01/

http://statweb.stanford.edu/~owen/reports/dropzero.pdf

**Comment by tupui** [comment]
FYI, SciPy 1.7 includes Sobol' scrambled among others. https://scipy.github.io/devdocs/reference/generated/scipy.stats.qmc.Sobol.html
