### ISSUE TITLE
[Question] Seed variable in analyze function

### ISSUE THREAD

**Issue by giupardeb** [SALib/SALib#451]
Hi, I am using the sobol analyze (https://salib.readthedocs.io/en/latest/_modules/SALib/analyze/sobol.html#analyze) I would like to know, what is the purpose of variable seed in the sobol analyze?

Thank you!

**Comment by ConnectedSystems** [comment]
Hello @giupardeb 

It doesn't actually do anything for the sobol' analysis, and is only there for compatibility with the command-line interface.

We hope to remove it as a parameter eventually, as it does cause some confusion.

**Comment by ConnectedSystems** [comment]
See use of SALib from the command prompt/terminal here: https://github.com/SALib/SALib/blob/4012c1313ee360d0cc3be0fba084f4f86048e2ea/examples/sobol/sobol.sh#L4

**Comment by ConnectedSystems** [comment]
Hi again @giupardeb 

Seems I was incorrect - the seed variable for the `analyze` function ensure consistent results are obtained when estimating the confidence intervals. Apologies for any confusion caused!

I'm closing the issue now but feel free to reopen if you have another question.
