### ISSUE TITLE
Deployment failing

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#458]
Following the upgrade of pyscaffold to v4, we're getting some problems with the automated deployment step on Travis.

- [x] git tags not getting picked up correctly resulting in version number 0.0.0 used for all deployments
- [ ] tox currently not being used for tests or deployment on travis

**Comment by vincentdumont** [comment]
Is this why some of the pages in the documentation are empty? For instance, the [API page](https://salib.readthedocs.io/en/latest/api.html) only shows the name of the sections...

**Comment by willu47** [comment]
Hi @vincentdumont - that's a separate issue, but thanks for flagging. I'm working on a fix in #466

**Comment by willu47** [comment]
@vincentdumont - docs have now been fixed with commit 02d0a76e71caba088
