### ISSUE TITLE
A SALib discussion forum?

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#467]
We've got a great community building up around SALib and perhaps we should talk more? 

Github have announced [Discussions](https://github.com/SALib/SALib/discussions) which seems to offer standard chat features with several others under development.

Alternatives include Slack, Gitter, etc.

**Comment by tupui** [comment]
I would suggest looking into Scientific Python: https://scientific-python.org 

We have a self hosted discuss server at https://discuss.scientific-python.org and we are happy to welcome any communities (I am personally very interested here as you know 😃). Practically speaking I can create a SALib tag. Then you can post in any category using your tag (or any combination). As we grow this hopefully will increase chances of cross project interactions.

After the SciPy conference, we sparkle a lot of interest from other large groups such as Pangeo. The big advantage for you is that you would not have to manage the server configuration etc.

**Comment by ConnectedSystems** [comment]
Tagging @sahin-abdullah on this as well.

@tupui I understand you two have, or intend to have, a discussion around these things. Please feel free to keep me in the loop.

**Comment by tupui** [comment]
@ConnectedSystems we did not discuss this topic, only the theme part.

Let me know if you want me to add a tag for Scientific Python's discuss.

I did not mention it above, but instead of Slack we also have discord https://discord.com/invite/vur45CbwMz

All that might be easier for you than having yet another thing to maintain. 😃

**Comment by ConnectedSystems** [comment]
Hi @tupui 

Abdullah and I had a look around the Discord community for Scientific Python, looks very nice and I think its a good fit for what we want.

Some questions:
- We're wondering would we be able to get admin rights to assign roles or is this something someone else needs to do.
- Is it possible to set up some voice/video channels to allow quick ad-hoc group meetings
- I guess the community and the SALib channel would be completely public and anyone can join/leave as they wish?
- I'm entertaining the idea of setting up a discord bot to point people to relevant places in the documentation

Thanks!

**Comment by willu47** [comment]
I vote for completely open. The forum will be for discussing aspects of the project which should be public anyway as a way to engage and inform. If we really need to discuss something in private we can revert to email.

**Comment by tupui** [comment]
There is actually a new discord space for SA in general https://discord.gg/J6bQDW8q

Takuya and I are already there (even Andrea Saltelli joined 😅) It's still a small group, but everyone is very much interested with SA.

I am working on a project with Mariia, the admin and she gave me a moderator status. There could be a place for Softwares in SA there.

What do you think about using that?
