### ISSUE TITLE
why there are multiple repeated parameter sets in the sample ? 

### ISSUE THREAD

**Issue by karimnorouzi** [SALib/SALib#471]
why there are some repeated parameters in the sample ? it means repeated model simulations that are not needed.

**Comment by ConnectedSystems** [comment]
Hello

Please see my answer here. Issue will be resolved soon.

https://github.com/SALib/SALib/issues/470#issuecomment-912109393

**Comment by karimnorouzi** [comment]
I don't understand the part that says eliminating repeated models can cause problems. Why not give the user only the unique parameter sets and then put the repeated solutions back in place.

**Comment by ConnectedSystems** [comment]
Closing - resolved in v1.4.5
