### ISSUE TITLE
Documentation Basic Example Result Inconsistent

### ISSUE THREAD

**Issue by natuspati** [SALib/SALib#475]
We followed the example shown on the [basics page](https://github.com/SALib/SALib/blob/main/docs/basics.rst), but we could not reproduce the results.

However, we obtained results identical to the script in the [folder examples](https://github.com/SALib/SALib/blob/main/examples/Problem/problem_spec.py). After correcting to the number of sample points

```python
from SALib.sample import saltelli
from SALib.analyze import sobol
from SALib.test_functions import Ishigami
import numpy as np
import os

#define function
def f(a, b):
    out1 = a + b
    out2 = a - b 
    return [out1, out2]

# def main():

problem = {
    'num_vars': 3,
    'names': ['x1', 'x2', 'x3'],
    'bounds': [[-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359],
               [-3.14159265359, 3.14159265359]]
}

param_values = saltelli.sample(problem, 2**10)

Y = Ishigami.evaluate(param_values)

Si = sobol.analyze(problem, Y)

print(Si['S1'])
print(Si['ST'])
```
Our results
- S1 results : 
    - 0.31683154
    - 0.44376306
    - 0.01220312
- ST results:
    - 0.55586009
    - 0.44189807
    - 0.24467539

**Comment by ConnectedSystems** [comment]
Hi, thanks for raising this 

We recently changed the number of samples used for these examples - obviously I/we missed updating the results too.

I believe the original example used 1000 as the number of samples points. 

I will update the example results over the next few days, thanks again.

**Comment by ConnectedSystems** [comment]
Thanks again for raising this issue @natuspati 

Please do let us know if you spot any other inconsistencies.

**Comment by babakkhavari** [comment]
Hello @ConnectedSystems,

It seems like the example has been updated on the **Basics** page but not on the **Getting Started** page of the documentation?

https://salib.readthedocs.io/en/latest/getting-started.html

**Comment by ConnectedSystems** [comment]
Thank you, have updated and this will be replaced on next release.
