### ISSUE TITLE
fast method has bug when compute S1_conf/ST_conf 

### ISSUE THREAD

**Issue by BeingHapppy** [SALib/SALib#480]
this is my setting:

```python
param_values = fast_sampler.sample(problem, N=4935, seed=100)  # N=4935
```
when the code do fast analyze as following sentence:
```python
Si = fast.analyze(problem, Y, print_to_console=True)
# len(Y) = 34545, because len(Y)= N*D (D is number of parameters, there D=7, I have 7 parameters to analysis)
```

**The bug is comming**:

```bash
  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\SALib\analyze\fast.py", line 83, in analyze
    S1_d_conf, ST_d_conf = bootstrap(Y_l, N, M, omega_0, num_resamples, conf_level)

  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\SALib\analyze\fast.py", line 116, in bootstrap
    S1, ST = compute_orders(Y_rs, N, M, omega_0)

  File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\SALib\analyze\fast.py", line 95, in compute_orders
    Sp = np.power(np.absolute(f[np.arange(1, int((N + 1) / 2))]) / N, 2)

**IndexError: index 2467 is out of bounds for axis 0 with size 2467**
```

In my opinion:
It is `np.arange(1, int((N + 1) / 2))` cause the bug, `np.arange` return is `[1,2,.....2467]`, however the lenth of f is 2467, the max index is 2466,  So, I think maybe File "C:\ProgramData\Anaconda3\envs\geo_env\lib\site-packages\SALib\analyze\fast.py", line 95, should change to `Sp = np.power(np.absolute(f[np.arange(0, int((N + 1) / 2)-1)]) / N, 2)`.  Do you think so?

Sorry, my English is poor, my code is also poor. I wish l describe the problem clearly.

**Comment by ConnectedSystems** [comment]
Hi @BeingHapppy welcome to the community, and thank you for reporting this issue.

Some minor advice: GitHub uses [Markdown](https://guides.github.com/features/mastering-markdown/) so you can format your text to make your posts clearer.

If you wrap your code with triple ticks (```), it will be formatted for you.

For example:

\```python
param_values = fast_sampler.sample(problem, N=4935, seed=100) # N=4935
\```

Will become:

```python
param_values = fast_sampler.sample(problem, N=4935, seed=100) # N=4935
```

---

@BeingHapppy if you need to resolve this quickly, I suggest using an even number of samples (e.g., use 4936 instead of 4935)

@jdherman I can recreate this reported issue using the [`lake_problem` function](https://github.com/SALib/SALib/blob/main/examples/Problem/multi_output.py) we have in the examples, which just so happens to also use 7 parameters.

This is to say, I don't think this is an issue with the problem specification.

```python
from SALib import ProblemSpec
from SALib.test_functions import lake_problem


seed_val = 101

sp = ProblemSpec({
    'names': ['a', 'q', 'b', 'mean', 'stdev', 'delta', 'alpha'],
    'bounds': [[0.0, 0.1], [2.0, 4.5], [0.1, 0.45], [0.01, 0.05], [0.001, 0.005], [0.93, 0.99], [0.2, 0.5]],
    'outputs': ['max_P', 'Utility', 'Inertia', 'Reliability']
})

(sp.sample_fast(4935)
    .evaluate(lake_problem.evaluate)
    .analyze_fast())

# IndexError: index 2467 is out of bounds for axis 0 with size 2467
```

I believe the below is the fix, which I will submit shortly.

```python
Sp = np.power(np.absolute(f[np.arange(1, math.floor(N / 2))]) / N, 2)
```

**Comment by chagas98** [comment]
I´m trying to run a sensitivity analysis with some ODEs and showed me up the same warning.

`from scipy import integrate as sp
import numpy as np
import SALib
from SALib.sample import saltelli
from SALib.analyze import sobol
from MasterModel import *
mat = [v, Ks, y, lamb, alphamax, sig, tmax,
             R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]
problem = {
  'num_vars': 23, #a's, b's and initial condition
  'names': ['v', 'Ks','y','lamb','alphamax','sig','tmax','R','DEGrna',
            'DEGamp', 'Kd', 'ktl', 'dig_rat', 'growthLeish', 'n',
            'Bsi', 'Si', 'Trigger', 'mRNA', 'mRNAon', 'proAMP', 'AMPa', 'Leish'],
  'bounds':  np.column_stack((np.array([[v, Ks, y, lamb, alphamax, sig, tmax,R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]])*0.8,
                              np.array([[v, Ks, y, lamb, alphamax, sig, tmax,R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]])*1.2))
}

# Generate samples
vals = saltelli.sample(problem, 512)

# initializing matrix to store output
Y = np.zeros([len(vals),1])
print(vals)
Y = np.zeros([len(vals),8])
print(Y)
for i in range(len(vals)):
  Y[i][:] = sp.odeint(modelkinetic,[vals[i][16],vals[i][17],vals[i][18],vals[i][19], vals[i][20],vals[i][21], vals[i][22], vals[i][23]],t,
    args=(vals[i][0],vals[i][1],vals[i][2],vals[i][3],vals[i][4],vals[i][5],
          vals[i][6], vals[i][7], vals[i][8], vals[i][9], vals[i][10], vals[i][11],
          vals[i][12],vals[i][13],vals[i][14],vals[i][15]))[len(ODE_Geral)-1]

  # completing soboal analysis for each X1, X2, and X3
  print('\n\n====X1 Sobol output====\n\n')
  Si_X1 = sobol.analyze(problem, Y[:, 0], print_to_console=True)
  print('\n\n====X2 Sobol output====\n\n')
  Si_X2 = sobol.analyze(problem, Y[:, 1], print_to_console=True)
  print('\n\n====X3 Sobol output====\n\n')
  Si_X3 = sobol.analyze(problem, Y[:, 2], print_to_console=True)

#And I got this information

Traceback (most recent call last):
  File "/home/samuel/PycharmProjects/ModellingGrowthProtein/SensitivityAnalysis.py", line 31, in <module>
    Y[i][:] = sp.odeint(modelkinetic,[vals[i][16],vals[i][17],vals[i][18],vals[i][19], vals[i][20],vals[i][21], vals[i][22], vals[i][23]],t,
IndexError: index 23 is out of bounds for axis 0 with size 23
`

**Comment by chagas98** [comment]
I´m trying to run a sensitivity analysis with some ODEs and showed me up the same warning.

`sdsdsdsd`

**Comment by chagas98** [comment]
I´m trying to run a sensitivity analysis with some ODEs and showed me up the same warning.

`from scipy import integrate as sp
import numpy as np
import SALib
from SALib.sample import saltelli
from SALib.analyze import sobol
from MasterModel import *
mat = [v, Ks, y, lamb, alphamax, sig, tmax,
             R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]
problem = {
  'num_vars': 23, #a's, b's and initial condition
  'names': ['v', 'Ks','y','lamb','alphamax','sig','tmax','R','DEGrna',
            'DEGamp', 'Kd', 'ktl', 'dig_rat', 'growthLeish', 'n',
            'Bsi', 'Si', 'Trigger', 'mRNA', 'mRNAon', 'proAMP', 'AMPa', 'Leish'],
  'bounds':  np.column_stack((np.array([[v, Ks, y, lamb, alphamax, sig, tmax,R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]])*0.8,
                              np.array([[v, Ks, y, lamb, alphamax, sig, tmax,R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]])*1.2))
}

# Generate samples
vals = saltelli.sample(problem, 512)

# initializing matrix to store output
Y = np.zeros([len(vals),1])
print(vals)
# Run model (example)
# numerically soves the ODE
# output is X1, X2, and X3 at the end time step
# could save output for all time steps if desired, but requires more memory
Y = np.zeros([len(vals),8])
print(Y)
for i in range(len(vals)):
  Y[i][:] = sp.odeint(modelkinetic,[vals[i][16],vals[i][17],vals[i][18],vals[i][19], vals[i][20],vals[i][21], vals[i][22], vals[i][23]],t,
    args=(vals[i][0],vals[i][1],vals[i][2],vals[i][3],vals[i][4],vals[i][5],
          vals[i][6], vals[i][7], vals[i][8], vals[i][9], vals[i][10], vals[i][11],
          vals[i][12],vals[i][13],vals[i][14],vals[i][15]))[len(ODE_Geral)-1]

  # completing soboal analysis for each X1, X2, and X3
  print('\n\n====X1 Sobol output====\n\n')
  Si_X1 = sobol.analyze(problem, Y[:, 0], print_to_console=True)
  print('\n\n====X2 Sobol output====\n\n')
  Si_X2 = sobol.analyze(problem, Y[:, 1], print_to_console=True)
  print('\n\n====X3 Sobol output====\n\n')
  Si_X3 = sobol.analyze(problem, Y[:, 2], print_to_console=True)`

And I got the follow information

Traceback (most recent call last):
  File "/home/samuel/PycharmProjects/ModellingGrowthProtein/SensitivityAnalysis.py", line 31, in <module>
    Y[i][:] = sp.odeint(modelkinetic,[vals[i][16],vals[i][17],vals[i][18],vals[i][19], vals[i][20],vals[i][21], vals[i][22], vals[i][23]],t,
IndexError: index 23 is out of bounds for axis 0 with size 23

**Comment by chagas98** [comment]
I´m trying to run a sensitivity analysis with some ODEs and showed me up the same warning.

`from scipy import integrate as sp
import numpy as np
import SALib
from SALib.sample import saltelli
from SALib.analyze import sobol
from MasterModel import *
mat = [v, Ks, y, lamb, alphamax, sig, tmax,
             R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]
problem = {
  'num_vars': 23, #a's, b's and initial condition
  'names': ['v', 'Ks','y','lamb','alphamax','sig','tmax','R','DEGrna',
            'DEGamp', 'Kd', 'ktl', 'dig_rat', 'growthLeish', 'n',
            'Bsi', 'Si', 'Trigger', 'mRNA', 'mRNAon', 'proAMP', 'AMPa', 'Leish'],
  'bounds':  np.column_stack((np.array([[v, Ks, y, lamb, alphamax, sig, tmax,R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]])*0.8,
                              np.array([[v, Ks, y, lamb, alphamax, sig, tmax,R, DEGrna, DEGamp, Kd, ktl, dig_rat, growthLeish, n, Bsi, Si, Trigger, mRNA, mRNAon, proAMP, AMPa, Leish]])*1.2))
}


vals = saltelli.sample(problem, 512)


Y = np.zeros([len(vals),1])
print(vals)


Y = np.zeros([len(vals),8])
print(Y)
for i in range(len(vals)):
  Y[i][:] = sp.odeint(modelkinetic,[vals[i][16],vals[i][17],vals[i][18],vals[i][19], vals[i][20],vals[i][21], vals[i][22], vals[i][23]],t,
    args=(vals[i][0],vals[i][1],vals[i][2],vals[i][3],vals[i][4],vals[i][5],
          vals[i][6], vals[i][7], vals[i][8], vals[i][9], vals[i][10], vals[i][11],
          vals[i][12],vals[i][13],vals[i][14],vals[i][15]))[len(ODE_Geral)-1]

  # completing soboal analysis for each X1, X2, and X3
  print('\n\n====X1 Sobol output====\n\n')
  Si_X1 = sobol.analyze(problem, Y[:, 0], print_to_console=True)
  print('\n\n====X2 Sobol output====\n\n')
  Si_X2 = sobol.analyze(problem, Y[:, 1], print_to_console=True)
  print('\n\n====X3 Sobol output====\n\n')
  Si_X3 = sobol.analyze(problem, Y[:, 2], print_to_console=True)
`

**Comment by BeingHapppy** [comment]
Hello@chagas98, I don’t think we have the same problem. I have 7 parameters to analyze. But I do not get
```python
 #IndexError: index 7 is out of bounds for axis 0 with size 7
```
I agree with @ConnectedSystems  , you are better to open a new issue.
