### ISSUE TITLE
MorrisAnalyzer fails for single group

### ISSUE THREAD

**Issue by FWuellhorst** [SALib/SALib#483]
I am using v 1.4.5 of the SALib and I'm getting the following error when analyzing one single variable:
```
  File "C:\...\SALib\sample\morris\morris.py", line 113, in sample
    sample_morris = _sample_morris(problem, N, num_levels)
  File "C:\...\SALib\sample\morris\morris.py", line 148, in _sample_morris
    group_membership, _ = compute_groups_matrix(groups)
  File "C:\...\SALib\util\__init__.py", line 254, in compute_groups_matrix
    num_vars = len(groups)
TypeError: object of type 'bool' has no len()
```

This results out of these two lines in morris.py:
```
    groups = _check_groups(problem)
    group_membership, _ = compute_groups_matrix(groups)
```
`_check_group` returns false for a single group. 

Two solutions:
1. Allow single groups
2. Raise a more meaningful error. If Morris analysis is not possible for single variables, the error message should state that.

**Comment by ConnectedSystems** [comment]
Hi,

A single variable or a single group?

If a single variable, then you don't need to specify groups at all, although I agree it should bypass the group check in that case.
