### ISSUE TITLE
Groups for Delta-moment independent method

### ISSUE THREAD

**Issue by lb1609** [SALib/SALib#487]
Hi, 

I was wondering if you are also planning to implement the possibility to use groups of parameters for the Delta-moment independent method as is already the case for Sobol and Morris?

**Comment by ConnectedSystems** [comment]
Hello,

Yes, we do have plans for it but it won't happen any time soon as we're all pressed for time.
If you're willing to help, do let me know.

**Comment by ConnectedSystems** [comment]
Hi again,

I have a very preliminary version here: https://github.com/ConnectedSystems/SALib/tree/delta-group

Please be completely aware that this is an unfinished, untested implementation.

The only check I've done so far is confirm that the factor rankings are similar to the Saltelli approach when applied to the Ishigami test function. Outside of that, nothing is guaranteed.
