### ISSUE TITLE
SALib 1.4.5 upgrade issue - index 32 is out of bounds for axis 0 with size 32

### ISSUE THREAD

**Issue by prasadkumar0590** [SALib/SALib#492]
Hi Team, we have 15 input problem and we were able to run the problem on SALib 1.3.8 but upgrading to 1.4.5 we are getting below error

index 32 is out of bounds for axis 0 with size 32

we are getting error in analyse/fast.py line number 95

def compute_orders(outputs, N, M, omega):
    f = np.fft.fft(outputs)
    **Sp = np.power(np.absolute(f[np.arange(1, int((N + 1) / 2))]) / N, 2)** # error line

Please let us know if you need some more information. Your help will be appreciated greatly.

**Comment by ConnectedSystems** [comment]
Hi @prasadkumar0590 

This looks related to https://github.com/SALib/SALib/issues/480

We have a fix coming, just need a few things confirmed.
In the meantime, is it possible to adjust the number of samples to an even number?

Alternatively, you could try the fix here: https://github.com/ConnectedSystems/SALib/tree/fix_fast_analysis_480

You should be able to install it with:
`pip install -U git+https://github.com/ConnectedSystems/SALib.git@fix_fast_analysis_480`

**Comment by jennywang123** [comment]
Thank you for the response. I saw that in eFAST new version, you added confidence interval, this is good. Look forward to next official release.

**Comment by ConnectedSystems** [comment]
Closed by #481
