### ISSUE TITLE
Performance issue with delta method

### ISSUE THREAD

**Issue by sofianehaddad** [SALib/SALib#493]
Hi,

I noticed that `delta.analyze` can be too much CPU/time consuming in case of high dimension, large datasets and many `num_samples` for the estimation of confidence interval. A quick analysis highlights that the current implementation might be performed. 

Indeed, considering [current implementation](https://github.com/SALib/SALib/blob/main/src/SALib/analyze/delta.py#L81), we rely on the evaluation of `f_y` density. for the estimation of the `delta` sensitivity. This density is estimated on samples of size `N` (that can be large) many times ( `D x num_samples` times). We can focus on [calc_delta](https://github.com/SALib/SALib/blob/main/src/SALib/analyze/delta.py#L100) and how it is called through [bias_reduced_delta](https://github.com/SALib/SALib/blob/main/src/SALib/analyze/delta.py#L133) for example. In fact we are computing the same quantity many times whereas only o1 evaluation is required and provided to these routines.

Changing this might significantly improve efficiency/maintainability without changing any result

**Comment by ConnectedSystems** [comment]
Hi @sofianehaddad 

Thank you for taking the time to flag this issue, I'll take a look when I can.

**Comment by ConnectedSystems** [comment]
Hi @sofianehaddad 

> We can focus on calc_delta and how it is called through bias_reduced_delta for example. 

> In fact we are computing the same quantity many times whereas only o1 evaluation is required and provided to these routines.

Unfortunately, this is not the case here. The repeated evaluations are to produce estimates of the confidence bounds.
The default number of resamples is 100, so you could adjust this as you deem fit for your purpose and potentially reduce computational burden.

Thanks for having look anyway!
