### ISSUE TITLE
Too high dimensional data to use sample(N, D) in SALib/sample/sobol_sequence.py

### ISSUE THREAD

**Issue by elenaraponi** [SALib/SALib#494]
Hi, 

When trying to use the `sample` method in `SALib/sample/sobol_sequence.py`, 

`ValueError: Error in Sobol sequence: not enough dimensions` is raised. 

I think that the problem is related to the fact that the list defined in `directions.py` is not big enough to pass the check.  I have to deal with 27005 variables, which are doubled when calling the `sample` method inside  `SALib/sample/saltelli.py`. Can the directions be augmented or is there a reason why they stop there (i.e., it does not make sense to address such high dimensional problems with Sobol SA)?

Thank you in advance!
Elena

**Comment by ConnectedSystems** [comment]
That's a lot of variables!

SALib v1.4.5 and before uses an older set of direction numbers that only go up to 21000 dimensions.
The next release makes use of a newer set that go up to 21201.

I've just merged in this change into the `main` branch. You should be able to install it from the repo directly with:

`pip install -U git+https://github.com/SALib/SALib.git@main`

Let me know if you run into any issues

**Comment by ConnectedSystems** [comment]
Sorry, just realised you said the dimensions will be doubled?

Not sure if I'm understanding correctly but if the updated SALib doesn't work, it's likely you'll have to make your own sampling/analysis functions.

I believe you should be able to leverage this function in SciPy

https://scipy.github.io/devdocs/reference/generated/scipy.stats.qmc.Sobol.html

**Comment by elenaraponi** [comment]
Ok. Thanks a lot for your feedback and the tip! 

Yes, they're a lot of variables, which I could handle with Morris sample/analysis functions (from your package). I will use SpiPy then.

**Comment by elenaraponi** [comment]
The dimensions are doubled inside your library, before checking `calc_second_order`. Here: https://github.com/SALib/SALib/blob/57827cd4d1582c04c9cd602d7f7aec08d50827b7/src/SALib/sample/saltelli.py#L139

**Comment by ConnectedSystems** [comment]
Ah, this is creating the matrix for cross-sampling, so it isn't really doubling the number of variables.

With that high dimensionality it will be highly memory intensive though, I won't be surprised if you hit some out of memory error, even using SciPy directly

**Comment by elenaraponi** [comment]
Yes, sorry. It's doubling the D input to `sample(N, D)` in `sobole_sequence.py`, which is checked here and compared to `len(directions)`:

https://github.com/SALib/SALib/blob/57827cd4d1582c04c9cd602d7f7aec08d50827b7/src/SALib/sample/sobol_sequence.py#L54

In the description of the SciPy method, they also say that "Max dimensionality is 21201". So I think it won't solve the problem. But thanks anyway for your time and assistance!

**Comment by ConnectedSystems** [comment]
There's also this program by Prof. Kuo (see under "Simple C++ program")

https://web.maths.unsw.edu.au/~fkuo/sobol/index.html

You'll have to modify it as suggested to generate the sequence one point at a time for your purposes though.

In any case, good luck!
