### ISSUE TITLE
Method of Morris

### ISSUE THREAD

**Issue by aagnesina** [SALib/SALib#497]
Hello,

The original paper assumes the problem bounds are the unit hypercube. Do we need to normalize the problem first or is it done automatically in the implementation?

Thanks.

**Comment by ConnectedSystems** [comment]
Hi @aagnesina 

If by "normalize the problem", you're referring to the model parameters (or input factors), then yes, these are automatically scaled.

**Comment by aagnesina** [comment]
Hi,
Yes by problem I mean input factors. Thanks a lot for the prompt answer!
