### ISSUE TITLE
Confirm FAST analysis issue is resolved

### ISSUE THREAD

**Issue by ConnectedSystems** [SALib/SALib#499]
Hi @prasadkumar0590, @jennywang123, @BeingHappy

I have just added a pre-release to PyPI (v1.4.6-beta0, see [notes here](https://github.com/SALib/SALib/releases/tag/v1.4.6-beta.0)) which contains a fix to the FAST analysis issues you encountered, as well as tentative support for confidence intervals.

If you can, could you please try it and let me know if it resolves your specific use cases or if the issue still remains?

You can try out the pre-release version by installing it from PyPI directly with:

```bash
pip install SALib==1.4.6b0 --pre
```

Thank you

**Comment by jennywang123** [comment]
I tried and can not install 1.4.6b0. I can install 1.4.5 though.

Thank you
Jenny

**Comment by jennywang123** [comment]
I can install 1.4.6b0, the issue seems to be resolved. Thank you.
