### ISSUE TITLE
Often times main sensitivity index is bigger than total sensitivity indi

### ISSUE THREAD

**Issue by jennywang123** [SALib/SALib#500]
![Capture](https://user-images.githubusercontent.com/26229103/152700630-e8caafcc-0ac6-405e-be3a-579b5d6c9c42.JPG)

**Comment by ConnectedSystems** [comment]
Hello

S1 can be larger than ST for many reasons. This can be due to numerical error, correlations/interactions between parameters or insufficient sample size.
