### ISSUE TITLE
Giving error as "bounds are not legal".

### ISSUE THREAD

**Issue by Sumit9013** [SALib/SALib#501]
Hello all,

I have just started using SALib and have come across the error: 

```
runfile('V:/study_material/uncertainty/untitled0.py', wdir='V:/study_material/uncertainty')
Traceback (most recent call last):

  File "V:\study_material\uncertainty\untitled0.py", line 19, in <module>
    param_values = saltelli.sample(problem, 4096)

  File "C:\Users\AppData\Local\Continuum\anaconda3p7\envs\Uncertain\lib\site-packages\SALib\sample\saltelli.py", line 65, in sample
    scale_samples(saltelli_sequence, problem['bounds'])

  File "C:\Users\AppData\Local\Continuum\anaconda3p7\envs\Uncertain\lib\site-packages\SALib\util\__init__.py", line 24, in scale_samples
    raise ValueError("Bounds are not legal")

ValueError: Bounds are not legal
```

The problem definition is given below:
```
from SALib.sample import saltelli
from SALib.analyze import sobol
import numpy as np

# Define the model inputs
problem = {
    'names': ['x1', 'x2', 'x3'],
    'num_vars': 3,
    'bounds': [[10,2], [25,5], [32,9]],
    'dists': ['norm', 'norm', 'norm']
}
param_values = saltelli.sample(problem, 4096)
```
Could anyone please hint me about the error in the code?
Thanks in Advance

**Comment by ConnectedSystems** [comment]
Hello,

If you are using `norm` (normal distribution), the bounds are interpreted as the mean and standard deviation of the distribution, rather than the parameter bounds per se.

https://salib.readthedocs.io/en/latest/advanced.html

**Comment by Sumit9013** [comment]
How do i define it in those lists with key `'bounds'` the first entry in every list is mean and other is SD.
if it is not much work for you, could you please define the problem correctly for me?

Thanks in advance

**Comment by Sumit9013** [comment]
the issue is resolved in the latest release. i was using 0.5 after upgrading to 1.4.5 it isn't throwing the error

**Comment by ConnectedSystems** [comment]
Wow, 0.5 is a very old release!

Glad you found a way forward, I will close this issue now.

**Comment by EwoutH** [comment]
I have the same issue. My problem is defined as:
```Python
from SALib.sample import saltelli

problem = {
    'names': ['Q', 'Ks', 'Zv', 'Zm'],
    'num_vars': 4,
    'bounds': [[49, 51], [30.0, 8.0], [49, 51], [54, 56]],
    'dist': ['unif', 'norm', 'unif', 'unif']
}

param_values = saltelli.sample(problem, 1024)
```
The last line gives `ValueError: Bounds are not legal`.

Tested with both SALib `1.4.5` and `1.4.6b0`, both give the same error.

Can anyone reproduce this and/or know how to solve this?

**Comment by ConnectedSystems** [comment]
@EwoutH 

I think there is a typo in your problem specification: `dist` should be `dists` (note the missing `s`)

Otherwise, as I write above, check that the values in "bounds" are given as the mean and standard deviation as opposed to the parameter bounds themselves.

https://salib.readthedocs.io/en/latest/advanced.html

**Comment by EwoutH** [comment]
> I think there is a typo in your problem specification: `dist` should be `dists` (note the missing `s`)

@ConnectedSystems Thanks a lot, that was indeed the case, weird that I didn’t notice that.

With this problem dict, the `saltelli.sample` function gives a `ValueError`, suggesting something is wrong with the values of the bound. Maybe a warning (or error) could be cast if an unrecognized dict key is detected in the problem dictionary?
