### ISSUE TITLE
Problem with eFAST conf interval calculations - intervals change on recalculation with static dataset

### ISSUE THREAD

**Issue by natalie-morris** [SALib/SALib#504]
Hi,

I'm using the eFAST analysis function. I was rerunning the index calculation on a saved output dataset and noticed that while the S1/ST values recalculate to the same value, their confidence intervals keep changing. I'm not sure what's causing this.

My code is: 
~~~
X = np.load('output.npy')
Si_X1 =  fast.analyze(problem, X[:,0], print_to_console=True)
~~~
This is looking at one of four model outputs (X is an array of shape (1000,4)).

So on each rerun I get:
A - S1 = 0.072010, ST = 0.090011
B - S1 = 0.898752, ST = 0.923655

But the conf intervals change - on the first run:

A - S1_conf = 0.015654; ST_conf = 0.036531
B - S1_conf = 0.015515; ST_conf = 0.038035

Then I run it again and get:

A - S1_conf = 0.016507; ST_conf = 0.041802
B - S1_conf = 0.14987 ; ST_conf = 0.033161

I'm using SALib 1.4.5, and python 3.8

I also noticed that the sum of the S1 values is less than 1 - does anyone have an idea as to why this may be? (I've only been able to find explanations for the sum being >1)

Thanks for your help

**Comment by ConnectedSystems** [comment]
Hi @natalie-morris 

The confidence intervals are determined via bootstrapping, which involves taking pseudo-random samples from the analysis results.

If you want confidence bounds to be the same, set the `seed` parameter, for example:

```python
fast.analyze(problem, X[:,0], print_to_console=True, seed=101)
```

Although this should return the same values across runs, we cannot offer any guarantees that the specific values you see will remain the same for all time as the pseudo-random generator/process can change. This is true for all computing environments, and is not specific to SALib or Python.

Note that if the CI differs significantly when `seed` is not set, it can indicate that the sensitivity measure has not yet converged.

> I also noticed that the sum of the S1 values is less than 1 - does anyone have an idea as to why this may be?

As far as I'm aware this can be explained by the same reasons for why S1 can be > 1, parameter correlation and interactions.

**Comment by ConnectedSystems** [comment]
Closing as I am assuming this issue is now resolved. Feel free to re-open if this is not the case.
