### ISSUE TITLE
How to handle integer parameter？

### ISSUE THREAD

**Issue by FOANFAN** [SALib/SALib#506]
What I want to do is building energy consumption analysis, some variables are integer types (such as weather file 1, weather file 2), how can I get integer parameters when sampling？

**Comment by ConnectedSystems** [comment]
Hello,

In such cases I use what I call the "flooring trick" (note this is just what I call it). 

The idea is adapted from the "General Probabilistic Framework" described in [Baroni and Tarantola (2014)](https://doi.org/10.1016/j.envsoft.2013.09.022) as well as others before them.

The process in this case would be:
1. For any integer parameters, increase the upper bound by 1 (e.g., `b + 1.0`, where `b` is the upper bound)
2. Generate samples
3. Post-process samples back to integers

The post-processing is to:
- Search for any sample that is `b + 1.0` and replace with `b` (this is on the off-chance that the sampled value is exactly `b + 1`)
- For all other values, floor the sampled value (e.g., `np.floor()`) to transform these into a whole number value

This allows you to produce a discretized sample

**Comment by FOANFAN** [comment]
Thank you for your answer!

**Comment by FOANFAN** [comment]
Thank you for your answer!

**Comment by willu47** [comment]
See also #112
