### ISSUE TITLE
How to use SALib for time series input data?

### ISSUE THREAD

**Issue by JoCook1997** [SALib/SALib#513]
Hi,

I have been using the SALib library to vary individual constant parameters in the config file of a model, and see how changing those affects the output parameters of interest. I am now interested in seeing how the input data affects the output parameters of interest in the model. The model has an input file with hourly data such as temperature, rainfall and light. I wanted use the sensitivity analysis to see how varying those between limits of +/-10% of what they are in the current input changes the outputs. In this way I can see which are the key input variables driving the changes in my model output. In total there are 7 hourly input variables which I want to vary by +/- 10%. 
I can't see any examples for the SALib library to do this kind of analysis. I wanted to ask if it was possible, and if it is possible, where I can find an example to follow.
If it's not possible in SALib but someone else knows of a source/ paper that I can use to help me with this I would be very grateful.

Thank you,

Jo

**Comment by ConnectedSystems** [comment]
Hi @JoCook1997 

I can better help if you provide a minimum working example (MWE), but I see several ways you can do the analysis you're after. I've listed the two main ones below.

1. Analyze the temperature/rainfall/light/etc data you have currently to determine their respective min/max bounds, and run the model with values sampled from that range +/- 10%. In effect you will be running a set of 1-hour simulations. This approach assumes time is not a factor to the model and so does not influence outputs - it is a direct analysis of the model at a single time step.

2. Formulate the problem such that the inputs to the `problem spec` represent the percent variation.

For example, for a three parameter model:

```python
problem = {
  'num_vars': 3,
  'names': ['var_x1', 'var_x2', 'var_x3'],
  'bounds': [[-0.1, 0.1]]*3
}
```

Your model should then be wrapped, and the percent deviation applied to each variable for its given time series.

Something like:

```python
def wrapped_model(X):
    original_data = ... # Load the data to be perturbed

    # Each column of X should relate to a column in `original_data`
    
    # Run model for each scenario
    Y = np.zeros(N,D)  # where N is number of time steps, D is number of outputs (remove `D` if there is only 1 metric)
    for i in range(X.shape[0]):
        # Apply the perturbation and run the model with perturbed inputs
        Y[i] = actual_model(original_data + X[i, :])
    
    return Y
```

This approach assumes you are okay with a constant variation for each parameter for a given simulation.

I could probably give more advice if you provide an MWE, but hope the above is enough to get you started.

**Comment by JoCook1997** [comment]
Hi both,

Thank you so much for your suggestions and the resource. I have an understanding now of how best to proceed, thank you!

Jo
