### ISSUE TITLE
Question: Can I add samples to an existing Saltelli sequence?

### ISSUE THREAD

**Issue by MarAlder** [SALib/SALib#518]
Hi,

I really enjoy applying SALib for Sensitivity Analyses. From a user's point of view, I have the following question:

### Problem description
Let's say I have the following problem specification:
```python
problem = {
        "num_vars": 2,
        "names": ["var1", "var2"],
        "bounds": [[-2000.0, 2000.0], [0.90, 1.1]],
    }
```
I generate a LDS via:
```python
saltelli.sample(problem, N, calc_second_order=False)
```
to compute the Sobol indices:
```python
sobol.analyze(problem, Y, calc_second_order=False)
```

### Question
If run the analysis to compute `Y` and then conclude that I would need, e.g., `N=1024` samples rather than `N=512` to get a satisfactory convergence of my Sobol indices, can I re-use the previous samples and calculations by extending the existing sequence? I'm not too deep into the theory of LDS, but found something like this at [qmc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.qmc.Sobol.html#scipy.stats.qmc.Sobol) for Sobol sequences (see `To continue an existing design, extra points can be obtained by [...]`). 

I played with the sampler and found that the first 16 values generated by `saltelli.sample(problem, 4, calc_second_order=False)` and `saltelli.sample(problem, 16, calc_second_order=False)` are equal. However, the first 64 values of `saltelli.sample(problem, 16, calc_second_order=False)` and `saltelli.sample(problem, 32, calc_second_order=False)` do not match. Therefore, I wonder if I must compute all samples again?

I appreciate your response! Thanks,
Marko

PS: I think I don't have the rights to add the `question_interpretation` label.

**Comment by tupui** [comment]
Hi @MarAlder this is because of the `skip_values` parameter which is "kicking in". Otherwise samples from the small sample should be present in the other one. Otherwise Sobol' being a sequence, you are able to reuse the previous samples as Saltelli's method is just a shuffling on the dimensions, not the number of samples.

**Comment by MarAlder** [comment]
Ah ok, thank you!
