### ISSUE TITLE
Use pydata-sphinx-theme

### ISSUE THREAD

**Issue by tupui** [SALib/SALib#520]
Are you interested in using the PyData-Sphinx theme? This theme is used by an increasing number of libraries including SciPy, NumPy and Pandas.

https://pydata-sphinx-theme.readthedocs.io

I can do the work if wanted 😃

**Comment by ConnectedSystems** [comment]
@sahin-abdullah you indicated you were interested in updating the documentation style, to the same theme if I remember correctly.

Have you looked into this at all since our last chat, or are you happy for @tupui to look into this? Or would you two like to coordinate?

**Comment by tupui** [comment]
I am happy to review as well. I have a lot of experience with the theme as I am following its development and doing things from time to time.

**Comment by sahin-abdullah** [comment]
@ConnectedSystems No Takuya. I have not started working on this theme because I got hired recently. But, I can work with @tupui on this. I was planning to add some explanation to the methods we have in SALib. If @tupui is OK, we can work together.

**Comment by tupui** [comment]
@sahin-abdullah sure! 😃 What do you want me to do? I suppose I can work on the setup/infrastructure itself and you work on the content, e.g. what to put in the navbar. Let me know if you want to start a PR or if I should.

**Comment by ConnectedSystems** [comment]
cc @willu47 just so you're aware
