### ISSUE TITLE
Make Pathos an optional dependency

### ISSUE THREAD

**Issue by tupui** [SALib/SALib#521]
As far as I can see in the code, Pathos is only required in a single function to run distributed runs.

I propose to make it an optional dependency to lower the footprint of the library.

It should just consist in a condition at the top checking for the import, set a flag and then in the function if would use the flag to report a missing deps.

I can do the work if wanted.

**Comment by ConnectedSystems** [comment]
This has been on my todo list for a while.

Were you thinking of moving it as an extra dependency in the conda/pip spec?

I think a try/except around the import would be cleaner than setting a global flag.

**Comment by tupui** [comment]
Yes we can make it optional there as well. I can make a PR if wanted

**Comment by tupui** [comment]
To be clear, I was talking about using a try except block at the beginning which is a common pattern found in other libraries.

**Comment by tupui** [comment]
I started to work on that, and there is actually another dependency that we can think about removing: `multiprocess`. It's currently being pulled by Pathos.

Any reason this is used? SciPy for instance just uses plain multiprocessing for its optimizers and others.

**Comment by ConnectedSystems** [comment]
> Any reason this is used?

Why we use Pathos? It has a nice accessible interface that I found preferable to the `multiprocessing` package. It supports serialization of a wider range of objects which `multiprocessing` does not and supports distributed runs on HPCs which, again, `multiprocessing` does not (at least last I checked).

**Comment by tupui** [comment]
I meant about the library `multiprocess`

**Comment by ConnectedSystems** [comment]
> I meant about the library `multiprocess`

Ah, hmmm. It's been a while so not 100% sure on that one. It may be a stray dependency back when I was working on parallelization (as you note it gets pulled in by Pathos but is not used by SALib directly).

Thanks for all the work you've been doing, I will hopefully get some time this weekend to review and merge.

**Comment by tupui** [comment]
Thanks! I updated the PR. `multiprocess` is actually directly used in 2 places. I just made it optional as it can be replaced directly with the standard library. cf the PR.
