### ISSUE TITLE
Consider/investigate alternate packaging tool(s)

### ISSUE THREAD

**Issue by ConnectedSystems** [SALib/SALib#524]
Raised in #522 , there are newer packaging tools (Flit, Hatchling) that may help reduce maintenance overhead

https://packaging.python.org/en/latest/tutorials/packaging-projects/

cc @willu47 @tupui 

Primary question that comes to mind is: are there any pros/cons with our current setup vs these newer tools (e.g., if we end up incorporating Cython)

**Comment by ofek** [comment]
Maintainer of Hatchling here!

> current setup vs these newer tools (e.g., if we end up incorporating Cython)

Hatchling has plugins and also allows for custom build steps like setuptools

**Comment by tupui** [comment]
Thank you @ofek for stopping by. I was trying to look into this yesterday actually and was not sure about how to make a build command to handle Cython files. It looks like Hatchling would be a great solution then if that can be done easily.

To answer the other question about the benefits of moving. Yes it would really simplify the packaging. We can remove all files but `pyproject.toml` and the only tool we need is Hatchling. No more wheel, setuptools and pyscafolding.

**Comment by ConnectedSystems** [comment]
> the only tool we need is Hatchling. No more wheel, setuptools and pyscafolding

This sounds appealing.

@ofek I had a quick look over the documentation and although it says hatchling can publish to other sources (https://hatch.pypa.io/latest/), it wasn't immediately clear to me if this included conda/conda-forge.

@willu47 Any other thoughts or additional considerations? As per discussion in #445 I don't this change to impact our current documentation deployment.

**Comment by tupui** [comment]
Conda-forge needs a recipe in any case and it's not a problem or more complicated to have Hatchling here 😃

**Comment by ofek** [comment]
> hatchling can publish to other sources [...] it wasn't immediately clear to me if this included conda/conda-forge

You can write a [publisher plugin](https://hatch.pypa.io/latest/plugins/publisher/reference/) but there's really no point because the feedstock bot automatically opens PRs when it sees new releases.

> how to make a build command to handle Cython files

You can write a [custom](https://hatch.pypa.io/latest/plugins/build-hook/custom/) build hook.

`pyproject.toml`:
```toml
[tool.hatch.build.targets.wheel.hooks.custom]
dependencies = ["setuptools", "cython"]
```

`hatch_build.py`:
```python
from hatchling.builders.hooks.plugin.interface import BuildHookInterface

class CustomBuildHook(BuildHookInterface):
    def initialize(self, version, build_data):
        import subprocess
        import sys

        subprocess.check_output([sys.executable, __file__, 'build_ext', '--inplace'])

if __name__ == '__main__':
    from Cython.Build import cythonize
    from setuptools import setup
    from setuptools.extension import Extension

    setup(
        name='cython_output',
        ext_modules=cythonize(...),
    )
```

**Comment by ConnectedSystems** [comment]
Thanks @ofek !

**Comment by tupui** [comment]
@ofek Are there plans to have a somewhat official plugin for Cython? I suppose that is going to be a very common thing people will want/ask.

I also suppose we can chain plugins? Like have one for Cython, another for Pythran, etc.

**Comment by ofek** [comment]
> Are there plans to have a somewhat official build hook for Cython?

There will definitely be a build hook for Cython but I'm not experienced enough to know what that static config might look like.

> I also suppose we can chain plugins? Like have one for Cython, another for Pythran, etc.

Yup!

**Comment by willu47** [comment]
> @willu47 Any other thoughts or additional considerations? As per discussion in #445 I don't this change to impact our current documentation deployment.

@ConnectedSystems @tupui - My main objection to moving from PyScaffold to an alternative is that I'll need to learn something new! The latest version of Pyscaffold uses tox, which seems great for running tests and building and deploying packages. PyScaffold just sets up the package, similar to a cookie-cutter. It doesn't add any dependencies. At the moment, we're using Travis CI, but we could relatively easily move to Github Actions, which I've found to be much faster to run than Travis.

To add or remove dependencies to SALib, you only need to edit the `setup.cfg` file under the entry `install_requires`.  The contents of the `requirements.txt` is not used for installation, only for developers who wish to set up a fixed environment.

So I am not opposed to migrating to new tools, but it is not clear if that will significantly change the admin overhead (and then why not poetry etc.?).

**Comment by willu47** [comment]
Releases are already automated through a deploy stage on Travis. Just create and push an annotated tag to the master branch and a new release will be created on PyPi.

I'm happy to see this migrated to GitHub actions along with the testing, as it would remove Travis from the CI and be more streamlined.

**Comment by tupui** [comment]
@willu47 shall I make a PR that move to GitHub Actions and also does the migration to Hatchling? Or just moving the CI?

**Comment by willu47** [comment]
Hi @tupui - yes, that would be great.
