### ISSUE TITLE
Allow user-provided X for SALib.analyze.sobol.analyze

### ISSUE THREAD

**Issue by bbantal** [SALib/SALib#528]
My use-case involves a function which is interpretable only at select _x_ inputs. For this reason I have my own pair of X and Y. X was originally sampled with sobol sequence but then was altered with custom filters. In contrast, SALib.analyze.sobol.analyze seems to be limited to an unaltered sample drawn with Saltelli sampling. This is incompatible with my use-case. Any chance it would become possible in the near future to pass my own X-Y datapairs to SALib.analyze.sobol.analyze?

An alternative solution would be if I could pass a Y containing NaNs to SALib.analyze.sobol.analyze but that doesn't seem to work either.

**Comment by willu47** [comment]
Hi @bbantal - you cannot use sobol.analyze with your own sample-result pairs. The Sobol approach requires that you use a particular sample structure (see the paper referenced in the SALib documentation). I suggest you investigate using alternative approaches, such as dmim or dgsm, which allow you to use any sample structure.

**Comment by ConnectedSystems** [comment]
Just to note PAWN and HDMR are also "given data" methods as well. 

PAWN is comparatively computationally cheaper than DMIM, and HDMR being more.

**Comment by bbantal** [comment]
Many thanks for these highly useful suggestions. I recognize "holes" in the structure of X, which applies to my case, can bias the output from Sobol's approach. I'll go with one of your recommendations instead, once I understand them.
