### ISSUE TITLE
Logo for SALib

### ISSUE THREAD

**Issue by sahin-abdullah** [SALib/SALib#529]
Hi,

I was wondering how do you guys think of having a logo for SALib project. It might be good to put it on the readthedocs page. I found Adobe's online platform that allows you to make logo for free. Here is the link to that page: https://www.adobe.com/express/create/logo

I created one logo on this website. What do you guys think? Do you have any input on the design? I thought having a pie chart on the logo would be nice because of apportioning model outputs to the its inputs. I am leaving two samples here. 

<img src="https://user-images.githubusercontent.com/48244771/187428288-ac2532f3-3a63-455d-beab-287f0be7d8a9.jpeg" width=100>

<img src="https://user-images.githubusercontent.com/48244771/187428699-6c0e7448-5660-4cc7-ab17-c61d65b78c33.png" width=100>

**Comment by tupui** [comment]
I like the idea!

I am afraid this is more or less Matplotlib's logo, so it might be confusing. Following on your idea, it could also be a bar chart or a stacking of a few bars of different sizes/shapes.

**Comment by ConnectedSystems** [comment]
> I am afraid this is more or less Matplotlib's logo

Oh shoot, it is too! @sahin-abdullah what about the other one you showed me, the one with the connected nodes?

**Comment by tupui** [comment]
A wild option that Hatch went with is actually to ask Dall.E to generate a logo 😅 and the output is actually not that bad.

**Comment by willu47** [comment]
I've always used the visual metaphor of a black-box with a bunch of levers that you move around to view the output. I think that might make a cool logo - kind of across between [Bertha](https://en.wikipedia.org/wiki/Bertha_(TV_series)), an excavator cockpit, and a [polygraph](https://en.wikipedia.org/wiki/Polygraph#:~:text=A%20polygraph%2C%20often%20incorrectly%20referred,answers%20a%20series%20of%20questions.)

**Comment by sahin-abdullah** [comment]
Here is my three candidates of logo. It does not have be one of these. Since these are easy to make, also we can't make one that is exactly in our mind.  Colors and other arrangements can be changed.

<img src="https://user-images.githubusercontent.com/48244771/188765165-1c5e4d53-e32e-41a7-ab18-d608d0cca0af.jpeg" width=200>

<img src="https://user-images.githubusercontent.com/48244771/188765315-fe1bac84-7cac-4885-b438-5de5332164c4.png" width=200>

<img src="https://user-images.githubusercontent.com/48244771/188765357-794d1058-f016-4d46-bd6c-3395a9a391ff.jpeg" width=200>

I liked the last one most. Seems more appropriate.

**Comment by ConnectedSystems** [comment]
Last one is my favourite so far too. We may want to adjust the font but it looks great to me!

**Comment by tupui** [comment]
I like the first one as the lever idea would work good for a small icon (like a favicon).

The last one is also cool. Looks a bit like some Ishigami.

**Comment by ConnectedSystems** [comment]
Here is my humble contribution which attempts to bring the elements discussed above together.

The nodes attempt to evoke a graph network as well as control levers.

![image](https://user-images.githubusercontent.com/4075136/194678726-66b69ae4-8fb7-413d-b64f-6cc8c99779ac.png)
