### ISSUE TITLE
Readme installation instructions are out of data

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#531]
Following the update to hatchling (#527), there is no setup.py file, so `pip install -e .` and `python setup.py install` no longer work, but are still listed in the `readme.rst` file.

**Comment by willu47** [comment]
@tupui

**Comment by tupui** [comment]
`pip install -e .` does work (this is also used in the CI without the `-e`). Your version of `pip` might be too old. What error do you get?

**Comment by ConnectedSystems** [comment]
I can confirm `pip install -e .` does work, but I did have to completely recreate my conda env.

**Comment by willu47** [comment]
Okay, did not work with pip `21.2.4`, does work with pip `22.2.2`. I am surprise hatch doesn't have the later pip version as a constraint?

**Comment by tupui** [comment]
It's a bit of a chicken egg issue there. If pip is too old to read the pyproject.toml, then it cannot really read any deps and update pip itself. And I don't think there is such thing as specifying a minimal pip version as the version of pip or conda/mamba is not the responsibility of the package or packaging tool.

**Comment by ofek** [comment]
PEP 660 (`-e`) landed in https://pip.pypa.io/en/stable/news/#v21-3
