### ISSUE TITLE
Returning variance instead of sobol index 

### ISSUE THREAD

**Issue by ChitraDangwal** [SALib/SALib#534]
If I wanted the variances (the numerator) part in sobol index instead of sobol index is the following change in sobol.py enough?

def first_order(A, AB, B):
    # First order estimator following Saltelli et al. 2010 CPC, normalized by
    # sample variance
    return np.mean(B * (AB - A), axis=0) / ; #  np.var(np.r_[A, B], axis=0).  (**Commenting out the denominator**)

def total_order(A, AB, B):
    # Total order estimator following Saltelli et al. 2010 CPC, normalized by
    # sample variance
    return 0.5 * np.mean((A - AB) ** 2, axis=0) / ; # np.var(np.r_[A, B], axis=0) (**Commenting out the denominator)**

def second_order(A, ABj, ABk, BAj, B):
    # Second order estimator following Saltelli 2002
    Vjk = np.mean(BAj * ABk - A * B, axis=0) / ; # np.var(np.r_[A, B], axis=0) (**Commenting out the denominator**)
    Sj = first_order(A, ABj, B)
    Sk = first_order(A, ABk, B)

    return Vjk - Sj - Sk

**Comment by tupui** [comment]
Hi @ChitraDangwal, yes if you just want the respective variances you just need to not divide by the total variance. Depending on how you are calling the functions, you could simply multiply the output with the total variance that you can calculate manually (or you might know its theoretical value).

**Comment by ConnectedSystems** [comment]
Closing this issue as your question has been answered.

Thanks for using SALib @ChitraDangwal
