### ISSUE TITLE
Deployment workflow fails

### ISSUE THREAD

**Issue by ConnectedSystems** [SALib/SALib#535]
https://github.com/SALib/SALib/actions/runs/3118380987/jobs/5057633000

pinging @tupui 

I will look into it if no one else beats me to it.

**Comment by tupui** [comment]
I suppose this is just because we are missing the PyPi token in the GitHub secrets (need to create a unique token in PyPi for the project and register it in GitHub as `PYPI_TOKEN`). I don't have access here so cannot help.

**Comment by ConnectedSystems** [comment]
Thanks for the hint!

I tried it late at night so didn't want to dig into it at the time. I've set things up now so am closing.

**Comment by tupui** [comment]
Pleasure 😃 

Seems like it works fine now. Let me know if you need help with anything else.
