### ISSUE TITLE
Question to post: How to sample discrete scenarios?

### ISSUE THREAD

**Issue by mishagrol** [SALib/SALib#547]
Hello! 👋

In this [post](https://waterprogramming.wordpress.com/2014/02/11/extensions-of-salib-for-more-complex-sensitivity-analyses/) author describes sampling for discrete scenarios and share link to research,

> This approach was recently used by Matt Perry to [analyze the impact of climate change scenarios on forest growth](http://blog.perrygeo.net/2014/01/19/sensitivity-analysis/).

However this link is not active now (http://blog.perrygeo.net/2014/01/19/sensitivity-analysis/), 

May someone have access to this blog/paper? 

I am interested in conducting experiments to analyze the sensitivity of environmental models in relation to various climatic scenarios.

Thank you!💜

**Comment by ConnectedSystems** [comment]
Here you go: https://www.perrygeo.com/sensitivity-analysis-in-python.html

Seems perrygeo has moved his blog to a new domain.

**Comment by mishagrol** [comment]
thank you, @ConnectedSystems !
