### ISSUE TITLE
Extra methods to be included in this package in the future

### ISSUE THREAD

**Issue by JoerivanEngelen** [SALib/SALib#55]
Hello everyone,

I have used this package with great pleasure so far. In my internship I am going to implement the Morris method on a complex model, but while reading the scientific literature I found some methods that, in my opinion, would make a nice addition to this package. I am not sure if this is the right place to post this; so if I am doing this incorrectly, sorry in advance. I am not a very skilled coder, therefore I mention these methods here. I hope my lazy attitude does not bother you! ;-) 

--Radial Sampling--
This is nothing else than an iterated One Factor At A Time approach. Starting from a random point in the hyperspace, one step in turn is taken for each factor. This procedure is iterated. So: instead of using trajectories like Morris' method, "stars" are created in the input hyperspace. Campolongo et al. (2011) used this method with greater success than Morris' method and the same amount of runs.
http://www.sciencedirect.com/science/article/pii/S0010465510005321

--Morris method with sampling strategy of Ruano et al. (2012)--
As the "Brute Force Approach" of Campolongo et al. (2007) introduces an combinatorial optimization problem, a sampling strategy which looks at combinations locally instead of globally might be a nice addition to the Morris function in this package. This makes it doable to create more optimized trajectories in exchange for a better coverage of the input space. Still, this is better than purely random sampling. Ruano et al. (2012) present such an approach. I myself find it hard to understand the thoughts behind each step in their algorithm, but it is presented in such a way that it could be implemented in code.
http://www.sciencedirect.com/science/article/pii/S1364815212000904
UPDATE: I have made an implementation of this method for SALib and pulled it as a request (or whatever the correct grammar for a "pull request" is)

--Latin Hypercube Sampling (LHS) of starting points in Morris method--
Using LHS for the starting points was originally proposed by Morris to enhance the spread in the output space. This is also an alternative to the "brute force approach".

I hope these methods could be added to the "Methods to consider adding" list! If you cannot access the papers, send me a message.

**Comment by jdherman** [comment]
Thanks, I agree these would be an improvement. I won't have much time to work on them in the near future, but I'll leave the issue open in case anyone is up to the task.

One thing to note, @willu47 has already implemented a combinatorial optimization approach to create Morris trajectories. This doesn't cover the methods you mentioned, but is better than the naive sampling that I wrote originally.

Thanks again for using the library!

**Comment by willu47** [comment]
Hi there.  Thanks for your feedback.  It's great to hear that you've been using the library.  I hadn't yet come across a few of those papers, so it's good to see that others have been working on improvements to the Morris method (I'll have to get my paper out soon or someone else will beat me to it!).

As @jdherman mentioned, I have indeed added a combinatorial optimisation approach to the Morris method in the SALib package.  However, you need to install gurobi (+ the python api for gurobi), which is a commercial piece of software and unless you are lucky enough to have an academic license (like me!), rather expensive.  Sorry about that :(.  I'd like to amend this at some point in the future to increase access, as I used whatever I had to hand at the moment.  The combinatorial optimisation approach is very computationally demanding, and only worth doing if you have a very computationally expensive model to run.  If you can, just run as many runs as possible and the law of large numbers should come to your rescue.

The radial approach has been on my to-do list, but is likely to stay there for a while.  Why don't you have a go?  Put some code together, write some tests, submit a pull request and contribute to the library!  It's a great way to improve your coding.  I'd be excited to see the codebase grow and improve and would be happy to help support this (i.e. give you comments on your code via the pull-request).  If you're new to github and version control, [here is](https://guides.github.com/introduction/flow/index.html) a good guide on how to contribute to a project. 

Will

**Comment by JoerivanEngelen** [comment]
I have added a pull request for adding the local optimization by Ruano et al. 2012 :)

**Comment by dojeda** [comment]
I'm not sure if the radial sampling method is exactly the same or similar to Pujol's simplex sampling for Morris (http://www.sciencedirect.com/science/article/pii/S0951832008002135). I was reading this conversation and I remembered that the R sensitivity package lets you choose between a OAT or the simplex design (more expensive).

By the way, I don't know if you guys are familiar with the `sensitivity` R package; there are a lot of algorithms and open-source implementations there that can be a great inspiration for SALib.

**Comment by JoerivanEngelen** [comment]
I am both aware of the sensitivity R package (never have used it though) and Pujol's article, which I have read. If I remember his article correctly, there is an important difference with the radial sampling method, as with the simplex method, you do not discretize the input hyperspace (or discretize it differently). It is some months ago that I have read that paper though.

**Comment by willu47** [comment]
It would be interesting to compare all of these methods on some real-life applications and test-problems.  Could be a nice open-source and collaborative paper showcasing implementations of these methods in SALib?

**Comment by jdherman** [comment]
@dojeda, yes I've used the R package quite a bit a few years ago, and used it to translate the initial versions of Morris OAT and FAST. They have a lot of good methods in there.

It does sound like the radial/simplex sampling share some similar ideas. If we look into implementing these, we can figure out which one to cite (or both).

@willu47 it would be great to publish something from this. Whether a method comparison or just a software announcement. How cool would it be to have an author list who have only met on Github :)

**Comment by JoerivanEngelen** [comment]
@willu47 That sounds like a cool idea! 

Off topic: @jdherman I see we share an interest in hydrology!

**Comment by jdherman** [comment]
Yes indeed! Hydrology was how I got into sensitivity analysis in the first place. I'm working more on the water management side now, but still with some overlap in hydrology.

I really like the idea of writing a paper together. I'll start a new issue!

**Comment by dojeda** [comment]
How about nth-order (n>2) indices for Sobol ?

**Comment by jdherman** [comment]
@dojeda would that require a different sampling scheme, or are there estimators for these from the samples we already have?

**Comment by dojeda** [comment]
The way I have been doing my Sobol analyses with n-th (n>2) indices is to use a random sample (following the input's probability function, of course), with a huge number of evaluations (~1e5--1e6); aka a Monte Carlo approach. I don't think there is such sampler in SALib.sample, but it seems easy to implement.

**Comment by jdherman** [comment]
Interesting. I didn't know there was a way to calculate nth order indices from a regular MC sample. What does the estimator look like for this?

SALib.sample contains latin hypercube sampling, which is used by some of the analysis methods.

**Comment by dojeda** [comment]
Well, I'm not familiar with the exact details, but the `sobol` function of R's sensitivity package (https://cran.r-project.org/web/packages/sensitivity/index.html) seems to calculate these by multiplying by +1 or -1 each variable, depending on whether said variable participates in the nth-order effect or not, and then calculating the variance estimators "as usual" (again, I'm not familiar with the exact mathematical formulation of these estimators).

I can't find the (old) publication where more details may be covered:
I. M. Sobol, 1993, Sensitivity analysis for non-linear mathematical model, Math. Modelling Comput. Exp., 1, 407–414.

**Comment by jdherman** [comment]
Hm it looks like that's the original ANOVA, before Saltelli et al. came up with the faster method for first-second-total orders.

Could be good to add this, even though it's probably a bit slower than the Saltelli implementation. Anyone reading this is welcome to take a crack at translating the R version :)

**Comment by dojeda** [comment]
I can take a shot at that, but not before mid-december, since I'm changing jobs at the moment and things are a bit hectic.

**Comment by jdherman** [comment]
Great! No rush whatsoever. Anytime you can look into it would be great.

**Comment by JoerivanEngelen** [comment]
!@#!@ Somebody claimed he made a better method for optimizing the trajectories, guess there is some additional implementation work for me to do... http://plaza.ufl.edu/khareyogesh1/OSU_Poster.pdf

**Comment by jdherman** [comment]
Haha. This happens. No pressure to implement the new version, unless you want to :)  Just send them a quick email first to make sure they would be ok with others translating their matlab code.

**Comment by jdherman** [comment]
Going to close this -- we have the planned new methods broken out in separate issues. Thanks everyone for the work on the updated Morris sampling methods.
