### ISSUE TITLE
Sensitivity analysis of ODE system?

### ISSUE THREAD

**Issue by lhdp0110** [SALib/SALib#554]
Is it possible to use SALib to do a global sensitivity analysis of the parameters of a system of ordinary differential equations?
If so, could you please refer me to an example of how it would be implemented?
If not, is there any other package in Python that can do this?
Thank you in advance

**Comment by tupui** [comment]
Hi @lhdp0110, thank you for reporting.

I am not sure exactly what you want to do here but, you can apply sensitivity analysis to anything that can be written in the form `f(x1, x2, ..., xn) = Y`. The methods are non-intrusive so it does not really matter what is `f`.

Trying to make an analogy here, if you could frame your problem as an optimization problem, then you should be able to do a sensitivity analysis.

If you have a minimal example to show what you are trying to do, maybe we could give you a more complete answer.

**Comment by lhdp0110** [comment]
Thank you! I did figure out how to run the analysis below:

``from scipy import integrate as sp
from scipy.integrate import solve_ivp
from scipy.integrate import odeint
import numpy as np
from numpy import exp
import matplotlib.pyplot as plt
import SALib
from SALib.sample import saltelli
from SALib.analyze import sobol

# degradation/inactivation rates
d_A = 0.5      # 0.02 (delta_A) per Ellner Fig.3,4 /// 0.05 per Table S3
d_G = 0.02       # 0.02 (delta_P) per Ellner Fig.4
d_P = 0.01       # 0.01 (delta_P) per Ellner Table S3
d_bP = 0.02      # 0.02 (delta_P*) per Ellner Table S3
d_bI = 0.01      # 0.01 (rho_I*) per Ellner Table S3
d_R = 0.01       # 0.01 (delta_R) per Ellner Table S3
d_N = 0.01       # 0.01 (delta_N) per Ellner Table S3
d_NG1 = 0.05    # 0.05 (delta_H) per Ellner Table S3
d_NG2 = 0.05     # 0.05 (delta_H) per Ellner Table S3

# supply rates
s_A = d_A       # (Q_A = delta_A) per Ellner p.15
s_P = d_P       # (Q_P = delta_P) per Ellner p.15
s_B = d_R       # (Q_R = delta_R) per Ellner p.15
s_NG1 = d_NG1     # (Q_H = delta_H) per Ellner p.15
s_NG2 = d_NG1    # (Q_H = delta_H) per Ellner p.15

# reaction/binding rates
c_A = 0.8     # (default = 0.8) this parameter adjusts how high A peaks
c_P = 0.5       # (new default = 0.5)
c_I = 1       # (default = 0.5)
c_B = 4        # (default = 4) can be higher than 4 but not lower than 2
c_N = 3     # (default = 3) decreasing to 1 lowers peak of A and induces small lift around t=48, increasing beyond 3 doesn't change much
c_bN = 2.5      # (default = 0.5) variations alter shape and peak of A, but not by much
c_NG1 = 0.1
c_NG2 = 0.2

# carrying capacity
K_I = 1

# flow rate into nucleus
f_P =  9       # (default = 10) increasing to 20 or higher doesn't change much, decreasing to 1 flattens A and incudes small lift at t=48

# strength of feedback effect
phi_NG1 = 0.07
phi_NG2 = 0.32

# proliferation rate
p_G = 2.5       # (new default = 2.8) 2.5, per Frank. alters G more than A

# mortality rate
m_G = 2            # (default = 2) max=5, per Frank. alters G more than A


# definition of the system of ODEs
def model(y, t, d_A, d_N, c_A, c_N, c_bN):
    A = y[0]
    G = y[1]
    P = y[2]
    bP = y[3]
    bI = y[4]
    RB = y[5]
    RP = y[6]
    RN = y[7]
    bRN = y[8]
    NG1 = y[9]
    NG2 = y[10]
    #val_base = y[11]
    #val_max = y[12]
   # rate_induc = y[13]
   # rate_decay = y[14]
    
   # val_base = A[0]
    #val_max = max(A)
    #rate_induc = (A[6]-A[0])/6
    #rate_decay = (A[12]-A[6]/6)
    
    dA_dt = s_A + c_A * bRN - d_A * A                       # AMPs transcribed by Relish
    dG_dt = p_G * G - m_G * G * A - d_G * G                 # pathogen present outside the cell
    
    dP_dt = s_P - 2 * c_P * P**2 * G * exp(-phi_NG1 * NG1) - d_P * P              # unbound PGRP-LC monomer
    dbP_dt = c_P * P**2 * G * exp(-phi_NG1 * NG1) - d_bP * bP                     # PGRP-LC dimer bound to pathogen
   
    dbI_dt = c_I * (1-bI/K_I) * bP * exp(-phi_NG2 * NG2) - d_bI * bI                  # IMD recruited by activated PGRP-LC
   
    dRB_dt = s_B - c_B * RB * bI - d_R * RB                 # Relish B in cytoplasm
    dRP_dt = c_B * RB * bI - f_P * RP - d_R * RP            # Relish P in cytoplasm
   
    dRN_dt = f_P * RP - c_N * RN + c_bN * bRN - d_N * RN    # free nuclear Relish
    dbRN_dt = c_N * RN - c_bN * bRN            # nuclear Relish bound to target gene
   
    dNG1_dt = s_NG1 + c_NG1 * bRN - d_NG1 * NG1             # neg reg at level 1 (PGRP-SC2/LB, pathogen binding)
    dNG2_dt = s_NG2 + c_NG2 * bRN - d_NG2 *NG2              # neg reg at level 2 (PIRK, IMD recruitment)

    return np.array([dA_dt, dG_dt, dP_dt, dbP_dt, dbI_dt, dRB_dt, dRP_dt, dRN_dt, dbRN_dt, dNG1_dt, dNG2_dt])

t_span = np.array([0, 50])
t = np.linspace(t_span[0], t_span[1], 101)

# Initial conditions of ODE system
y0 = np.array([1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1])

#new addition here
y = sp.odeint(model, y0, t, args=(d_A,d_N,c_A,c_N,c_bN))

problem = {
  'num_vars': 5, 
  'names': ['d_A', 'd_N','c_A','c_N','c_bN'],
  'bounds': [[0.25, 0.5],
             [0.01, 1],
             [0.5, 2],
             [1, 100],
             [0.1, 10]]
}

# Generate samples
param_values = saltelli.sample(problem, 50)

#new version here
Y = np.zeros([len(param_values),11])

for i in range(len(param_values)):
    Y[i][:] = sp.odeint(model,y0,t,args=(param_values[i][0],param_values[i][1],param_values[i][2],param_values[i][3],param_values[i][4]))[len(y)-1]
    
    
print('\n\n====AMP Sobol output====\n\n')
Si_AMP = sobol.analyze(problem, Y[:,0], print_to_console=True)

Si_AMP.plot()``

However, I am having a hard time reading the plots and interpreting the results as far as the t variable. For what value of t is the analysis being ran?

My ultimate goal is to look at the influence of input parameters onto the value of A = y[0] at time points t=0, t=6, t=48, and on the time ranges t=0 to t=6, and t=6 to t=36. 
Is this feasible? is there even such a thing as a global sensitivity analysis at specific time points or over time ranges?

**Comment by tupui** [comment]
AFAIK SALib does not handle yet vector output, which is what you seem to have (Y of shape (n_samples, n_output)). Even if, to simplify I suggest to just run `n_output` analysis (make a `for` loop.)

Hence this should give you the answer, for time `t=x` the Sobol' indices are the following for these 5 parameters `['d_A', 'd_N','c_A','c_N','c_bN']`.

Once you have all the analysis, you could make some plot of indices along the time. You can also compute some aggregated indices (see Marrel and Iooss.)

**Comment by lhdp0110** [comment]
Ahh, I had written this using a similar example I found online, it did seem to run but the plots looked weird.

Sorry I'm a beginner at Python so I'm not completely clear on what you mean about Y -- should it not be an array?
It does not throw an error as it is. 
How would I go about making these plots of indices along the time, or aggregated indices?

I guess I'm trying to do something similar to the "Another Example" plot at the very bottom of this tutorial: https://salib.readthedocs.io/en/latest/basics.html#run-model

But I'm confused by some of the syntax. 
For example, what is the T IN ```# analyse
sobol_indices = [sobol.analyze(problem, Y) for Y in y.T]
```
and the s[S1] in ``S1s = np.array([s['S1'] for s in sobol_indices])
```

**Comment by ConnectedSystems** [comment]
Hi Louise,

If you use the `ProblemSpec` interface, it should handle the multiple outputs for you (where these are the different results over time). The links below will be helpful - you could probably adjust the example in the last to do what you want.

To answer your question above though, the `.T` is numpy shorthand for array transpose. You want to loop over each column in `Y` but if you loop over it directly numpy assumes you want to loop over rows, hence the transpose.

The 'S1' refers to First Order sensitivity - the contribution of that specific factor toward variance in the outputs. For understand that further, I refer you to the relevant papers.

FYI if you're working in the REPL or in a Jupyter Notebook you can view the documentation by running a function with a question mark:

```python
# These should display the documentation for the sobol analysis function
sobol.analyze?
?sobol.analyze
```

We're expanding the docs at the moment so let us know if anything is too cryptic and I'll try to make it clearer.


Links:

https://salib.readthedocs.io/en/latest/basics_with_interface.html
https://github.com/SALib/SALib/blob/main/examples/Problem/problem_spec.py
https://github.com/SALib/SALib/pull/553

**Comment by ConnectedSystems** [comment]
Just to add in case useful, the specific section below has some minor detail on interpreting S1 and ST. 

https://salib.readthedocs.io/en/latest/basics_with_interface.html#perform-analysis

**Comment by ConnectedSystems** [comment]
@lhdp0110 assuming you've managed to resolve your problem so I am closing this issue. Feel free to come back with more questions if this is not the case.

**Comment by lhdp0110** [comment]
Thank you for your help and my apologies for not responding sooner -- I have not yet figured this out but had to take a break from this project for a while. 
I am trying to run the script from issue #553 but getting the following error: 
''AttributeError: 'ProblemSpec' object has no attribute 'analyze_rsa'''
Do I need to update the package or import something that I'm not seeing? It looks like I have SALib version 1.4.6.1

**Comment by ConnectedSystems** [comment]
Hi @lhdp0110 

The Regional Sensitivity Analysis method you're after will be in the next release which I hope to finalise soon. "Soon" can be weeks though.

You can install the latest development version directly from this repository which will have RSA though.

`pip install SALib@git+https://github.com/SALib/SALib`

**Comment by lhdp0110** [comment]
I understand -- so is the RSA method necessary when using Problem_Spec to perform time-dependent sensitivity analysis (my objective is to get something like the graph at the very bottom of this page, showing sensitivity of each parameter onto the output at each time point x: https://salib.readthedocs.io/en/latest/user_guide/basics.html#another-example)

Also, I am using Anaconda, will it be okay to install the development version using ```conda develop <path>``` ?

**Comment by ConnectedSystems** [comment]
You can perform temporal (or time-varying) sensitivity analysis with any SA method really. You simply apply the method to each time step.

RSA is intended to give you a "snapshot" across factor or output space but I suppose nothing is stopping you from making the X "time".

> Also, I am using Anaconda, will it be okay to install the development version using conda develop <path> ?

That should be fine. I think it just calls `pip install -e <path>` underneath anyway.

**Comment by lhdp0110** [comment]
Thank you for clarifying! I had misunderstood thinking that those examples you recommended would be of particular interest for me due to the RSA method, rather than simply showing how to use the ``ProblemSpec`` interface. 
I will try and adapt those to my project -- if expanding the docs is still in the cards, an ODE example of ProblemSpec implementation would definitely be useful!

**Comment by ConnectedSystems** [comment]
Sorry for the delayed response - things have been busy of late.

> Can the ProblemSpec interface be merged with the example at the bottom of https://salib.readthedocs.io/en/latest/user_guide/basics.html#another-example ?

In essence, yes. Though with the ProblemSpec it's a little tricky. I've done it myself, but it's not the easiest thing to do.

As I said above, temporal SA is at its core is applying the sensitivity analysis method for each time step. There's nuances to this of course but that's what it is. If you have some code to show I could probably help you here, or at least show you how to do it with the underlying SALib methods directly.

**Comment by lhdp0110** [comment]
That would be super helpful! No need to use ProblemSpec then if it's not necessary. Below is the code for the function I want to analyze, there are six parameters of interest for the sensitivity analysis and I'd like it to be done at time steps 0, 6, 24, and 48

``
from scipy import integrate as sp
import numpy as np
import SALib
from SALib.sample import saltelli
from SALib.analyze import sobol
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# defining all parameters of the ODE system
init_vals = 1
tot_I = init_vals

d_A = 0.4  
d_G = 0.3
d_P = 0.43 
d_bP = 0.93   
d_bI = 1.1  
d_R = 0.2  
d_N = 0.63

s_A = 0.27   
s_P = 0.53   
s_B = 0.35     

c_A = 9.55 
c_P = 4.94
c_I = 1.1 
c_B = 1.69
c_N = 14.61
c_bN = 11.86

f_P = 30  
p_G = 2.04
m_G = 1.93   

#defining the ODE system
def function(y,t,d_A,s_A,c_A,c_N,c_bN,f_P):
    A,G,P,bP,bI,RB,RP,RN,bRN=y
  
    dA = s_A + c_A * bRN - d_A * A              
    dG = p_G * G - m_G * G * A - d_G * G                
    
    dP = s_P - 2 * c_P * P**2 * G  - d_P * P            
    dbP = c_P * P**2 * G  - d_bP * bP                     
   
    dbI = c_I * (tot_I-bI) * bP - d_bI * bI             
   
    dRB = s_B - c_B * RB * bI - d_R * RB                 
    dRP = c_B * RB * bI - f_P * RP - d_R * RP           
   
    dRN = f_P * RP - c_N * RN + c_bN * bRN - d_N * RN   
    dbRN = c_N * RN - c_bN * bRN     
    
    return dA, dG, dP, dbP, dbI, dRB, dRP, dRN, dbRN;

times = np.linspace(0, 50, 100)

# Initial conditions of ODE system
y0 = [init_vals, init_vals, init_vals, 0, 0, init_vals, 0, 0, 0]

# lower/upper bounds below are estimated, can be modified if needed
problem = {
  'num_vars': 6, #a's, b's and initial condition
  'names': ['d_A', 's_A','c_A','c_N','c_bN','f_P'],
  'bounds':  np.column_stack((np.array([0.2, 0.1, 1, 1, 1, 1]),np.array([1, 0.4, 15, 20, 15, 20])))
}
``

**Comment by lhdp0110** [comment]
I just wanted to check in again, have you had a chance to work on incorporating a temporal analysis on the ODE system above?

**Comment by ConnectedSystems** [comment]
Ah sorry, this dropped off my radar. I will try to make time for this tonight.

**Comment by ConnectedSystems** [comment]
Hello @lhdp0110 

See attachment here. You'll note I left quite a bit for you to do yourself but the basics are there and seem to work.
All the best with this.

[tsa_salib_554.zip](https://github.com/SALib/SALib/files/12618913/tsa_salib_554.zip)

**Comment by lhdp0110** [comment]
Thank you so much, I really appreciate your help with this!

**Comment by ConnectedSystems** [comment]
I'm going to close this issue but feel free to re-open if you have any more questions.
