### ISSUE TITLE
Details in "Wrapping an Existing Model" appear incorrect

### ISSUE THREAD

**Issue by morrowcj** [SALib/SALib#560]
# Problem
In the [Wrapping an Existing Model](https://salib.readthedocs.io/en/latest/user_guide/wrappers.html) documentation, it is stated that "[The SALib *ProblemSpec* Interface] automatically applies the model for each individual sample set in a *for* loop (at the cost of computational efficiency)". However, this does not appear to be the case. 

From the "problem.py" file:
```python
def evaluate(self, func, *args, **kwargs):
    if "nprocs" in kwargs:
        nprocs = kwargs.pop("nprocs")
        return self.evaluate_parallel(func, *args, nprocs=nprocs, **kwargs)

    self.results = func(self._samples, *args, **kwargs)
    return self
```

It appears, from this method, that `func` is simply called with the full matrix of samples as the first argument. The parallel version breaks the matrix into chunks (sub-matrices) and passes those chunks as the first argument.

# Suggestion
I think you might want to edit the document to better represent the true functionality of `ProblemSpec.evaluate()`, unless my assessment is incorrect. 

Perhaps you could clarify that if the user wants to utilize the parallel functionality for a model that is "not [easily] expressed in a vectorizable form", the wrapper function should include a for loop. Something like:

```python
def linear(a: float, b: float, x: float):
    return a + b * x

def wrapper(X: numpy.array, func=linear):
    results = numpy.empty(X.shape[0])
    for i in range(X.shape[0]):
        a, b, x = X[i, :]
        results[i] = func(a, b, x)
   return results
```

**Comment by ConnectedSystems** [comment]
Hi @morrowcj 

Yes you're right! Apologies, seems I got my wires crossed here.

I had written something previously to handle this but the computational overhead was too much in cases where the model was able to be expressed in a vectorized form so it was ultimately abandoned. What I was actually thinking of was that the analysis would be parallelized across multiple outputs.

I will correct the documentation as soon as I can.

Thank you for picking up on this oversight!
