### ISSUE TITLE
Does SALib support Global Sensitivity Analysis?

### ISSUE THREAD

**Issue by jacktang** [SALib/SALib#569]
Hello there!

Does SALib support Global Sensitivity Analysis where the output is a high dimensional vector?

**Comment by jacktang** [comment]
Ok, i got it

**Comment by sahin-abdullah** [comment]
I did not get why this is issue is closed but I can answer your question. Global Sensitivity Analysis means measuring sensitivity indices among parameters' input range. Let's take ishigami function as an example. -pi and pi is the range for the **input** matrix X. What makes sensitivity analysis global for this example is that doing an analysis for all points between the given range. There are methods that account for sensitivity indices at certain points. These are called local sensitivity analysis. There are also other methods that provides hybrid solutions such as VARS method. 

Given this piece of information, sensitivity analysis does not become global when output is high dimensional vector. Usually high dimensional output vector represent time component. If so, you have couple of options.

Option 1: You can run sensitivity analysis for each time step
Option 2: You can use aggregated function over the time step such as RMSE, FLASHINESS INDEX etc.

I am reopening this issue in case you might have further question.

**Comment by tupui** [comment]
Hi everyone. I would still keep this issue closed because we are already tracking the idea elsewhere, e.g. in #525

@jacktang funny that you are mentioning CFD, I did my PhD in SA and PhD 😃 I am going to do a shameless plug with what I did and how I addressed the temporal/spatial/vector space: https://link.springer.com/article/10.1007/s00477-017-1470-4 and http://dx.doi.org/10.1002/fld.4504

**Comment by ConnectedSystems** [comment]
Yeah, thanks @tupui for raising temporal SA - apologies @jacktang for not responding sooner. 

I need to find some time to finish #525.

**Comment by jacktang** [comment]
Hello @tupui. Thanks you so much for your paper! It is valuable to me, I am working on the pod-based surrogates topic :), I'd like to read it carefully in next days.

**Comment by tupui** [comment]
As said above, I am going to close this one in favour of #525 This is in an effort to keep the tracker manageable.
