### ISSUE TITLE
How to handle multiclass classification problem in sobol.analyze function?

### ISSUE THREAD

**Issue by usnishmukherjee** [SALib/SALib#576]
Hi,
I was trying to implement sensitivity analysis using SALib library. Here in SALib, the anlyze function of sobol, expects Y , the output of model, as an one dimensional array. But, predict_proba method of any classifier gives a N*(number of class) dimensional array. Is it correct to pass array of each class separately to the sobol.analyze function and calculate Si values?
Here is the code snippet that I have tried.
 for class_label in np.unique(Y):
            y_pred_poba = model.predict_proba(param_values)[:, class_label]
            Si = sobol.analyze(problem, y_pred_poba)
            S += Si['S1']
S/= np.unique(Y)

Where Y is the target column.
I am getting some negative values in First order Sensitivity Index. Thats why I am curious about my implementation.

**Comment by tupui** [comment]
Hi @usnishmukherjee, thank you for reporting!

I am tempted to say that this is a similar discussion as we had on #525

Making a loop on indices of Sobol' is ok but keep in mind that each analysis is totally independent from each other.

**Comment by tupui** [comment]
What do you mean by cumulative? If you have an output with 3 values, you do 3 analysis. These analysis are independent.

There are some work to combine them, but this is not implemented (yet) in SALib.

Have a look at this: https://arxiv.org/abs/0911.1189v4

**Comment by usnishmukherjee** [comment]
Suppose, I am performing Sensitivity analysis on a dataset, which have categorical features in target column such as 'True', 'False'. now model.predict_proba(param_values) will generate a N*2 vector. Corresponding to each sample there will be probability of True and False like [0.3, 0.7]  where 0.3 corresponds to True and 0.7 is for False. There will be N such vector for N sample. 
I can not pass the N*2 output vector to analyze function.
For, that reason, I am trying to calculate the Si values for each class separately and adding the Si values which is making a cumulative Si values.
Finally I am dividing the Si values by total number of classes, here by 2.
```
for class_label in np.unique(Y):
    y_pred_poba = model.predict_proba(param_values)[:, class_label]
    Si = sobol.analyze(problem, y_pred_poba)
    S += Si['S1']
S/= np.unique(Y)
```
Hope I am able to describe the situation.

**Comment by tupui** [comment]
Yes you are trying to do an aggregated Sobol' indices, have a look at this short explanation in OpenTURNS' documentation: https://openturns.github.io/openturns/latest/theory/reliability_sensitivity/sensitivity_sobol.html#aggregated-sobol-indices
