### ISSUE TITLE
Discrete input random variables

### ISSUE THREAD

**Issue by jaimeambrus** [SALib/SALib#577]
Hi,

I am new to using SALib and currently, I have a model that contains continuous and discrete input variables. I read the closed issues and understood the workaround of rounding the floats to integers but I also understood that this could cause some bias in the sampling. My current model is expensive to evaluate, so having native discrete input variables distributions would be better than increasing the sample size. 

I looked at the code and the point where different distributions are used is at the `_nonuniform_scale_samples` method. As the other methods seem to be distribution agnostic, I guess this could be a relatively small addition? Please correct me if this is a too simplistic view, and of course, I would be more than happy to submit a PR.  What are your thoughts on this?

**Comment by tupui** [comment]
Hi @jaimeambrus thank you for reporting.

So it's easy to sample a single parameter following a discrete distribution. But joint distributions mixing continuous and integer variables needs to be handled. It's not optimal but it's actually ok to round a float to an integer if you have a smaller working on floats. We do that in SciPy and Art Owen could confirm me that it's fine.

All that to say, I think here we can rewrite the function you mentioned with a combination of `scipy.stats.qmc.scale`, the integer handling we have and for the distribution part use `scipy.stats.sampling`. All the features we want are there and we don't need more customizations.

To your expensive problem, I would suggest that you build a surrogate model and do your analysis on it instead. That would save you a lot of computational cost.

**Comment by jaimeambrus** [comment]
Hi @tupui thanks for the feedback!

I'll try the rounding approach then. 

Regarding the surrogate, it is in my plans, indeed it would be something worth investing some time in. 

Thanks again!
