### ISSUE TITLE
SA for model with integer variable

### ISSUE THREAD

**Issue by AmosJoseph** [SALib/SALib#581]
Hi, thanks for your nice SALib!

I'm writing to ask if input contains continuous variable and integer variable (1, 2, 3), then how to define the bounds?

Best!

**Comment by ConnectedSystems** [comment]
Hi @AmosJoseph 

We don't support categorical/integer variables out of the box just yet, but for these situations I use what I call the "flooring trick".

In essence, you:

1. create a sample using the desired range, adding one to the upper bound (in your case, [1, 4])
2. post-process the sample by `floor`-ing the value, such that 1.1 becomes 1, 3.99 becomes 3, etc

**Comment by ConnectedSystems** [comment]
Closing this assuming you have resolved your issue, but feel free to ask more questions if you need.
