### ISSUE TITLE
Question : Sobol indices and groups

### ISSUE THREAD

**Issue by ghost** [SALib/SALib#583]
Hi ! 

I have come to you because I would like to implement a strategy for calculating Sobol indices for the following problem: 

I have a model with 16 inputs and 1 output. The 16 inputs are split into two :

-> The first 11 inputs are managed independently.
-> The last 5 inputs form a group (called VG_2): a 5D random vector.

The 11 variables are independent of each other, and also of the VG_2 group. Whereas the 5 variables making up the group are not independent of each other. They represent a particular system which only makes sense if they are managed together. 

It's easy for me to generate instances of these 16 variables.

I want to obtain a ranking of the 11 variables + VG_2 (1st order, 2nd order and total indices).

This model comes from a GP (Gaussian Process).

It seems that SALib can take groups into account with Sobol. 

However, I can't see how to properly declare the problem for this context. Can you help me?

Normally, I haven't read about a similar problem on the github, but if I'm wrong, sorry for the redundancy!

Thank you very much!

**Comment by ConnectedSystems** [comment]
Hello, sorry for the late response!

It sounds like you want 12 groups (11 unique ones and the last 5 factors in the 12th group) :

```python
sp = ProblemSpec({
  'names': [f"x{i}" for i in range(1,17)],  # Name of each parameter (remember, Python is end exclusive so we use 17, not 16)
  'groups': [f"x{i}" for i in range(1,12)] + ["VG_2", "VG_2", "VG_2", "VG_2", "VG_2"],
  'bounds': [[-np.pi, np.pi]]*16,  # bounds of each parameter
  'outputs': [f"Y{i}" for i in range(1,17)]  # name of outputs in expected order
})

sp.sample_sobol(2**6)
```
