### ISSUE TITLE
inputs without bounds

### ISSUE THREAD

**Issue by woyaobiyeya** [SALib/SALib#585]
Hi ,

thanks a lot for the excellent project.

I am total new to this SA area and currently writing my thesis. I have my own model .After the experiments I would like to use the SALib to analysis my project's inputs' influences on my output. Unfortunately my inputs is a set of numbers like e.g. [x1 x2 x3] = [0.05 0.02 0.3], corresponding y = [500 600 900]. All x belong to Gaussian distribution.  Could you please let me if there is any chance that I can also adapt your project to my work?

I appreciate your time and work. I wish you great day:)

**Comment by tupui** [comment]
Hi @woyaobiyeya, thank you for reporting 😃 

Yes you can use SALib to perform an analysis on your problem. Have a look at this part of our documentation to see how to define Gaussian (Normal) distributions for your input space: https://salib.readthedocs.io/en/latest/user_guide/advanced.html#generating-alternate-distributions

**Comment by woyaobiyeya** [comment]
hi :)

thank you so much for the quick reply!  Your answer gives me hope because I am stuck in understanding the papers of sensitivity analysis. 

 There is my understanding based on your elaboration:  Even though the output y generated by single input (x1 x2 x3), I still can use SALib to analyze the relationship between inputs(x) and outputs(y). As long as I know the exact distributions of x1 x2 x3. 

Could you please let me know if I understood correctly?

**Comment by tupui** [comment]
I am not sure I understand your question correctly.

What you need is to have a way to generate outputs based on varying inputs, i.e. `y = some_func(x1, x2, x3)`. If you have that, with SALib you can create a proper sample and evaluate your function at each point. Then you will be able to use things like Sobol' indices to draw conclusions in terms of Sensitivity Analysis.

I suggest you follow our intro in the documentation and try things out with small function to get a feeling of how this works.
