### ISSUE TITLE
Can SAlib be used with mesa.batch_run?

### ISSUE THREAD

**Issue by edday1** [SALib/SALib#586]
Can anyone give me some pointers how to use SALib with `mesa.batch_run`?
I'm trying the following but `mesa.batch_run` won't allow a numpy array. And i don't think `Y` can be set to a df.

```
problem = {
    'num_vars': 3,
    'names': ['width', 'height', 'N'],
    'bounds': [[0, 15],
               [0, 15],
               [10, 500]]
}
param_values = saltelli.sample(problem, 1024)

results = mesa.batch_run(
    MoneyModel,
    parameters=param_values,
    iterations=5,
    max_steps=100,
    number_processes=1,
    data_collection_period=1,
    display_progress=True,
)
Y = pd.DataFrame(results)

Si = sobol.analyze(problem, Y, print_to_console=True)
```

**Comment by tupui** [comment]
Hi @edday1, thank you for reporting.

What is `mesa.batch_run`?

I don't think this is really a question for SALib. You need to figure out what are the requirements from `mesa.batch_run` are for `parameters` and then convert `param_values` accordingly. Then you need to do a similar conversion for `result`. Here `Y` should be converted to NumPy arrays.
