### ISSUE TITLE
RSA results should not be within [0,1]

### ISSUE THREAD

**Issue by WangYuNeng** [SALib/SALib#587]
Hi everyone,

In the [regional sensitivity analysis](https://salib.readthedocs.io/en/latest/api.html#regional-sensitivity-analysis) docstring. It said that 

> The $k$-sample Anderson-Darling test is used to compare distributions. Results of the analysis are normalized so that values will be $\in$ [0, 1], and indicate relative sensitivity across factor/output space.

However, the statistic of k-sample Anderson-Darling test can be a negative value and the normalization did not consider that. For example, with the example in #553 and print the results to the console. One will have

```
             a         b         x
0.00  0.390191  0.741887  1.000000
0.05  0.111961  0.380669  0.610822
0.10  0.055837  0.217616  0.455647
0.15  0.050701  0.126190  0.304971
0.20  0.041214  0.048458  0.242932
0.25  0.009518  0.064832  0.136050
0.30  0.010863  0.017865  0.102018
0.35  0.001348  0.001385  0.088539
0.40  0.000373  0.004274  0.033639
0.45  0.000401 -0.000366  0.016558
0.50 -0.000866  0.000481  0.031200
0.55  0.001065  0.000685  0.029868
0.60  0.005188  0.012643  0.054367
0.65  0.015177  0.016362  0.103988
0.70  0.018540  0.033772  0.165337
0.75  0.018166  0.076879  0.234286
0.80  0.050358  0.115849  0.318244
0.85  0.066448  0.215251  0.432288
0.90  0.099630  0.383904  0.636461
0.95  0.412526  0.741783  0.982159
```
which contains negative values.

**Comment by ConnectedSystems** [comment]
Hi @WangYuNeng thanks for reporting this.

I agree this is a bug.

Regarding the title of this issue, are you suggesting an alternate normalisation approach be adopted or that the method should not normalise values at all?

**Comment by WangYuNeng** [comment]
I think normalizing to [0,1] could be misleading if someone thinks of it as similar to the Sobol's indices where 0 means insensitive. Currently, the document already mentions that it's a relative measurement. I wonder if it would help for clarity's sake to emphasize that normalization can cause large statistics to look close to zero, i.e., even when the result is close to 0, $(X|b_i)$ and $(X|~b_i)$ can still be very different distribution.

**Comment by ConnectedSystems** [comment]
Thanks, and I agree. The intention was the give an indication of where in factor space outputs are most/least sensitive.

I was thinking of a normalisation strategy that would still give a relative measure, but in the end, I think a better approach is to replace the Anderson-Darling test with something else, like the Cramér-von Mises statistic.
