### ISSUE TITLE
Analyze dependent factors

### ISSUE THREAD

**Issue by dhetting** [SALib/SALib#588]
Are there any methods implemented in SALib that support dependency among input factors? If not, any plans to add such support? I'm mostly familiar with Morris and Sobol methods and know both of those assume independent factors.

**Comment by tupui** [comment]
Hi @dhetting, thank you for reporting.

For that you could use methods such as https://salib.readthedocs.io/en/latest/api.html#delta-moment-independent-measure or https://salib.readthedocs.io/en/latest/api.html#pawn-sensitivity-analysis

**Comment by ConnectedSystems** [comment]
You can also use HDMR, although that may be too computationally intensive. 

Just for context, PAWN is the cheapest in terms of computational cost.

**Comment by dhetting** [comment]
Great, thank you both! I'll look into those methods. PAWN looks like a good candidate for factor screening for us.
