### ISSUE TITLE
Negative First Order Sobol Indices

### ISSUE THREAD

**Issue by GijsRut** [SALib/SALib#599]
I am using the SALib (1.4.7) library to perform the Sobol Analysis. 
In my first analysis I used 4 parameters with N = 256 and second order to False, generating 1536 simulations. This gave me only a couple of negative values which could be explained by sensitivity indices close to zero. 
In my second analysis I used 7 parameters with also N=256 with second order to True, generating 4096 simulations. However, this gave me a lot of negative first order values throughout the whole simulation period varying from -0.25 to 0.2.  Second order indices give me way less negative values. 
Do I get the negative values due to lack of simulations for second order or could it be numerical errors?

Gijs

**Comment by tupui** [comment]
Hi @GijsRut, thank you for reporting! This is definitely not enough simulations for such problems. General rule of thumb is to have at least 5k simulations per parameters. Other methods might converge faster, like moment independent delta. In general, try to run as many simulations as your budget allow. Converging higher order is also harder as you need to properly sample sub projections of the input parameter space (x1/x2, x1/x3, etc.)

I will close this as it does not seem to me that there is an implementation issue. Still feel free to discuss your case here 😃
