### ISSUE TITLE
Negative Sobol Indices (Quantity of Interest = 50)

### ISSUE THREAD

**Issue by AtishnalChand** [SALib/SALib#601]
Hi SALib team,
I have performed global sensitivity analysis using SALib library on a computationally expensive model (GITM - Globol Ionosphere Thermosphere Model). In order, to reduce the computational cost, I have created a gaussian process regression based surrogate model to generate enough sample for the sobol analysis. My quality of interest is 50 reaction rates which I understand is dimensionally very large.  After performing the sobol analysis, some (~13/50) of my first order sensitivity indice values are negative. Total order indices are okay – all are positive. I even tried to increase the samples, but negative values are still there.  However, the number of negative values reduces to 6 when I increased the sample size to 851968. I can see some of the quantities are converging but the ones with the negative values are changing. I followed up with other queries and found tha
[Sensitivity_Indices.xlsx](https://github.com/SALib/SALib/files/13873648/Sensitivity_Indices.xlsx)
t if the confidence level is very close to 0 then we can ignore those quantities. Please advise if I can ignore negative sensitivity indices. I am attaching my google drive link for the excel file which has my total sensitivity indices and first order sensitivity indices for different samples. In my sobol analysis, I have turned used calc_second_order=False.

Link for the google drive excel file: [Sensitivity_Indices ](https://docs.google.com/spreadsheets/d/1NMDZHtlH3o0pxOrZngWW3ugTXXatUEEC/edit?usp=drive_link&ouid=111574842007636751416&rtpof=true&sd=true)  

[Sensitivity_Indices.xlsx](https://github.com/SALib/SALib/files/13873668/Sensitivity_Indices.xlsx)

**Comment by tupui** [comment]
Hi @AtishnalChand, thank you for reporting.

Negative Sobol' values are due to numerical noise. I had a Quick Look at you Excel and it seems that the values are very small, also confirming the numerical noise.

Since you have a GP surrogate, I would really advice that you make a convergence study and for such a large problem, I would expect a few millions samples at least (total number of samples).

I will close the issue as for now I don't see a problem with the code itself. But please feel free to keep the discussion alive. I would re-open either way if it turns out that there would be an issue with SALib itself.

**Comment by AtishnalChand** [comment]
Hi @tupui, Thanks for your response. I was able to do the convergence study and then computed the Sobol indices using 1.7M samples.  I would like to seek your advice on how I can identify the minimum threshold value for the Sobol indices since the indices are quite small (such that I can say that the top 10 parameters are important and contribute most to the uncertainty). I have uploaded my Sobol Indices, sorted in descending order. 
[Sobol_Indices_Sorted.csv](https://github.com/SALib/SALib/files/14158826/Sobol_Indices_Sorted.csv)

**Comment by tupui** [comment]
Hi @AtishnalChand, this is pretty much up to you from there. It will depend on your application and what you want to use this analysis for. From you CSV only 6 parameters contribute to at least 1% of the output variance. i.e. the rest could be fixed values that you would not notice it on this output's variance.

**Comment by AtishnalChand** [comment]
Hi @tupui, could you please advise if it is possible to extract the total variance data from the Sobol Analysis.

**Comment by tupui** [comment]
@AtishnalChand `Var f(x)` is just the variance of the sample (only matrices A and B, don't use AB and BA because they are not independent from A and B).
