### ISSUE TITLE
Correct description of Saltelli's sampling

### ISSUE THREAD

**Issue by tupui** [SALib/SALib#603]
Sergei Kucherenko shared the following with me (sorry I am laking time right now to make a PR, though I thought that could be also left as a good first PR 😅):

> I have a remark with regards to SaLib, namely in the Section on Sobol’ Sensitivity Analysis it says: “Saltelli’s scheme extends the Sobol’ sequence in a way to reduce the error rates in the resulting sensitivity index calculations”. This is incorrect. Saltelli indeed proposed a formula to reduce the number of model runs from N ( 2D +1) to N(D+1) ( it was also published at the same time in [1]) but it was I who proposed a formula to reduce the error rates in the resulting sensitivity index calculations. It was firstly published in [1] but typically we give reference [2].
> 
> [1] Mauntz W. Global sensitivity analysis of general nonlinear systems. Master’s thesis, Imperial College London, CPSE; 2002. [Supervisors: C. Pantelides and S. Kucherenko.].
> 
> [2]  Sobol’ I, Tarantola S, Gatelli D, Kucherenko S, Mauntz W. Estimating the approximation error when fixing unessential factors in global sensitivity analysis. Reliab Eng Syst Safety 2007;92:957–60
> 
> [3] [S. Kucherenko](http://arxiv.org/find/math/1/au:+Kucherenko_S/0/1/0/all/0/1), [S. Song](http://arxiv.org/find/math/1/au:+Song_S/0/1/0/all/0/1), Different numerical estimators for main effect global sensitivity indices. Reliability Engineering and System Safety, 165 (2017) 222-238
> 
> I has one trivial but important improvement: in [3] see Improved formula of Sobol’ and Myshetzskay

**Comment by ConnectedSystems** [comment]
This is awesome, please pass on my thanks
