### ISSUE TITLE
How to detect interaction effects (and calc second-order sensitivities) with LHS and Delta MIM?

### ISSUE THREAD

**Issue by TobiasKAndersen** [SALib/SALib#611]
Hi all,

We are investigating model performance and parameter sensitivities in different 1-dimensional hydrodynamic models with a Latin Hypercube Sampling and the delta moment-independent measure. One model shows high interaction (non-additive model response) as calculated by [Borgonovo et al (2017)](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2017WR020767) with S_inter = 1 - sum of all S_i (of all first-order variance-based sensitivity indices).

The question is now which parameters are responsible for the interaction effects and higher-order sensitivities. Two-order sensitivity indices could help, but is not given with Delta MIM and, currently, it is not possible to rerun with another sampling scheme (e.g. Sobol's). 

Anyone know of how to investigate interaction effects based on LHS and Delta MIM?

**Comment by tupui** [comment]
Hi @TobiasKAndersen 👋 thanks for the question.

Indeed, AFAIK, you cannot easily get higher orders with moment I depend methods. If you cannot sample more, I have mainly 2 suggestions:

1. build a meta model (I have a preference for Gaussian Process) and calculate indices of Sobol'
2. Use a visualization method which could give you hints to which variables are creating the interactions. Difficult to say without the sample but some 2D subplots might be enough or you could try new techniques like SimDec (Simulation Decomposition: simdec.io)

**Comment by TobiasKAndersen** [comment]
Hi @tupui 

Thanks for your reply and suggestions!

Yep, luckily we only have 4-5 parameters (but a lot of models), so I did create 2D subplots for some of the models, which clearly shows interactions between 2-3 parameters. However, I really want to be able to show this with a test as well. I will look into meta modelling and SimDec.

**Comment by tupui** [comment]
Great 👍 

I will close the issue then as there is not much action point on SALib itself. Still, feel free to post more comments (I am still monitoring)

**Comment by TobiasKAndersen** [comment]
Hi again @tupui 

I am looking into the meta modelling and potentially the HDRM (from SALib). However, it is not really clear to me if the 'ST' (Total contribution of a particular dimension/parameter) is indeed the total-order effect - do you know?
Also, if I were to pursue meta modelling with Gausian Proces and then calculate Sobol effects, could you recommend a way forward? Any good materials out there?

**Comment by tupui** [comment]
ST is that total indice yes.

For Gaussian processes, I would suggest having a look at scikit-learn. They have a pretty good tutorial on GP. Fitting hyper parameters is an art as usual, here things that work ok are a matern 5/2 kernel and using some robust global optimization (e.g. differential evolution from SciPy). I have some old implementation (as in, I did not run this since a few years so might need tweaks as libraries updated) in my package Batman (on my GutHub)

**Comment by tupui** [comment]
Here is a link to the repo https://github.com/tupui/batman/blob/master/batman/surrogate/kriging.py
