### ISSUE TITLE
Using SALib with correlated parameters

### ISSUE THREAD

**Issue by Engel23** [SALib/SALib#621]
Hi there,
I am a novice regarding sensitivity analyses and using SALib so my apologies for my very limited knowledge on these topics. 

I have a model in python to simulate plant growth and the input parameters are the soil moistures for 2 different soil depths, whereby the soil moisture at each depth varies over time. I am currently trying to find out at which soil depth the soil moisture has the most influence on the model output for every timestep and I was wondering if I could use a method in SALib to do a sensitivity analysis. I realise that the soil moistures at the 2 depths are correlated; e.g. when the moisture at depth 1 is low it is likely that the moisture at depth 2 is low as well. As I understand it, I could for example use the delta method in SALib for this situation since this method allows correlated input parameters (but perhaps I might have understood it wrong?).

My current code is;
```
problem = {'num_vars': 2,
           'names': ['theta_layer0',
                     'theta_layer1'],
           'bounds': [[theta_layer0_min, theta_layer0_max],
                      [theta_layer1_min, theta_layer1_max]]}
                                                            
param_values = latin.sample(problem, 4000)                                                                                    

def plant_growth_rate_wrapper(params):                                                                                
    theta_da = xr.DataArray(params, dims=['soil'])               # using this because the model takes an array as input                                                                                

    # definitions of other parameters which stay constant
    
    return plant_growth_rate(theta_da=theta_da, #other parameter definitions)

Y = []
for sample in param_values:
    output = plant_growth_rate_wrapper(sample)                                                                      
    Y.append(output)
Y = np.array(Y)                                                                                                         

Si = delta.analyze(problem, param_values, Y)                                                                                          
```
But I get an output which seems not to be correct (as the delta sum is larger than 1, which should not happen right?):

```
                       0             1
delta          15.436704     21.931797
delta_conf      2.093167      4.280893
S1              0.030882        0.0829
S1_conf         0.011565      0.023797
names       theta_layer0  theta_layer1
```
Hence, is perhaps another method more suitable for a sensitivity analysis in this situation or am I doing something wrong?

Any insights or comments are appreciated, many thanks!

**Comment by tupui** [comment]
Hi @Engel23, the delta measure is not bounded to 1. Sobol' indices are (without correlations).

**Comment by Engel23** [comment]
Hi @tupui, thank you for your answer! Then I guess I can continue with using the delta method in this approach.
