### ISSUE TITLE
DGSM connected to auto diff libraries?

### ISSUE THREAD

**Issue by patriciacmayer** [SALib/SALib#624]
Hello,

I was looking into your implementation of the DGSM method, and am wondering how the derivatives are computed in your implementation. It seems that the dgsm.analyze function takes the already-computed model evaluations at the base and perturbed values and takes the finite difference for the derivatives. If this is the case, what is the benefit of using this method vs. other SA methods that also rely on finite differences? Is there the possibility of using automatic differentiation libraries with your implementation?

Thank you :)

**Comment by tupui** [comment]
Hi 👋 thanks for the question. You read it write, there is no trick with automatic differentiation happening. That would be quite difficult to pull out if we wanted to make it applicable to any black box function. But if you have some ideas in mind, always happy to discuss and see what can be done.
