### ISSUE TITLE
sobol.analyze compatibility numpy =2.0.0

### ISSUE THREAD

**Issue by QLelong** [SALib/SALib#627]
Hello, 
I am using the sobol.analyze function on a specific problem and Y ndarray.
I receive an error on the sobol.py first order estimator saying that : 

--> 215 if y.ptp() == 0:
    216     warn(CONST_RESULT_MSG)
    217     return np.array([0.0])

AttributeError: `ptp` was removed from the ndarray class in NumPy 2.0. Use np.ptp(arr, ...) instead.

How can I manage this attribute error, given that it is inside the package? 
Thanks for your answer

**Comment by tupui** [comment]
Hi @QLelong thanks for reporting, I will close this in favour of the existing issue about NumPy 2.0. Help is more than welcomed 😃 

See #625
