### ISSUE TITLE
Sobol Analyze Attribute Error - ptp() moved in NumPy >= 2.0

### ISSUE THREAD

**Issue by mason-fox0** [SALib/SALib#629]
### Problem:
Running `sobol.analyze()` with NumPy 2.0 results in an Attribute Error. `y.ptp()` no longer appears to be valid syntax, as it has been removed as a class function from ndarray.

[ API: Remove ptp, itemset and newbyteorder from np.ndarray class #24682 ](https://github.com/numpy/numpy/pull/24682)

### Possible Fix:
Change all occurrences of `y.ptp()` -> `np.ptp(y)`

**Comment by tupui** [comment]
Hi @mason-fox0 thank you for reporting. This is fixed now, we will cut a release soon as we are getting more and more reports 😅 which is good to see as well as it shows people are using SALib and care enough to open an issue 🤗

**Comment by ConnectedSystems** [comment]
In case you were wondering @mason-fox0 , the relevant PR with the fix is #628

**Comment by mason-fox0** [comment]
Whoops, should have looked closer. Sorry for the duplicate issue. Thanks!
