### ISSUE TITLE
Time series model input

### ISSUE THREAD

**Issue by JoCook1997** [SALib/SALib#633]
Hi,

I have a crop model with 6 time-varying inputs (temperature, relative humidity etc). The inputs for the model are hourly. I wanted to test the sensitivity of a single value model output (e.g. crop yield), to variation in these inputs. Previously when testing the sensitivity of my model to a single parameter (not time-varying) I used the "bounds" section of the problem to define an upper and lower limit for the parameter value. For the case when I have a time-varying input, can I use the "bounds" to define a range for perturbing the input data (e.g. 0.8-1.2 would represent +/- 20%). Then I could use the sampler to obtain the values for perturbing the model inputs, use them to perturb the inputs, run the model, then run the analysis. 

I wanted to ask for the opinions of the community on whether this is possible, and if anyone has any alternate ideas? 

Thank you

**Comment by tupui** [comment]
Hi @JoCook1997 👋 

Basically time analysis are nothing more than single analysis done at multiple times.

Using a +- x % to generate bounds is considered a bad practice in general unless there are statistical reasons for these uniform distributions. If you do that, you are adding a non negligible bias to the analysis.

Selecting the correct distributions and hyper parameters for your inputs should be done very carefully and thoughtfully.

**Comment by JoCook1997** [comment]
Thank you for your reply, I think I need to research some more then to understand how I could approach this :)

**Comment by tupui** [comment]
No worries, if you like SA in general, we have a forum where many experts are active 😃 https://discord.gg/xJkUecaa
