### ISSUE TITLE
Conda dependency issue

### ISSUE THREAD

**Issue by mrvisscher** [SALib/SALib#639]
Hi SALib devs!

There seems to be a dependency issue in your library when installing through Conda right now. You've pinned Numpy support at `numpy>=1.20.3` ([conda forge feedstock](https://github.com/conda-forge/salib-feedstock/blob/b38d5e435b42661ce027fb3d17a098391306d240/recipe/meta.yaml#L21C7-L21C21)) but with your newest release `v1.5.1` you've dropped support for `numpy<2.0`. For example here:

https://github.com/SALib/SALib/blob/942a2d4c40c73e868abe464d6b21763820c0dc9c/src/SALib/analyze/delta.py#L146

The `np.trapezoid` function doesn't exist pre Numpy 2.0, causing execution to fail.

Could you rebuild for Conda using a new pin?

Thanks a lot!

**Comment by tupui** [comment]
Thanks for catching this. Do you want to make a PR?

**Comment by mrvisscher** [comment]
Please note that this only fixes the dependency issue on the Conda side. Your [PyPI dependency](https://github.com/SALib/SALib/blob/942a2d4c40c73e868abe464d6b21763820c0dc9c/pyproject.toml#L35) also needs to be fixed it seems, but I don't have enough experience with PyPI to handle this for you.
