### ISSUE TITLE
Grouping of parameters yields NaN sigma values.

### ISSUE THREAD

**Issue by JMH-gif** [SALib/SALib#643]
Hello there, 

firstly thank you for setting up SALIB, it's a great and intuitive tool! 

Currently, I am working on a model which includes wind and solar profiles as well as electricity market prices which change hourly. I made dynamic bounds for every hour for each parameter. In my analysis I group these parameters into a single e.g. cf_wind parameter over the time horizon of the model. However, for their sigma I get NaN Values. The sigma of mu_star does have a value again. I attached a screenshot:
![image](https://github.com/user-attachments/assets/eb4eea5a-e242-4ef0-9223-1fa4877a0ca9)

So far, in hours like midnight where there is never sun over a year, I add a very tiny range. I am wondering if maybe the inclusion of bounds for these time-steps is the problem here. Also the default-method of morris I am using allows the grouped parameters to take a step in opposite directions. They might cancel each other out as well. 

I am not quite sure and hope your feedback could help me identifiy the next steps.

Kind regards!

**Comment by JMH-gif** [comment]
Next time I just read more carefully^^

I just read the thesis of Will Usher where it is clearly described that  sigma and mu and not usable anymore if you use groups.

**Comment by ConnectedSystems** [comment]
Thanks for raising the issue and glad to hear you find SALib intuitive. 

Perhaps it is worthwhile mentioning this "side-effect" of NaN sigma and mu when performing grouped analysis in the documentation.

I will mark it as a potential improvement.
