### ISSUE TITLE
Travis CI has a new container based infrastructure, but it doesn't allow `sudo`

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#67]
Details [here](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade).

**Comment by jdherman** [comment]
Thanks Will. It looks like the latest Travis build worked fine -- what does this mean in practice? New configuration files?

**Comment by willu47** [comment]
Yep, Travis is working fine, but on 'legacy infrastructure' apparently.  This is just a placeholder to jog our collective memories to do this sometime in the future, but not critical.

**Comment by jdherman** [comment]
Ok well thanks for catching the update. I never figured out the right way to use virtual environments. If I have time I'll look into it.
