### ISSUE TITLE
A new test function from Oakley et al. (2004)

### ISSUE THREAD

**Issue by willu47** [SALib/SALib#74]
In the following paper, Oakley et al. (2004) propose a test function of the form 

![test_function_oakley](https://cloud.githubusercontent.com/assets/3727919/9544183/68df8f82-4d76-11e5-9936-20873dec1e2d.png)

The data for the test function is available on the author's [website](http://www.jeremy-oakley.staff.shef.ac.uk/psa_example.txt).  The analytical results are in the paper (table 1 on page 764).

Oakley, Jeremy E., and Anthony O’Hagan. “Probabilistic Sensitivity Analysis of Complex Models: A Bayesian Approach.” Journal of the Royal Statistical Society: Series B (Statistical Methodology) 66, no. 3 (August 2004): 751–769. doi:10.1111/j.1467-9868.2004.05304.x.

**Comment by ConnectedSystems** [comment]
Closed by #474
