### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by dhadka** [SALib/SALib#75]
The methods are currently documented using comments and not docstrings.  Also missing details for the arguments.  I am working on a fix for this now and will send a pull-request when completed.

Would also be nice to setup online documentation when this issue is resolved.

**Comment by jdherman** [comment]
Thanks Dave, this is much needed and unglamorous work. I'll be happy to set up a readthedocs.

**Comment by willu47** [comment]
It would be great to have comprehensive documentation.  @jdherman check out [PyScaffold](http://pyscaffold.readthedocs.org).  This is a really useful package which sets up Python projects (normally before you start).  It may give a shortcut for setting up documentation within SALib.  [Sphinx](http://sphinx-doc.org/index.html) seems to be the standard for Python documentation.

**Comment by jdherman** [comment]
Alright thanks. Reading this stuff I'm a little confused about the steps involved if the project already exists. We'll figure it out when the time comes.

**Comment by willu47** [comment]
Hi @jdherman.  I was trying to help, but I'm not sure I was particularly helpful!  :octopus: 

I read through ReadTheDocs, and their instructions seems pretty straightforward so that's probably the way forward.

**Comment by dhadka** [comment]
Jon,

Started adding some documentation on my fork here: https://github.com/dhadka/SALib.
An example of the results: http://salib.readthedocs.org/en/latest/index.html

Dave

**Comment by jdherman** [comment]
Awesome! Thanks for doing this. So at this point is it just a matter of adding docstrings for all of the functions?

**Comment by willu47** [comment]
This is great!  Do you want to submit a pull request and we can continue commenting from their?

**Comment by willu47** [comment]
And a follow up question from @jdherman's, is there a way to distinguish between private and public functions?  For example, on the [api](http://salib.readthedocs.org/en/latest/api.html#module-SALib.sample.fast_sampler) page at the moment, `find smallest()` is a helper function which probably doesn't need to be exposed in the documentation (although please correct me if it should be), while `sample` definitely should be.  NB these are all from the factorial module called `SALib.sample.ff`

**Comment by willu47** [comment]
I'm going to close this as it's covered in PR #77
