### ISSUE TITLE
Publish something

### ISSUE THREAD

**Issue by jdherman** [SALib/SALib#83]
@willu47 and @joerivanengelen have discussed writing a paper based on SALib. A couple of thoughts come to mind which could be mixed and matched:
- Just a software announcement, "this thing exists"
- A description of all of the open source tools we're using (not many academic software packages have this kind of transparency and testing)
- A methods comparison, convergence on some test functions?

A combination of some or all of those things could make for a nice paper. The journal I'm most familiar with for this kind of paper is Environmental Modelling & Software. Let's keep a list of ideas here to get started if you're interested.

**Comment by willu47** [comment]
@jdherman I've around four weeks to kick some paper ideas around as I'm moving jobs and have completed my PhD! Happy to start working on bringing a paper together.

**Comment by willu47** [comment]
I've added a [repository](https://github.com/SALib/JournalPaper) in the SALib organisation to host a journal paper.  You can view the current state of the article on [Authorea](https://www.authorea.com/users/15415/articles/118717/_show_article?access_token=My_TsRnXRjtf3raqF-Tekw).

**Comment by jdherman** [comment]
Thanks @willu47 that's great. Congrats on finishing your PhD and the new job!

**Comment by willu47** [comment]
@jdherman [This](http://joss.theoj.org/) might be a good option to get a publication for minimal effort from SALib?

**Comment by Anto-F** [comment]
A little off topic but I plan to write a paper, using some SALib tools.
How to properly cite SALib in my paper ?

**Comment by jdherman** [comment]
Thanks @Anto-F ... the library is currently in review for the Journal of Open Source Software:
http://joss.theoj.org/papers/431262803744581c1d4b6a95892d3343

So hopefully we will have an official citation soon. In the meantime I think people have just been using the URL.

**Comment by willu47** [comment]
We do have a doi, as well, via [zenodo](https://zenodo.org/record/160164#.WBoRHeGLSEI)

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.160164.svg)](https://doi.org/10.5281/zenodo.160164)

**Comment by willu47** [comment]
Our Joss paper is now published and can be viewed [here](http://dx.doi.org/10.21105/joss.00097).

**Comment by JoerivanEngelen** [comment]
Congratulations!
