### ISSUE TITLE
sensitivity analysis with SALib [nan,nan,nan]

### ISSUE THREAD

**Issue by qwertz1406** [SALib/SALib#92]
Hey I want to do a sensitivity analysis using SALib. The model is based on differential equations to solve the temperature after a certain time with odeint.

Problem: I do not get any error, but it just say [nan,nan,nan] for my three values.
Is it allowed to post Code in here? Otherwise here is a Link to my Code: http://stackoverflow.com/questions/34943871/sensitivity-analysis-with-salib-nan-nan-nan

Maybe i am missing something. Some suggestions would be nice. Thanks

**Comment by willu47** [comment]
I've responded to your question on StackOverflow.  The problem does not seem to be with SALib, but with how you've defined your ode and wrapper function.  I suggest you write an ode which you can show works for a specific input and then use SALib to generate a sample to run through the ode.

**Comment by qwertz1406** [comment]
Hey I added the working code without SALib on Stackflow.
This works fine, but i dont get how to use SALib now i created the samples with:
param_values = saltelli.sample(problem, 1000, calc_second_order=True)
I thinks i do not know how to loop the odefunk() the right way. Normally odeint is not a function for me, but it needs to be for SALib right?

**Comment by qwertz1406** [comment]
Hey thanks for you help I added a few last questions to your code.. I want to understand the way your program works :)
