### ISSUE TITLE
dists without groups causes error

### ISSUE THREAD

**Issue by jdherman** [SALib/SALib#96]
from @calvinwhealton ...

It seems that reading-in a problem file with no groups but with distributions is triggering an error in lines 183-185 of __init__.py. The error is that there are no groups so the results will not be meaningful and it does not read-in the file. Was this an intentional change because of some of the methods (Morris)? I think a simple work around is to define groups and once the problem file is read-in to set the ‘groups' to None, although it is inelegant.

**Comment by jdherman** [comment]
I think I messed up something here, but how should this case be handled in the parameter file?

If there is no "groups" column, how does the parser know to skip ahead to "dists"?

**Comment by willu47** [comment]
Maybe make one group per parameter the default, which is only changed if a groups column is detected in the param file?  But we could be heading down a dead-end here.

**Comment by jdherman** [comment]
Yea this is an edge case but worth a quick fix. I don't think there is a good way to tell whether an arbitrary 4th column is the group name or distribution. So Calvin's suggestion is to allow a dummy group column where they are all "NA". I can add this.

Calvin adds over email:
I initially had a case for if all the group names were the same (e.g. all NA), then it would set groups to None. I needed an entry for the groups column in the input otherwise the distribution column would be read-in as groups (I tried this earlier). Could the code be changed to something like this so that there would be a warning, but not an error that prevents future computation. (I am not an expert on errors versus warnings in Python)

```python
    if groups == names:
        groups = None
    elif len(set(groups)) == 1:
        groups = None
        raise Warning('''Only one group defined, analysis completed for non-grouped input

''')
```

**Comment by calvinwhealton** [comment]
Another possibility is to have users repeat the variable name as the group and then specify the fifth column as distribution. This should cause the first `if` condition to be used. I tried it with the following input text file and it seemed to work. Unless there were conditions where the group names were checked against the possible distribution specifications I do not think that the code could determine whether the fourth column is a group or a distribution.

P1,0.0,1.0,P1,unif
P2,1.0,.75,P2,triang
P3,0.0,.2,P3,norm
P4,0.0,.2,P4,lognorm
P5,-1.0,1.0,P5,unif
P6,1.0,.25,P6,triang

The problem defined from this file is, which :

`{'bounds': [[0.0, 1.0],
  [1.0, 0.75],
  [0.0, 0.2],
  [0.0, 0.2],
  [-1.0, 1.0],
  [1.0, 0.25]],
 'dists': ['unif', 'triang', 'norm', 'lognorm', 'unif', 'triang'],
 'groups': None,
 'names': ['P1', 'P2', 'P3', 'P4', 'P5', 'P6'],
 'num_vars': 6}`

**Comment by jdherman** [comment]
Ok sure that's fine too. Let's just go with this, and I'll delete the pull request and close this issue. 

Thanks!
