### ISSUE TITLE
Use saltelli.sample method with boolean or discrete input parameters?

### ISSUE THREAD

**Issue by LindsayLBE** [SALib/SALib#98]
I would like to use the Sobol method to run a sensitivity analysis on a complex model in python. This model includes continuous, discrete, as well as boolean input parameters. Is it possible to use the SALib python package to perform this analysis? Specifically, can I use the saltelli.sample method (or somehow modify it) to generate quasi-random sets of my input parameters when some parameters don't actually have upper or lower bounds but instead only discrete options? For instance, if my input parameters looked more like this:

x1: continuous (so possible values could be 0, 0.01, 1.2...0.987)
x2: boolean (so possible values are 0 or 1)
x3: discrete (so possible values are 0, 0.25, 0.5, 0.75, or 1)

It would need to generate quasi-random sample sets for the continuous vars, but with boolean vars, for instance, it would need to only select from 0 or 1.

Thanks for the help.

**Comment by jdherman** [comment]
Hi @LindsayLBE, thanks for using the library.

Right now there is no way to (properly) sample discrete or boolean values. So I'd suggest a hack: sample a continous range and round to the nearest value you want.

If it's a boolean variable, sample on [0,1] and just round up or down. If it's discrete with N outcomes, sample on [0,N] and round to the nearest integer.

There was a blog post about this a while back:
https://waterprogramming.wordpress.com/2014/02/11/extensions-of-salib-for-more-complex-sensitivity-analyses/    (item 2 on the list)

It is a little hacky, but I think this is the more-or-less accepted way of doing things, especially if you're mixing continuous and discrete variables.

**Comment by LindsayLBE** [comment]
Thank you! Very helpful and simple fix.

**Comment by orcunkoraliseri** [comment]
Is there any development for SALib concerning the discrete sampling for input parameters?

**Comment by ReshmaCC** [comment]
Is there any update to this question? Can SALib be used for discrete sampling?

**Comment by willu47** [comment]
Hi @ReshmaCC  and @orcunkoraliseri  - there's no immediate plan to implement this ourselves, but if it's a popular request, we could definitely accept a pull request that implements this functionality.

**Comment by jdherman** [comment]
Yea, the only solution to implement on our side would be the rounding strategy mentioned above. And I think (1) it's simple enough for users to implement themselves when generating the samples, and (2) it's an unofficial hack, not documented in literature, so I'd rather it not become part of the library.
